import { createHash } from "crypto";

export interface ReconcileSaleInput { platform:string; external_sale_id:string; external_order_id?:string; colors_checkout_id?:string; external_status:string; customer_name?:string; customer_email?:string; customer_whatsapp?:string; customer_cpf?:string; product_slug?:string; product_name?:string; offer?:string; payment_url?:string; payment_method?:string; pix_copy_paste?:string; pix_qr_code?:string; quantity?:number; kit_size?:number; unit_price_cents?:number; total_price_cents?:number; coupon?:string; affiliate_code?:string; affiliate_external_id?:string; affiliate_name?:string; approved_at?:string; raw?:Record<string,unknown>; source:"webhook"|"import"|"manual"; }
export interface ReconcileResult { opportunity_id:string; contact_id:string|null; communication_contact_id:string|null; affiliate_id:string|null; order_id:string|null; created_opportunity:boolean; matched_by:"colors_checkout_id"|"external_sale_id"|"email"|"whatsapp"|"cpf_hash"|"new"; new_stage:string; }
const STATUS_TO_STAGE:Record<string,string>={approved:"cliente",paid:"cliente",pending:"pagamento_pendente",in_process:"pagamento_pendente",pix_pending:"pagamento_pendente",boleto_pending:"pagamento_pendente",rejected:"perdido",cancelled:"perdido",canceled:"perdido",refunded:"perdido",chargeback:"perdido",shipped:"cliente",delivered:"recompra"};
const STATUS_TO_ORDER:Record<string,string>={approved:"confirmed",paid:"confirmed",pending:"draft",in_process:"draft",pix_pending:"draft",boleto_pending:"draft",rejected:"cancelled",cancelled:"cancelled",canceled:"cancelled",refunded:"refunded",chargeback:"refunded",shipped:"processing",delivered:"fulfilled"};
const STATUS_TO_EVENT:Record<string,string>={approved:"PAYMENT_APPROVED",paid:"PAYMENT_APPROVED",pending:"PAYMENT_PENDING",in_process:"PAYMENT_PENDING",pix_pending:"PAYMENT_PENDING",boleto_pending:"PAYMENT_PENDING",rejected:"PAYMENT_FAILED",cancelled:"ORDER_CANCELED",canceled:"ORDER_CANCELED",refunded:"ORDER_REFUNDED",chargeback:"ORDER_CHARGEBACK",shipped:"ORDER_SHIPPED",delivered:"ORDER_DELIVERED"};
const normEmail=(v?:string)=>v?v.trim().toLowerCase():null;const normPhone=(v?:string)=>{const d=v?v.replace(/\D/g,""):"";return d.length>=8?d:null};function hashCpf(v?:string){if(!v)return null;const clean=v.replace(/\D/g,"");if(clean.length<11)return null;return createHash("sha256").update(`colors:${clean}`).digest("hex");}
const cleanText=(v?:string)=>{const s=v?.trim();return s?s.slice(0,4096):undefined};
const recovery=(input:ReconcileSaleInput)=>({payment_url:cleanText(input.payment_url??input.offer)??null,payment_method:cleanText(input.payment_method)??null,pix_copy_paste:cleanText(input.pix_copy_paste)??null,pix_qr_code:cleanText(input.pix_qr_code)??null,updated_at:new Date().toISOString()});

export async function reconcileColorsSale(sb:any,input:ReconcileSaleInput):Promise<ReconcileResult>{
 const emailN=normEmail(input.customer_email),phoneN=normPhone(input.customer_whatsapp),cpfHash=hashCpf(input.customer_cpf),status=input.external_status.toLowerCase();const newStage=STATUS_TO_STAGE[status]??"qualificado";const now=new Date().toISOString();
 const{data:tenant,error:tenantError}=await sb.from("communication_tenants").select("id,company_id").eq("slug","colorssaude").maybeSingle();if(tenantError||!tenant?.id||!tenant?.company_id)throw new Error("colors_tenant_missing");
 let contact:any=null;if(emailN)({data:contact}=await sb.from("colors_contacts").select("id,communication_contact_id,first_touch,last_touch").eq("email_normalized",emailN).maybeSingle());if(!contact&&phoneN)({data:contact}=await sb.from("colors_contacts").select("id,communication_contact_id,first_touch,last_touch").eq("whatsapp_normalized",phoneN).maybeSingle());if(!contact&&cpfHash)({data:contact}=await sb.from("colors_contacts").select("id,communication_contact_id,first_touch,last_touch").eq("cpf_hash",cpfHash).maybeSingle());
 let coreId=contact?.communication_contact_id??null;if(!coreId){let core:any=null;if(emailN)({data:core}=await sb.from("communication_contacts").select("id").eq("tenant_id",tenant.id).eq("attributes->>email_normalized",emailN).is("merged_into_contact_id",null).maybeSingle());if(!core&&phoneN)({data:core}=await sb.from("communication_contacts").select("id").eq("tenant_id",tenant.id).eq("attributes->>whatsapp_normalized",phoneN).is("merged_into_contact_id",null).maybeSingle());if(core?.id)coreId=core.id;else if(input.customer_name||emailN||phoneN){const{data:created,error}=await sb.from("communication_contacts").insert({tenant_id:tenant.id,display_name:input.customer_name??"Cliente Color Saúde",locale:"pt-BR",timezone:"America/Sao_Paulo",attributes:{email:input.customer_email??null,email_normalized:emailN,whatsapp:input.customer_whatsapp??null,whatsapp_normalized:phoneN,brand:"color_saude",source:`${input.platform}_${input.source}`}}).select("id").single();if(error)throw new Error(error.message);coreId=created.id;}}
 let contactId=contact?.id??null;const nba=newStage==="cliente"?"RETENTION":newStage==="pagamento_pendente"?"RECOVER_CHECKOUT":newStage==="perdido"?"ANSWER":"QUALIFY";if(contactId){await sb.from("colors_contacts").update({full_name:input.customer_name??undefined,email:input.customer_email??undefined,whatsapp:input.customer_whatsapp??undefined,cpf_hash:cpfHash??undefined,communication_contact_id:coreId,lifecycle_stage:newStage,next_best_action:nba,last_seen_at:now}).eq("id",contactId);}else if(input.customer_name||emailN||phoneN){const{data:created,error}=await sb.from("colors_contacts").insert({full_name:input.customer_name??"Cliente Color Saúde",email:input.customer_email??null,whatsapp:input.customer_whatsapp??"",cpf_hash:cpfHash,communication_contact_id:coreId,consent_lgpd:false,consent_marketing:false,lifecycle_stage:newStage,next_best_action:nba,last_seen_at:now}).select("id").single();if(error)throw new Error(error.message);contactId=created.id;}
 let affiliateId:string|null=null;if(input.affiliate_external_id){const{data}=await sb.from("colors_affiliates").select("id").eq("external_platform",input.platform).eq("external_id",input.affiliate_external_id).maybeSingle();affiliateId=data?.id??null;}if(!affiliateId&&input.affiliate_code){const{data}=await sb.from("colors_affiliates").select("id").eq("code",input.affiliate_code).maybeSingle();affiliateId=data?.id??null;}if(!affiliateId&&(input.affiliate_code||input.affiliate_external_id)){const code=input.affiliate_code??`ext_${input.platform}_${input.affiliate_external_id}`;const{data,error}=await sb.from("colors_affiliates").upsert({code,full_name:input.affiliate_name??code,external_platform:input.platform,external_id:input.affiliate_external_id??null,status:"ativo",metadata:{source:input.source}},{onConflict:"code"}).select("id").single();if(!error&&data)affiliateId=data.id;}
 let oppId:string|null=null;let matched:ReconcileResult["matched_by"]="new";if(input.colors_checkout_id){const{data}=await sb.from("colors_opportunities").select("id").eq("colors_checkout_id",input.colors_checkout_id).maybeSingle();if(data){oppId=data.id;matched="colors_checkout_id";}}if(!oppId){const{data}=await sb.from("colors_opportunities").select("id").eq("external_platform",input.platform).eq("external_sale_id",input.external_sale_id).maybeSingle();if(data){oppId=data.id;matched="external_sale_id";}}if(!oppId&&contactId){const{data}=await sb.from("colors_opportunities").select("id").eq("contact_id",contactId).is("external_sale_id",null).order("created_at",{ascending:false}).limit(1).maybeSingle();if(data){oppId=data.id;matched=emailN?"email":phoneN?"whatsapp":"cpf_hash";}}
 const recoveryData=recovery(input);const oppPatch:any={contact_id:contactId,affiliate_id:affiliateId,stage:newStage,next_best_action:nba,external_platform:input.platform,external_sale_id:input.external_sale_id,external_order_id:input.external_order_id??null,external_status:input.external_status,reconciled_at:now,metadata:{payment_recovery:recoveryData}};if(recoveryData.payment_url)oppPatch.offer_url=recoveryData.payment_url;if(input.product_slug)oppPatch.product_slug=input.product_slug;if(input.product_name)oppPatch.product_name=input.product_name;if(input.kit_size)oppPatch.kit_size=input.kit_size;if(input.quantity)oppPatch.quantity=input.quantity;if(input.unit_price_cents!=null)oppPatch.unit_price_cents=input.unit_price_cents;if(input.total_price_cents!=null)oppPatch.total_price_cents=input.total_price_cents;if(input.coupon)oppPatch.coupon=input.coupon;
 let createdOpp=false;if(oppId){const{data:existing}=await sb.from("colors_opportunities").select("metadata").eq("id",oppId).maybeSingle();oppPatch.metadata={...(existing?.metadata??{}),payment_recovery:recoveryData};const{error}=await sb.from("colors_opportunities").update(oppPatch).eq("id",oppId);if(error)throw new Error(error.message);}else{const{data,error}=await sb.from("colors_opportunities").insert({colors_checkout_id:input.colors_checkout_id??`rec_${input.platform}_${input.external_sale_id}`,product_slug:input.product_slug??"desconhecido",product_name:input.product_name??"Produto Color Saúde",kit_size:input.kit_size??1,quantity:input.quantity??1,...oppPatch}).select("id").single();if(error)throw new Error(error.message);oppId=data.id;createdOpp=true;}
 await sb.from("colors_opportunity_events").insert({opportunity_id:oppId,event_type:input.source,to_stage:newStage,payload:{matched_by:matched,external_sale_id:input.external_sale_id,external_order_id:input.external_order_id??null,external_status:input.external_status,payment_recovery:recoveryData},actor:input.source});
 let orderId:string|null=null;const orderNumber=String(input.external_order_id??input.external_sale_id);const orderStatus=STATUS_TO_ORDER[status]??"draft";const total=(input.total_price_cents??0)/100;const orderMetadata={brand:"color_saude",platform:input.platform,external_sale_id:input.external_sale_id,opportunity_id:oppId,affiliate_id:affiliateId,coupon:input.coupon??null,payment_recovery:recoveryData};const{data:existingOrder}=await sb.from("sales_orders").select("id").eq("company_id",tenant.company_id).eq("order_number",orderNumber).maybeSingle();if(existingOrder?.id){orderId=existingOrder.id;await sb.from("sales_orders").update({contact_id:coreId,customer_name:input.customer_name??null,status:orderStatus,currency:"BRL",subtotal:total,total,metadata:orderMetadata}).eq("id",orderId);}else{const{data:createdOrder,error}=await sb.from("sales_orders").insert({company_id:tenant.company_id,order_number:orderNumber,contact_id:coreId,customer_name:input.customer_name??null,status:orderStatus,currency:"BRL",subtotal:total,total,metadata:orderMetadata}).select("id").single();if(!error&&createdOrder){orderId=createdOrder.id;if(input.product_name){await sb.from("sales_order_items").insert({order_id:orderId,company_id:tenant.company_id,description:input.product_name,quantity:input.quantity??1,unit_price:(input.unit_price_cents??0)/100,total:(input.total_price_cents??0)/100});}}}
 const eventType=STATUS_TO_EVENT[status]??"ORDER_UPDATED";await sb.from("colors_event_bus").upsert({event_id:`${input.platform}:${input.external_sale_id}:${eventType}`,event_type:eventType,aggregate_type:"order",aggregate_id:orderId??orderNumber,payload:{platform:input.platform,external_sale_id:input.external_sale_id,external_order_id:orderNumber,opportunity_id:oppId,order_id:orderId,contact_id:contactId,communication_contact_id:coreId,affiliate_id:affiliateId,status:input.external_status,total_price_cents:input.total_price_cents??null,approved_at:input.approved_at??null,payment_recovery:recoveryData}},{onConflict:"event_id",ignoreDuplicates:true});
 return{opportunity_id:oppId!,contact_id:contactId,communication_contact_id:coreId,affiliate_id:affiliateId,order_id:orderId,created_opportunity:createdOpp,matched_by:matched,new_stage:newStage};
}
