import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { createHash, randomBytes } from "crypto";
import { z } from "zod";

export const getColorsGroupAccess=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const sb:any=context.supabase;const{data:linked,error:linkError}=await sb.rpc("colors_link_current_user");if(linkError)throw linkError;const contactId=linked?.colors_contact_id;if(!contactId)throw new Error("colors_contact_missing");const{data:status,error}=await sb.rpc("colors_refresh_group_eligibility",{p_contact_id:contactId});if(error)throw error;if(status!=="eligible")return{eligible:false,status};const url=process.env.COLORS_GROUP_URL??"";if(!url)return{eligible:true,status:"eligible",configured:false};await sb.from("colors_group_access").update({eligibility_status:"invited",invite_sent_at:new Date().toISOString(),metadata:{source:"authenticated_customer_account"}}).eq("contact_id",contactId).eq("eligibility_status","eligible");return{eligible:true,status:"invited",configured:true,url};});

const referralSchema=z.object({reasonCode:z.enum(["medication_interaction","pregnancy_breastfeeding","hypertension","allergy","multiple_medications","clinical_uncertainty","other"])});
export const createColorsChrismedReferral=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((raw:unknown)=>referralSchema.parse(raw)).handler(async({context,data})=>{const sb:any=context.supabase;const{data:linked,error:linkError}=await sb.rpc("colors_link_current_user");if(linkError)throw linkError;const contactId=linked?.colors_contact_id,coreId=linked?.communication_contact_id;if(!contactId||!coreId)throw new Error("colors_contact_missing");const{data:orders,error:orderError}=await sb.from("sales_orders").select("id").eq("company_id",(await sb.from("companies").select("id").eq("document","58.255.587/0001-60").maybeSingle()).data?.id).eq("contact_id",coreId).in("status",["confirmed","processing","fulfilled"]).limit(1);if(orderError)throw orderError;const verified=Array.isArray(orders)&&orders.length>0;if(!verified)return{created:false,reason:"verified_colors_origin_required"};const token=randomBytes(32).toString("base64url");const tokenHash=createHash("sha256").update(token).digest("hex");const expires=new Date(Date.now()+7*86400000).toISOString();const{data:row,error}=await sb.from("colors_chrismed_referrals").insert({colors_contact_id:contactId,communication_contact_id:coreId,referral_token_hash:tokenHash,referral_reason_code:data.reasonCode,source_channel:"colors_customer_account",colors_origin_verified:true,status:"created",coupon_code:"COLORS50",expires_at:expires,operational_metadata:{data_boundary:"operational_only",no_clinical_data:true}}).select("id").single();if(error)throw error;const url=`https://chrismed.impulsionando.com.br/agendar?modality=telemedicina&colors_ref=${encodeURIComponent(token)}`;return{created:true,referralId:row.id,expiresAt:expires,coupon:"COLORS50",url};});
