import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { createHash, randomUUID } from "crypto";
import { isValidCPF } from "@/lib/validators";

const optionalCpf=z.string().trim().max(20).optional().superRefine((value,ctx)=>{if(value&&!isValidCPF(value))ctx.addIssue({code:z.ZodIssueCode.custom,message:"CPF inválido."});});
const schema=z.object({
  fullName:z.string().trim().min(2).max(120),email:z.string().trim().email().max(255).optional().or(z.literal("").transform(()=>undefined)),whatsapp:z.string().trim().min(8).max(30),cpf:optionalCpf,
  cep:z.string().trim().max(10).optional(),addressLine1:z.string().trim().max(200).optional(),addressNumber:z.string().trim().max(20).optional(),addressComplement:z.string().trim().max(120).optional(),neighborhood:z.string().trim().max(120).optional(),city:z.string().trim().max(120).optional(),state:z.string().trim().max(2).optional(),
  consentLgpd:z.boolean(),consentMarketing:z.boolean().optional().default(false),productSlug:z.string().trim().min(1).max(80),productName:z.string().trim().min(1).max(160),kitSize:z.number().int().min(1).max(12).default(1),quantity:z.number().int().min(1).max(50).default(1),unitPriceCents:z.number().int().nonnegative().optional(),totalPriceCents:z.number().int().nonnegative().optional(),coupon:z.string().trim().max(40).optional(),offerUrl:z.string().trim().max(500).optional(),
  utmSource:z.string().trim().max(120).optional(),utmMedium:z.string().trim().max(120).optional(),utmCampaign:z.string().trim().max(160).optional(),utmContent:z.string().trim().max(160).optional(),utmTerm:z.string().trim().max(160).optional(),clickId:z.string().trim().max(160).optional(),cookieId:z.string().trim().max(160).optional(),origin:z.string().trim().max(120).optional(),affiliateCode:z.string().trim().max(60).optional(),device:z.string().trim().max(60).optional(),browser:z.string().trim().max(120).optional(),sessionId:z.string().trim().max(80).optional(),
});
export type StartColorsCheckoutInput=z.input<typeof schema>;
const normEmail=(v?:string)=>v?v.trim().toLowerCase():null;const normPhone=(v?:string)=>v?v.replace(/\D/g,""):null;
function hashCpf(v?:string){if(!v)return null;const clean=v.replace(/\D/g,"");if(!isValidCPF(clean))return null;return createHash("sha256").update(`colors:${clean}`).digest("hex");}
function detectPlatform(url?:string){const u=(url??"").toLowerCase();return u.includes("maisfy")||u.includes("/m")?"maisfy":"unknown";}

export const startColorsCheckout=createServerFn({method:"POST"}).inputValidator((raw:unknown)=>schema.parse(raw)).handler(async({data})=>{
  const {supabaseAdmin}=await import("@/integrations/supabase/client.server");const sb:any=supabaseAdmin;const now=new Date().toISOString();
  const emailN=normEmail(data.email),phoneN=normPhone(data.whatsapp),cpfHash=hashCpf(data.cpf);
  const {data:tenant,error:tenantErr}=await sb.from("communication_tenants").select("id,company_id").eq("slug","colorssaude").maybeSingle();if(tenantErr||!tenant?.id)throw new Error("Configuração da Colors Saúde indisponível.");
  let local:any=null;if(emailN)({data:local}=await sb.from("colors_contacts").select("id,communication_contact_id,first_touch").eq("email_normalized",emailN).maybeSingle());if(!local&&phoneN)({data:local}=await sb.from("colors_contacts").select("id,communication_contact_id,first_touch").eq("whatsapp_normalized",phoneN).maybeSingle());
  let coreId=local?.communication_contact_id??null;if(!coreId){let core:any=null;if(emailN)({data:core}=await sb.from("communication_contacts").select("id").eq("tenant_id",tenant.id).eq("attributes->>email_normalized",emailN).is("merged_into_contact_id",null).maybeSingle());if(!core&&phoneN)({data:core}=await sb.from("communication_contacts").select("id").eq("tenant_id",tenant.id).eq("attributes->>whatsapp_normalized",phoneN).is("merged_into_contact_id",null).maybeSingle());if(core?.id)coreId=core.id;else{const {data:created,error}=await sb.from("communication_contacts").insert({tenant_id:tenant.id,display_name:data.fullName,locale:"pt-BR",timezone:"America/Sao_Paulo",attributes:{email:data.email??null,email_normalized:emailN,whatsapp:data.whatsapp,whatsapp_normalized:phoneN,brand:"colors_saude",source:data.origin??"precheckout"}}).select("id").single();if(error)throw new Error("Não foi possível registrar o cliente.");coreId=created.id;}}
  const touch={utm_source:data.utmSource??null,utm_medium:data.utmMedium??null,utm_campaign:data.utmCampaign??null,utm_content:data.utmContent??null,utm_term:data.utmTerm??null,click_id:data.clickId??null,cookie_id:data.cookieId??null,origin:data.origin??"precheckout",affiliate_code:data.affiliateCode??null,session_id:data.sessionId??null,at:now};const firstTouch=local?.first_touch&&Object.keys(local.first_touch).length?local.first_touch:touch;
  const payload={full_name:data.fullName,email:data.email??null,whatsapp:data.whatsapp,cpf_hash:cpfHash,cep:data.cep??null,address_line1:data.addressLine1??null,address_number:data.addressNumber??null,address_complement:data.addressComplement??null,neighborhood:data.neighborhood??null,city:data.city??null,state:data.state??null,consent_lgpd:data.consentLgpd,consent_marketing:data.consentMarketing??false,marketing_consent:data.consentMarketing??false,whatsapp_consent:data.consentMarketing??false,email_consent:data.consentMarketing??false,consent_timestamp:now,consent_source:"colors_precheckout",first_touch:firstTouch,last_touch:touch,last_seen_at:now,communication_contact_id:coreId,next_best_action:"SEND_CHECKOUT"};
  let contactId=local?.id??null;if(contactId){const {error}=await sb.from("colors_contacts").update(payload).eq("id",contactId);if(error)throw new Error("Não foi possível atualizar o cadastro.");}else{const {data:created,error}=await sb.from("colors_contacts").insert(payload).select("id").single();if(error)throw new Error("Não foi possível salvar o cadastro.");contactId=created.id;}
  let affiliateId:string|null=null;if(data.affiliateCode){const {data:aff}=await sb.from("colors_affiliates").select("id").eq("code",data.affiliateCode).maybeSingle();affiliateId=aff?.id??null;if(affiliateId){await sb.from("colors_affiliate_clicks").insert({affiliate_id:affiliateId,affiliate_code:data.affiliateCode,session_id:data.sessionId??null,click_id:data.clickId??null,landing_url:data.offerUrl??null,utm_source:data.utmSource??null,utm_medium:data.utmMedium??null,utm_campaign:data.utmCampaign??null,utm_content:data.utmContent??null,utm_term:data.utmTerm??null});}}
  const platform=detectPlatform(data.offerUrl);if(platform!=="maisfy")throw new Error("Checkout MaisFy não configurado para esta oferta.");
  const {data:cap}=await sb.from("colors_commerce_platforms").select("checkout_mode,transparent_checkout_verified,active").eq("platform","maisfy").maybeSingle();if(!cap?.active)throw new Error("Checkout MaisFy temporariamente indisponível.");
  const colorsCheckoutId=`col_${Date.now().toString(36)}_${randomUUID().slice(0,8)}`;
  const {data:opp,error:oppErr}=await sb.from("colors_opportunities").insert({colors_checkout_id:colorsCheckoutId,contact_id:contactId,affiliate_id:affiliateId,product_slug:data.productSlug,product_name:data.productName,kit_size:data.kitSize,quantity:data.quantity,unit_price_cents:data.unitPriceCents??null,total_price_cents:data.totalPriceCents??null,coupon:data.coupon??null,offer_url:data.offerUrl??null,utm_source:data.utmSource??null,utm_medium:data.utmMedium??null,utm_campaign:data.utmCampaign??null,utm_content:data.utmContent??null,utm_term:data.utmTerm??null,click_id:data.clickId??null,cookie_id:data.cookieId??null,first_touch:firstTouch,last_touch:touch,assisted_touch:{iris:false},origin:data.origin??null,device:data.device??null,browser:data.browser??null,session_id:data.sessionId??null,stage:"checkout_iniciado",next_best_action:"SEND_CHECKOUT",external_platform:"maisfy",metadata:{communication_contact_id:coreId,checkout_mode:cap?.checkout_mode??"redirect_precheckout",transparent_checkout_verified:cap?.transparent_checkout_verified??false}}).select("id,colors_checkout_id").single();if(oppErr)throw new Error("Não foi possível iniciar o checkout.");
  await sb.from("colors_event_bus").insert({event_id:`checkout-started:${opp.id}`,event_type:"CHECKOUT_STARTED",aggregate_type:"opportunity",aggregate_id:opp.id,payload:{opportunity_id:opp.id,colors_checkout_id:opp.colors_checkout_id,contact_id:contactId,communication_contact_id:coreId,affiliate_id:affiliateId,platform:"maisfy",product_slug:data.productSlug,utm:touch}});
  return{opportunityId:opp.id,colorsCheckoutId:opp.colors_checkout_id,contactId,communicationContactId:coreId,affiliateId,platform:"maisfy",checkoutMode:cap?.checkout_mode??"redirect_precheckout",transparentCheckoutVerified:cap?.transparent_checkout_verified??false};
});
