import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { createHash, randomBytes } from "crypto";
import { z } from "zod";

async function linkedIdentity(context:any){const sb:any=context.supabase;const{data,error}=await sb.rpc("colors_link_current_user");if(error)throw error;if(!data?.colors_contact_id||!data?.communication_contact_id)throw new Error("colors_contact_missing");return{colorsContactId:String(data.colors_contact_id),communicationContactId:String(data.communication_contact_id)};}

export const getColorsGroupAccess=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const ids=await linkedIdentity(context);const{supabaseAdmin}=await import("@/integrations/supabase/client.server");const admin:any=supabaseAdmin;const{data:status,error}=await admin.rpc("colors_refresh_group_eligibility",{p_contact_id:ids.colorsContactId});if(error)throw error;if(status!=="eligible"&&status!=="invited"&&status!=="joined")return{eligible:false,status};const url=process.env.COLORS_GROUP_URL??"";if(!url)return{eligible:true,status,configured:false};if(status==="eligible")await admin.from("colors_group_access").update({eligibility_status:"invited",invite_sent_at:new Date().toISOString(),metadata:{source:"authenticated_customer_account"}}).eq("contact_id",ids.colorsContactId).eq("eligibility_status","eligible");return{eligible:true,status:status==="eligible"?"invited":status,configured:true,url};});

const referralSchema=z.object({reasonCode:z.enum(["medication_interaction","pregnancy_breastfeeding","hypertension","allergy","multiple_medications","clinical_uncertainty","other"])});
export const createColorsChrismedReferral=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((raw:unknown)=>referralSchema.parse(raw)).handler(async({context,data})=>{const ids=await linkedIdentity(context);const{supabaseAdmin}=await import("@/integrations/supabase/client.server");const admin:any=supabaseAdmin;const{data:company,error:companyError}=await admin.from("companies").select("id").eq("document","58.255.587/0001-60").maybeSingle();if(companyError||!company?.id)throw new Error("colors_company_missing");const{data:orders,error:orderError}=await admin.from("sales_orders").select("id").eq("company_id",company.id).eq("contact_id",ids.communicationContactId).in("status",["confirmed","processing","fulfilled"]).limit(1);if(orderError)throw orderError;if(!Array.isArray(orders)||orders.length===0)return{created:false,reason:"verified_colors_origin_required"};const{data:existing}=await admin.from("colors_chrismed_referrals").select("id,expires_at").eq("colors_contact_id",ids.colorsContactId).in("status",["created","opened"]).gt("expires_at",new Date().toISOString()).order("created_at",{ascending:false}).limit(1).maybeSingle();if(existing?.id)return{created:false,reason:"active_referral_exists",referralId:existing.id,expiresAt:existing.expires_at};const token=randomBytes(32).toString("base64url");const tokenHash=createHash("sha256").update(token).digest("hex");const expires=new Date(Date.now()+7*86400000).toISOString();const{data:row,error}=await admin.from("colors_chrismed_referrals").insert({colors_contact_id:ids.colorsContactId,communication_contact_id:ids.communicationContactId,referral_token_hash:tokenHash,referral_reason_code:data.reasonCode,source_channel:"colors_customer_account",colors_origin_verified:true,status:"created",coupon_code:"COLORS50",expires_at:expires,operational_metadata:{data_boundary:"operational_only",no_clinical_data:true}}).select("id").single();if(error)throw error;const url=`https://chrismed.impulsionando.com.br/agendar?modality=telemedicina&colors_ref=${encodeURIComponent(token)}`;return{created:true,referralId:row.id,expiresAt:expires,coupon:"COLORS50",url};});
