import { createFileRoute, Link, useNavigate } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { ChrismedShell } from '@/components/chrismed/ChrismedShell';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Building2, Download, FileText, ShieldCheck, ArrowLeft } from 'lucide-react';
import { toast } from 'sonner';

type Doc={id:string;file_name:string;document_type:string;modified_time:string|null;release_policy:string;mime_type:string|null};
export const Route=createFileRoute('/chrismed/empresa/documentos')({component:CompanyDocumentsPage,head:()=>({meta:[{title:'Documentos da Empresa — CHRISMED'},{name:'robots',content:'noindex,nofollow'}]})});

function CompanyDocumentsPage(){const navigate=useNavigate();const [docs,setDocs]=useState<Doc[]>([]);const [company,setCompany]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);
 async function load(){const {data:auth}=await supabase.auth.getUser();if(!auth.user){navigate({to:'/auth?persona=company&next=%2Fempresa%2Fdocumentos' as never});return;}const {data:members}=await (supabase as any).from('chrismed_occ_company_users').select('client_company_id,company:chrismed_occ_client_companies(legal_name,trade_name)').eq('user_id',auth.user.id).eq('active',true).limit(1);const m=members?.[0];if(!m){setLoading(false);return;}setCompany(m.company?.trade_name||m.company?.legal_name||'Empresa');const {data:links,error:le}=await (supabase as any).from('client_drive_document_links').select('drive_document_id').eq('entity_type','company').eq('entity_id',m.client_company_id).eq('release_to_entity',true);if(le){setLoading(false);return toast.error('Não foi possível carregar os documentos.');}const ids=(links??[]).map((x:any)=>x.drive_document_id);if(!ids.length){setDocs([]);setLoading(false);return;}const {data:documents,error}=await (supabase as any).from('client_drive_documents').select('id,file_name,document_type,modified_time,release_policy,mime_type').in('id',ids).eq('status','active').order('modified_time',{ascending:false});setLoading(false);if(error)return toast.error('Não foi possível carregar os documentos.');setDocs(documents??[]);}
 useEffect(()=>{void load();},[]);
 async function download(doc:Doc){setBusy(doc.id);try{const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('Sessão expirada.');const response=await fetch('/api/chrismed/documents/deliver',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({documentId:doc.id})});if(!response.ok)throw new Error('Documento indisponível para esta conta.');const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=doc.file_name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){toast.error((e as Error).message);}finally{setBusy(null);}}
 return <ChrismedShell><main className="min-h-[70vh] bg-[var(--chrismed-ivory)]"><div className="container max-w-6xl py-10"><Link to="/chrismed/empresa" className="mb-4 inline-flex items-center text-sm text-[var(--chrismed-forest-deep)]"><ArrowLeft className="mr-1 h-4 w-4"/>Voltar à Área da Empresa</Link><header className="rounded-3xl bg-[var(--chrismed-forest-deep)] p-7 text-white"><Badge className="mb-3 bg-white/10 text-white">Área protegida</Badge><h1 className="chrismed-serif flex items-center gap-3 text-4xl"><Building2 className="h-8 w-8"/>Documentos — {company||'Empresa'}</h1><p className="mt-3 max-w-3xl text-white/75">Notas fiscais e documentos administrativos liberados especificamente para sua empresa. Dados clínicos de colaboradores não são exibidos aqui.</p></header><div className="mt-6 rounded-2xl border border-[var(--chrismed-sand)] bg-white p-4 text-sm text-[var(--chrismed-graphite)]"><ShieldCheck className="mr-2 inline h-4 w-4"/>A liberação exige vínculo ativo da sua conta com a empresa e autorização específica do documento.</div>{loading?<p className="py-14 text-center">Carregando documentos…</p>:!docs.length?<Card className="mt-6"><CardContent className="py-14 text-center text-[var(--chrismed-graphite)]">Nenhum documento foi liberado para esta empresa até o momento.</CardContent></Card>:<div className="mt-6 grid gap-4 md:grid-cols-2">{docs.map(doc=><Card key={doc.id}><CardHeader><CardTitle className="flex items-start gap-2 text-lg"><FileText className="mt-0.5 h-5 w-5"/><span>{doc.file_name}</span></CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Badge variant="outline">{doc.document_type}</Badge><Badge variant="outline">{doc.release_policy}</Badge></div><p className="text-xs text-[var(--chrismed-graphite)]">Atualizado: {doc.modified_time?new Date(doc.modified_time).toLocaleString('pt-BR'):'—'}</p><Button onClick={()=>void download(doc)} disabled={busy===doc.id} className="w-full bg-[var(--chrismed-forest-deep)] text-white"><Download className="mr-2 h-4 w-4"/>{busy===doc.id?'Preparando…':'Baixar documento'}</Button></CardContent></Card>)}</div>}</div></main></ChrismedShell>}
