import { createFileRoute, Link } from '@tanstack/react-router';
import { useState } from 'react';
import { CalendarDays, CheckCircle2, ChevronLeft, Building2 } from 'lucide-react';
import { ChrismedShell } from '@/components/chrismed/ChrismedShell';
import { openChrismedOliver } from '@/components/chrismed/oliver-store';
import { supabase } from '@/integrations/supabase/client';

export const Route = createFileRoute('/chrismed/eventos/contratar')({
  head: () => ({ meta: [
    { title: 'Contratar evento em saúde · CHRISMED' },
    { name: 'description', content: 'Solicite à CHRISMED um evento corporativo, científico ou de saúde com datas, público e operação sob medida.' },
  ]}),
  component: ContratarEventoPage,
});

const inputCls='w-full rounded-xl border border-[var(--chrismed-sand)] bg-white px-4 py-3 text-[var(--chrismed-forest-deep)] outline-none focus:border-[var(--chrismed-forest)]';

function ContratarEventoPage(){
  const [sent,setSent]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const [form,setForm]=useState({organization:'',document:'',contactName:'',email:'',phone:'',eventKind:'corporativo',objective:'',audience:'',attendees:'',date1:'',date2:'',date3:'',timeWindow:'',locationMode:'empresa',city:'Rio de Janeiro',venue:'',notes:''});
  const set=(key:string,value:string)=>setForm(v=>({...v,[key]:value}));
  async function submit(e:React.FormEvent){e.preventDefault(); if(busy)return; setBusy(true);setError(null); const {error:rpcError}=await supabase.rpc('submit_chrismed_event_service_request' as never,{p_request:{requestId:crypto.randomUUID(),...form}} as never); setBusy(false); if(rpcError){setError('Não foi possível registrar a solicitação agora. Tente novamente ou fale com Oliver.');return;} setSent(true);}
  return <ChrismedShell><main className="min-h-screen bg-[var(--chrismed-ivory)] text-[var(--chrismed-forest-deep)]">
    <section className="bg-[var(--chrismed-forest-deep)] text-white"><div className="mx-auto max-w-5xl px-5 py-16 md:py-24"><Link to="/chrismed/eventos" className="inline-flex items-center gap-2 text-sm text-[var(--chrismed-amber-soft)]"><ChevronLeft className="h-4 w-4"/>Eventos</Link><div className="mt-7 flex items-center gap-3 text-xs font-bold uppercase tracking-[.2em] text-[var(--chrismed-amber-soft)]"><Building2 className="h-4 w-4"/>Para empresas e organizações</div><h1 className="chrismed-serif mt-4 max-w-4xl text-5xl leading-tight md:text-6xl">Leve um evento CHRISMED para sua empresa.</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-white/75">Informe objetivo, público, estimativa de participantes e até três opções de data. A CHRISMED recebe a demanda, organiza a proposta e confirma a agenda antes da contratação.</p></div></section>
    <section className="mx-auto max-w-5xl px-5 py-12 md:py-16">{sent?<div className="rounded-3xl border border-[var(--chrismed-sand)] bg-white p-8 text-center md:p-12"><CheckCircle2 className="mx-auto h-12 w-12 text-[var(--chrismed-forest)]"/><h2 className="chrismed-serif mt-5 text-4xl">Solicitação recebida.</h2><p className="mx-auto mt-3 max-w-2xl text-[var(--chrismed-graphite)]">A demanda já entrou na jornada corporativa CHRISMED. A equipe poderá validar escopo, disponibilidade, local e proposta antes de transformar a solicitação em evento confirmado.</p><button onClick={()=>openChrismedOliver()} className="mt-7 rounded-full bg-[var(--chrismed-forest-deep)] px-6 py-3 font-semibold text-white">Falar com Oliver</button></div>:
    <form onSubmit={submit} className="grid gap-6 rounded-3xl border border-[var(--chrismed-sand)] bg-white p-6 shadow-sm md:p-10">
      <div><h2 className="chrismed-serif text-3xl">Solicitação de evento</h2><p className="mt-2 text-sm text-[var(--chrismed-graphite)]">Campos com * são obrigatórios.</p></div>
      <div className="grid gap-5 md:grid-cols-2"><Field label="Empresa / organização *"><input required className={inputCls} value={form.organization} onChange={e=>set('organization',e.target.value)}/></Field><Field label="CNPJ"><input className={inputCls} value={form.document} onChange={e=>set('document',e.target.value)}/></Field><Field label="Responsável *"><input required className={inputCls} value={form.contactName} onChange={e=>set('contactName',e.target.value)}/></Field><Field label="E-mail corporativo *"><input required type="email" className={inputCls} value={form.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="Telefone / WhatsApp *"><input required className={inputCls} value={form.phone} onChange={e=>set('phone',e.target.value)}/></Field><Field label="Tipo de evento *"><select required className={inputCls} value={form.eventKind} onChange={e=>set('eventKind',e.target.value)}><option value="corporativo">Evento corporativo de saúde</option><option value="cientifico">Evento científico</option><option value="palestra">Palestra / educação em saúde</option><option value="ocupacional">Ação de saúde ocupacional</option><option value="campanha">Campanha / ação preventiva</option><option value="outro">Outro</option></select></Field></div>
      <Field label="Objetivo do evento"><textarea rows={3} className={inputCls} value={form.objective} onChange={e=>set('objective',e.target.value)}/></Field>
      <div className="grid gap-5 md:grid-cols-2"><Field label="Público / perfil dos participantes"><input className={inputCls} value={form.audience} onChange={e=>set('audience',e.target.value)}/></Field><Field label="Estimativa de participantes"><input inputMode="numeric" className={inputCls} value={form.attendees} onChange={e=>set('attendees',e.target.value)}/></Field></div>
      <div><div className="mb-3 flex items-center gap-2 font-semibold"><CalendarDays className="h-5 w-5"/>Datas preferenciais</div><div className="grid gap-4 md:grid-cols-3"><input type="date" className={inputCls} value={form.date1} onChange={e=>set('date1',e.target.value)}/><input type="date" className={inputCls} value={form.date2} onChange={e=>set('date2',e.target.value)}/><input type="date" className={inputCls} value={form.date3} onChange={e=>set('date3',e.target.value)}/></div></div>
      <div className="grid gap-5 md:grid-cols-2"><Field label="Turno / horário preferencial"><input placeholder="Ex.: manhã, 9h às 12h" className={inputCls} value={form.timeWindow} onChange={e=>set('timeWindow',e.target.value)}/></Field><Field label="Onde será realizado?"><select className={inputCls} value={form.locationMode} onChange={e=>set('locationMode',e.target.value)}><option value="empresa">Na empresa / contratante</option><option value="chrismed">Local CHRISMED</option><option value="externo">Espaço externo</option><option value="online">Online</option><option value="to_define">A definir</option></select></Field><Field label="Cidade"><input className={inputCls} value={form.city} onChange={e=>set('city',e.target.value)}/></Field><Field label="Local / endereço"><input className={inputCls} value={form.venue} onChange={e=>set('venue',e.target.value)}/></Field></div>
      <Field label="Observações, necessidades e estrutura"><textarea rows={4} className={inputCls} value={form.notes} onChange={e=>set('notes',e.target.value)}/></Field>
      {error&&<p role="alert" className="text-sm font-semibold text-red-700">{error}</p>}
      <div className="flex flex-col gap-3 sm:flex-row"><button disabled={busy} className="rounded-full bg-[var(--chrismed-forest-deep)] px-7 py-3 font-bold text-white disabled:opacity-60">{busy?'Enviando…':'Solicitar evento'}</button><button type="button" onClick={()=>openChrismedOliver()} className="rounded-full border border-[var(--chrismed-forest)] px-7 py-3 font-bold text-[var(--chrismed-forest-deep)]">Falar com Oliver</button></div>
      <p className="text-xs text-[var(--chrismed-graphite)]">A solicitação não bloqueia automaticamente a data. A reserva ocorre após validação de disponibilidade e confirmação comercial.</p>
    </form>}</section>
  </main></ChrismedShell>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span>{children}</label>}
