import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2, Stethoscope, Users } from "lucide-react";
import { ChrismedShell } from "@/components/chrismed/ChrismedShell";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { CHRISMED_DOCTORS, CHRISMED_SPECIALTIES } from "@/data/chrismed-catalog";

export const Route = createFileRoute("/chrismed/medicos")({
  head: () => ({ meta: [{ title: "Time CHRISMED — Profissionais da Saúde" },{ name:"description",content:"Cadastre-se para integrar o Time CHRISMED. O cadastro profissional é analisado pelo comitê gestor antes da ativação." }] }),
  component: HealthProfessionalNetwork,
});

function HealthProfessionalNetwork(){
 return <ChrismedShell>
  <section className="chrismed-bleed chrismed-page-forest border-b border-white/10"><div className="container max-w-5xl py-16 md:py-20"><Badge className="mb-5 border border-[var(--chrismed-sand)] bg-[var(--chrismed-bone)] text-[var(--chrismed-ink)]">TIME CHRISMED</Badge><h1 className="chrismed-serif max-w-4xl text-4xl leading-tight text-[var(--chrismed-ink)] md:text-6xl">Profissional da saúde, faça parte da CHRISMED.</h1><p className="mt-6 max-w-3xl text-lg text-[var(--chrismed-graphite)]">Cadastre seu perfil profissional, especialidades, modalidades e disponibilidade. Após concluir, seu cadastro será enviado ao comitê gestor CHRISMED para análise. Somente profissionais aprovados são ativados e disponibilizados para atendimento.</p><div className="mt-6 grid gap-2 text-sm text-[var(--chrismed-graphite)] sm:grid-cols-2">{['Escolha sua profissão e informe seu conselho profissional quando aplicável.','Selecione uma ou mais especialidades e subespecialidades.','Configure atendimento presencial, teleconsulta ou modalidades disponíveis.','Defina dias, horários, locais e preferências de agenda.'].map(x=><div key={x} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0"/>{x}</div>)}</div><Button asChild className="mt-7 bg-[var(--chrismed-ink)] text-[var(--chrismed-ivory)]"><Link to="/auth" search={{mode:"signup"}}><Users className="mr-2 h-4 w-4"/>Quero fazer parte do Time CHRISMED</Link></Button><p className="mt-3 text-xs text-[var(--chrismed-mist)]">O cadastro não representa aprovação automática. A ativação depende da análise da gestão CHRISMED.</p></div></section>
  <section className="container max-w-6xl py-12 md:py-16"><div className="mb-6 flex items-center gap-2"><Stethoscope className="h-5 w-5 text-[var(--chrismed-ink)]"/><h2 className="chrismed-serif text-2xl text-[var(--chrismed-ink)]">Profissionais em destaque</h2></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{CHRISMED_DOCTORS.map(p=><article key={p.slug} className="flex flex-col rounded-2xl border border-[var(--chrismed-sand)] bg-[var(--chrismed-ivory)] p-6"><h3 className="chrismed-serif text-lg text-[var(--chrismed-ink)]">{p.name}</h3><p className="mt-1 text-xs uppercase tracking-wide text-[var(--chrismed-mist)]">{p.crm}</p><p className="mt-3 flex-1 text-sm text-[var(--chrismed-graphite)]">{p.title}</p><div className="mt-4 flex flex-wrap gap-1.5">{p.specialtySlugs.map(s=><span key={s} className="rounded-full border border-[var(--chrismed-sand)] px-2 py-1 text-xs">{CHRISMED_SPECIALTIES.find(i=>i.slug===s)?.name??s}</span>)}</div><Button asChild className="mt-5 bg-[var(--chrismed-ink)] text-[var(--chrismed-ivory)]"><Link to="/chrismed/agendar" search={{doctor:p.slug}}>Agendar atendimento<ArrowRight className="ml-2 h-4 w-4"/></Link></Button></article>)}</div></section>
 </ChrismedShell>;
}
