import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { Building2, CheckCircle2, ClipboardList, FlaskConical, HardDrive, ShieldCheck, UsersRound, XCircle } from 'lucide-react';
import { ChrismedShell } from '@/components/chrismed/ChrismedShell';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

export const Route=createFileRoute('/chrismed/admin')({
  head:()=>({meta:[{title:'Gestão CHRISMED'},{name:'robots',content:'noindex, nofollow'}]}),
  component:AdminPage,
});

const db=supabase as any;
type Patient={user_id:string;full_name:string;whatsapp:string;email:string;status:string;created_at:string;approved_at?:string|null;rejection_reason?:string|null};
type CompanyRequest={id:string;legal_name:string;trade_name?:string|null;document?:string|null;contact_name:string;contact_email:string;contact_phone:string;status:string;created_at:string;client_company_id?:string|null;rejection_reason?:string|null};
type Partner={id:string;name:string;partner_type:string;website?:string|null;address?:Record<string,unknown>;contact?:Record<string,unknown>;instructions?:string|null;active:boolean};
type DriveConnection={id:string;provider_account_email:string;status:string;connected_at?:string|null;last_sync_at?:string|null};
type Overview={authorized:boolean;patient_requests:Patient[];company_requests:CompanyRequest[];partners:Partner[];counts:Record<string,number>};

function AdminPage(){
 const navigate=useNavigate(); const [data,setData]=useState<Overview|null>(null); const [drive,setDrive]=useState<DriveConnection|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [partner,setPartner]=useState({name:'',partner_type:'laboratory',website:'',instructions:'',address_text:'',contact_text:''});
 async function load(){const {data:auth}=await supabase.auth.getUser();if(!auth.user){navigate({to:'/auth?persona=admin&next=%2Fchrismed%2Fadmin' as never});return;}const [{data:row,error},{data:connections}]=await Promise.all([supabase.rpc('chrismed_admin_overview' as never),db.from('client_drive_connections').select('id,provider_account_email,status,connected_at,last_sync_at').eq('company_id','642096b5-a9ff-4521-a82a-c004f6d2e2d2').eq('provider','google_drive').limit(1)]);if(error){toast.error('Não foi possível carregar a gestão CHRISMED.');setLoading(false);return;}const ov=row as unknown as Overview;if(!ov.authorized){toast.error('Seu usuário não possui permissão de gestão CHRISMED.');navigate({to:'/chrismed' as never});return;}setData(ov);setDrive((connections?.[0]??null) as DriveConnection|null);setLoading(false);}
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const status=params.get('drive');if(status==='connected')toast.success('Google Drive CHRISMED conectado com sucesso.');if(status==='cancelled')toast.info('Conexão com Google Drive cancelada.');if(status==='invalid'||status==='error')toast.error('Não foi possível concluir a conexão com Google Drive.');void load()},[]);
 async function connectGoogleDrive(){setBusy('drive');const {data:session}=await supabase.auth.getSession();const token=session.session?.access_token;if(!token){setBusy(null);return toast.error('Sua sessão expirou. Entre novamente na Gestão CHRISMED.');}const response=await fetch('/api/chrismed/google-drive/start',{method:'POST',headers:{authorization:`Bearer ${token}`}});const json=await response.json().catch(()=>({})) as {authorizationUrl?:string;error?:string};setBusy(null);if(!response.ok||!json.authorizationUrl)return toast.error('Não foi possível iniciar a autorização do Google Drive.');window.location.href=json.authorizationUrl;}
 async function reviewPatient(userId:string,approve:boolean){setBusy(`p-${userId}`);const reason=approve?null:window.prompt('Motivo da não aprovação:')||'Cadastro não aprovado pela gestão CHRISMED.';const {error}=await supabase.rpc('chrismed_review_patient_profile' as never,{p_user_id:userId,p_approve:approve,p_rejection_reason:reason} as never);setBusy(null);if(error)return toast.error('Não foi possível atualizar o paciente.');toast.success(approve?'Paciente aprovado.':'Cadastro não aprovado.');await load();}
 async function reviewCompany(id:string,approve:boolean){setBusy(`c-${id}`);const reason=approve?null:window.prompt('Motivo da não aprovação:')||'Cadastro empresarial não aprovado.';const {error}=await supabase.rpc('chrismed_occ_approve_company_request' as never,{p_request_id:id,p_approve:approve,p_rejection_reason:reason} as never);setBusy(null);if(error)return toast.error('Não foi possível atualizar a empresa.');toast.success(approve?'Empresa aprovada e área corporativa criada.':'Solicitação empresarial não aprovada.');await load();}
 async function addPartner(e:React.FormEvent){e.preventDefault();setBusy('partner');const address=partner.address_text?{texto:partner.address_text}:{};const contact=partner.contact_text?{texto:partner.contact_text}:{};const {error}=await db.from('chrismed_occ_partner_network').insert({company_id:'642096b5-a9ff-4521-a82a-c004f6d2e2d2',name:partner.name,partner_type:partner.partner_type,website:partner.website||null,address,contact,instructions:partner.instructions||null,active:true});setBusy(null);if(error)return toast.error('Não foi possível cadastrar o parceiro.');setPartner({name:'',partner_type:'laboratory',website:'',instructions:'',address_text:'',contact_text:''});toast.success('Parceiro cadastrado.');await load();}
 async function togglePartner(p:Partner){setBusy(`partner-${p.id}`);const {error}=await db.from('chrismed_occ_partner_network').update({active:!p.active,updated_at:new Date().toISOString()}).eq('id',p.id);setBusy(null);if(error)return toast.error('Não foi possível atualizar o parceiro.');await load();}
 if(loading)return <ChrismedShell variant="minimal"><div className="mx-auto max-w-7xl px-5 py-24 text-center text-[var(--chrismed-forest-deep)]">Carregando Gestão CHRISMED…</div></ChrismedShell>;
 if(!data)return null;
 const pendingPatients=data.patient_requests.filter(x=>x.status==='pending');const pendingCompanies=data.company_requests.filter(x=>x.status==='pending');
 return <ChrismedShell variant="minimal"><section className="min-h-screen bg-[var(--chrismed-ivory)] px-4 pb-16 pt-10 text-[var(--chrismed-forest-deep)] md:px-6"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-4 border-b border-[var(--chrismed-sand)] pb-7 md:flex-row md:items-end md:justify-between"><div><Badge className="mb-3 bg-[var(--chrismed-forest-deep)] text-white"><ShieldCheck className="mr-1 h-3.5 w-3.5"/>Gestão protegida</Badge><h1 className="chrismed-serif text-4xl md:text-5xl">Gestão CHRISMED</h1><p className="mt-2 max-w-2xl text-sm text-[var(--chrismed-graphite)]">Aprovações, empresas, rede parceira, documentos e visão operacional da plataforma.</p></div><Button variant="outline" onClick={()=>void load()}>Atualizar dados</Button></div>
 <div className="mt-7 rounded-2xl border border-[var(--chrismed-sand)] bg-white p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[var(--chrismed-bone)] text-[var(--chrismed-forest-deep)]"><HardDrive className="h-5 w-5"/></span><div><div className="flex items-center gap-2"><strong>Google Drive CHRISMED</strong><Badge variant={drive?.status==='connected'?'default':'outline'}>{drive?.status==='connected'?'Conectado':'Não conectado'}</Badge></div><p className="mt-1 text-sm text-[var(--chrismed-graphite)]">{drive?.status==='connected'?`Conta autorizada: ${drive.provider_account_email}`:'Conecte exclusivamente a conta Google Drive da CHRISMED. O Oliver terá leitura e classificação, com liberação de documentos somente pelas regras do cliente autenticado.'}</p>{drive?.connected_at&&<p className="mt-1 text-xs text-[var(--chrismed-graphite)]">Conectado em {new Date(drive.connected_at).toLocaleString('pt-BR')}</p>}</div></div><Button disabled={busy==='drive'} onClick={()=>void connectGoogleDrive()} className="bg-[var(--chrismed-forest-deep)] text-white">{busy==='drive'?'Abrindo Google…':drive?.status==='connected'?'Reconectar Google Drive':'Conectar Google Drive'}</Button></div></div>
 <div className="my-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><Metric label="Pacientes pendentes" value={data.counts.patients_pending||0}/><Metric label="Empresas pendentes" value={data.counts.companies_pending||0}/><Metric label="Empresas ativas" value={data.counts.active_companies||0}/><Metric label="Colaboradores" value={data.counts.active_employees||0}/><Metric label="Parceiros" value={data.counts.active_partners||0}/><Metric label="Prontuários" value={data.counts.clinical_records||0}/></div>
 <Tabs defaultValue="pacientes"><TabsList className="flex h-auto flex-wrap bg-[var(--chrismed-bone)]"><TabsTrigger value="pacientes"><UsersRound className="mr-1.5 h-4 w-4"/>Pacientes</TabsTrigger><TabsTrigger value="empresas"><Building2 className="mr-1.5 h-4 w-4"/>Empresas</TabsTrigger><TabsTrigger value="parceiros"><FlaskConical className="mr-1.5 h-4 w-4"/>Rede parceira</TabsTrigger><TabsTrigger value="prontuarios"><ClipboardList className="mr-1.5 h-4 w-4"/>Prontuários</TabsTrigger></TabsList>
 <TabsContent value="pacientes" className="mt-6"><PanelTitle title="Aprovação de pacientes" subtitle="O cadastro inicial contém somente nome, WhatsApp e e-mail. Após aprovação, o paciente completa CPF e endereço em sua área exclusiva."/><div className="mt-4 space-y-3">{pendingPatients.map(p=><article key={p.user_id} className="grid gap-4 rounded-2xl border border-[var(--chrismed-sand)] bg-white p-5 md:grid-cols-[1fr_auto] md:items-center"><div><strong className="text-lg">{p.full_name}</strong><div className="mt-1 text-sm text-[var(--chrismed-graphite)]">{p.email} · {p.whatsapp}</div><div className="mt-1 text-xs text-[var(--chrismed-graphite)]">Solicitado em {new Date(p.created_at).toLocaleString('pt-BR')}</div></div><div className="flex gap-2"><Button disabled={busy===`p-${p.user_id}`} onClick={()=>void reviewPatient(p.user_id,true)} className="bg-[var(--chrismed-forest-deep)] text-white"><CheckCircle2 className="mr-1.5 h-4 w-4"/>Aprovar</Button><Button disabled={busy===`p-${p.user_id}`} variant="outline" onClick={()=>void reviewPatient(p.user_id,false)}><XCircle className="mr-1.5 h-4 w-4"/>Não aprovar</Button></div></article>)}{!pendingPatients.length&&<Empty text="Nenhum paciente aguardando aprovação."/>}</div></TabsContent>
 <TabsContent value="empresas" className="mt-6"><PanelTitle title="Aprovação de empresas" subtitle="Ao aprovar, a Área da Empresa é criada e o solicitante passa a ser administrador corporativo."/><div className="mt-4 space-y-3">{pendingCompanies.map(c=><article key={c.id} className="grid gap-4 rounded-2xl border border-[var(--chrismed-sand)] bg-white p-5 md:grid-cols-[1fr_auto] md:items-center"><div><strong className="text-lg">{c.trade_name||c.legal_name}</strong><div className="text-sm">{c.legal_name}{c.document?` · ${c.document}`:''}</div><div className="mt-1 text-sm text-[var(--chrismed-graphite)]">{c.contact_name} · {c.contact_email} · {c.contact_phone}</div></div><div className="flex gap-2"><Button disabled={busy===`c-${c.id}`} onClick={()=>void reviewCompany(c.id,true)} className="bg-[var(--chrismed-forest-deep)] text-white"><CheckCircle2 className="mr-1.5 h-4 w-4"/>Aprovar</Button><Button disabled={busy===`c-${c.id}`} variant="outline" onClick={()=>void reviewCompany(c.id,false)}><XCircle className="mr-1.5 h-4 w-4"/>Não aprovar</Button></div></article>)}{!pendingCompanies.length&&<Empty text="Nenhuma empresa aguardando aprovação."/>}</div></TabsContent>
 <TabsContent value="parceiros" className="mt-6 grid gap-6 lg:grid-cols-[24rem_1fr]"><form onSubmit={addPartner} className="rounded-2xl border border-[var(--chrismed-sand)] bg-white p-5"><PanelTitle title="Novo parceiro" subtitle="Use somente dados reais e confirmados da rede parceira."/><div className="mt-4 grid gap-3"><Field label="Nome" value={partner.name} onChange={v=>setPartner({...partner,name:v})}/><Select label="Tipo" value={partner.partner_type} onChange={v=>setPartner({...partner,partner_type:v})}/><Field label="Site" value={partner.website} onChange={v=>setPartner({...partner,website:v})} required={false}/><Field label="Endereço / unidades" value={partner.address_text} onChange={v=>setPartner({...partner,address_text:v})} required={false}/><Field label="Contato" value={partner.contact_text} onChange={v=>setPartner({...partner,contact_text:v})} required={false}/><Field label="Orientações" value={partner.instructions} onChange={v=>setPartner({...partner,instructions:v})} required={false}/><Button disabled={busy==='partner'} className="bg-[var(--chrismed-forest-deep)] text-white">Cadastrar parceiro</Button></div></form><div className="space-y-3">{data.partners.map(p=><article key={p.id} className="rounded-2xl border border-[var(--chrismed-sand)] bg-white p-5"><div className="flex items-start justify-between gap-4"><div><strong>{p.name}</strong><div className="mt-1 text-xs uppercase tracking-wider text-[var(--chrismed-graphite)]">{p.partner_type}</div>{p.website&&<a className="mt-2 block text-sm underline" href={p.website} target="_blank" rel="noreferrer">{p.website}</a>}{p.instructions&&<p className="mt-2 text-sm text-[var(--chrismed-graphite)]">{p.instructions}</p>}</div><Button variant="outline" disabled={busy===`partner-${p.id}`} onClick={()=>void togglePartner(p)}>{p.active?'Desativar':'Ativar'}</Button></div></article>)}{!data.partners.length&&<Empty text="Nenhum parceiro cadastrado."/>}</div></TabsContent>
 <TabsContent value="prontuarios" className="mt-6"><PanelTitle title="Prontuários eletrônicos" subtitle="O conteúdo clínico é acessível somente a profissionais vinculados e gestores clínicos autorizados. Este painel mostra apenas a contagem operacional; o conteúdo clínico deve ser aberto pela jornada profissional/paciente adequada."/><Empty text={`${data.counts.clinical_records||0} prontuário(s) clínico(s) registrado(s) no núcleo CHRISMED.`}/></TabsContent>
 </Tabs></div></section></ChrismedShell>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-[var(--chrismed-sand)] bg-white p-4"><div className="text-[10px] uppercase tracking-[0.16em] text-[var(--chrismed-graphite)]">{label}</div><div className="mt-1 chrismed-serif text-3xl">{value}</div></div>}
function PanelTitle({title,subtitle}:{title:string;subtitle:string}){return <div><h2 className="chrismed-serif text-2xl">{title}</h2><p className="mt-1 text-sm text-[var(--chrismed-graphite)]">{subtitle}</p></div>}
function Field({label,value,onChange,required=true}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean}){return <label><span className="mb-1 block text-xs font-semibold text-[var(--chrismed-graphite)]">{label}</span><input required={required} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-[var(--chrismed-sand)] px-3 py-2.5 outline-none focus:border-[var(--chrismed-forest)]"/></label>}
function Select({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label><span className="mb-1 block text-xs font-semibold text-[var(--chrismed-graphite)]">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-[var(--chrismed-sand)] px-3 py-2.5"><option value="laboratory">Laboratório</option><option value="imaging">Imagem</option><option value="clinic">Clínica</option><option value="occupational_clinic">Clínica ocupacional</option><option value="other">Outro</option></select></label>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-[var(--chrismed-sand)] bg-white p-8 text-center text-sm text-[var(--chrismed-graphite)]">{text}</div>}
