import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CalendarDays, CheckCircle2, ShieldCheck, Users } from "lucide-react";
import { useColorsUtmHydration } from "@/lib/colors-utm-hydrate";

export const Route=createFileRoute("/colors/afiliados")({
  head:()=>({meta:[
    {title:"Afiliados Colors Saúde — programa oficial"},
    {name:"description",content:"Conheça a jornada oficial de afiliados Colors Saúde, acesse orientação e agende uma conversa com o gerente de afiliados."},
    {property:"og:title",content:"Afiliados Colors Saúde"},{property:"og:description",content:"Programa oficial de afiliados Colors com suporte e acompanhamento."}
  ],links:[{rel:"canonical",href:"https://colors.impulsionando.com.br/afiliados"}]}),component:AffiliatePage
});
function AffiliatePage(){useColorsUtmHydration("colors_afiliados");return <main className="min-h-screen bg-[#07110d] text-white"><header className="border-b border-white/10"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4"><Link to="/colors" className="font-black">Colors Saúde</Link><Link to="/colors/agenda" className="rounded-full bg-emerald-400 px-4 py-2 text-sm font-black text-black">Agendar call</Link></div></header><section className="mx-auto grid max-w-6xl gap-12 px-4 py-20 lg:grid-cols-2 lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.25em] text-emerald-400">Afiliados Colors</p><h1 className="mt-3 text-5xl font-black sm:text-6xl">Venda com a força da Colors e com relacionamento de verdade.</h1><p className="mt-5 text-lg text-white/65">A Íris identifica candidatos, preserva a origem e a atribuição das vendas e apoia o afiliado sem inventar comissão, regra ou promessa de renda. Informações comerciais são sempre as vigentes no programa oficial.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/colors/agenda" className="inline-flex items-center gap-2 rounded-full bg-emerald-400 px-6 py-3.5 font-black text-black"><CalendarDays className="h-4 w-4"/>Falar com gerente de afiliados</Link><Link to="/colors/super-green-black" className="inline-flex items-center gap-2 rounded-full border border-white/15 px-6 py-3.5 font-bold">Conhecer Super Green Black <ArrowRight className="h-4 w-4"/></Link></div></div><div className="grid gap-4"><Card icon={Users} title="Origem preservada" text="UTMs, código do afiliado, first touch e last touch fazem parte da jornada de atribuição."/><Card icon={CheckCircle2} title="Materiais oficiais" text="A jornada deve direcionar somente para materiais, links e regras aprovados pela Colors e pelas plataformas vigentes."/><Card icon={ShieldCheck} title="Sem promessa de renda" text="A Íris não inventa comissão nem promete ganhos. Toda regra comercial vem da configuração oficial do programa."/></div></section><section className="border-t border-white/10 bg-white/[.025]"><div className="mx-auto max-w-6xl px-4 py-14"><h2 className="text-3xl font-black">Já é afiliado?</h2><p className="mt-3 max-w-2xl text-white/65">Use a agenda Colors para solicitar uma conversa com o gerente de afiliados. Seu histórico e origem ficam associados à jornada para reduzir retrabalho.</p><Link to="/colors/agenda" className="mt-6 inline-flex rounded-full border border-emerald-400/30 bg-emerald-400/10 px-6 py-3 font-black text-emerald-300">Agendar atendimento de afiliado</Link></div></section></main>}
function Card({icon:Icon,title,text}:{icon:any;title:string;text:string}){return <div className="rounded-3xl border border-white/10 bg-white/[.035] p-6"><Icon className="h-7 w-7 text-emerald-400"/><h2 className="mt-4 text-xl font-black">{title}</h2><p className="mt-2 text-sm text-white/60">{text}</p></div>}
