import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { Eye, EyeOff, Loader2, UserPlus } from "lucide-react";
import AuthShell from "@/components/colors/AuthShell";
import { Field, inputCls } from "@/routes/colors.entrar";
import { supabase } from "@/integrations/supabase/client";

export const Route=createFileRoute("/colors/criar-conta")({head:()=>({meta:[{title:"Criar conta — Colors Saúde"},{name:"description",content:"Crie sua conta Colors Saúde para acompanhar pedidos e relacionamento oficial."},{name:"robots",content:"noindex"}]}),component:CriarContaPage});
function signupError(msg?:string){const m=(msg??"").toLowerCase();if(m.includes("already registered")||m.includes("user already registered"))return"Já existe uma conta com este e-mail.";if(m.includes("password"))return"A senha informada não atende aos requisitos de segurança.";if(m.includes("email")&&m.includes("invalid"))return"Informe um e-mail válido.";if(m.includes("rate limit")||m.includes("too many"))return"Muitas tentativas em pouco tempo. Aguarde alguns minutos e tente novamente.";if(m.includes("network")||m.includes("fetch"))return"Não foi possível conectar agora. Verifique sua internet e tente novamente.";return"Não foi possível criar sua conta agora. Tente novamente em instantes.";}
function CriarContaPage(){const navigate=useNavigate();const[show,setShow]=useState(false);const[loading,setLoading]=useState(false);const[done,setDone]=useState(false);const[form,setForm]=useState({name:"",email:"",phone:"",pass:""});const[err,setErr]=useState<string|null>(null);const upd=(k:keyof typeof form)=>(e:React.ChangeEvent<HTMLInputElement>)=>setForm(f=>({...f,[k]:e.target.value}));
async function submit(e:React.FormEvent){e.preventDefault();setErr(null);if(!form.name||!form.email||!form.pass){setErr("Preencha todos os campos obrigatórios.");return;}if(form.pass.length<8){setErr("A senha precisa ter no mínimo 8 caracteres.");return;}setLoading(true);try{const redirectTo=typeof window!=="undefined"?`${window.location.origin}/colors/minha-conta`:undefined;const{data,error}=await supabase.auth.signUp({email:form.email.trim(),password:form.pass,options:{emailRedirectTo:redirectTo,data:{full_name:form.name.trim(),phone:form.phone.trim(),colors_customer:true}}});if(error)throw error;if(data.session){await supabase.rpc("colors_link_current_user" as never);navigate({to:"/colors/minha-conta"});return;}setDone(true);}catch(error:any){setErr(signupError(error?.message));}finally{setLoading(false)}}
if(done)return<AuthShell title="Confira seu e-mail" subtitle="Enviamos a confirmação da sua conta Colors."><div className="space-y-4 text-sm text-white/70"><p>Abra a mensagem de confirmação e conclua o cadastro. Depois, sua conta será vinculada ao seu histórico Colors pelo e-mail verificado.</p><Link to="/colors/entrar" className="inline-flex rounded-full bg-emerald-400 px-5 py-3 font-black text-black">Ir para o login</Link></div></AuthShell>;
return<AuthShell title="Criar sua conta Colors" subtitle="Sua conta conecta pedidos, atendimento, benefícios e histórico em um único lugar." footer={<>Já tem conta? <Link to="/colors/entrar" className="font-semibold text-emerald-300">Entrar</Link></>}><form onSubmit={submit} className="space-y-4"><Field label="Nome completo"><input required value={form.name} onChange={upd("name")} className={inputCls}/></Field><Field label="E-mail"><input type="email" autoComplete="email" required value={form.email} onChange={upd("email")} className={inputCls}/></Field><Field label="WhatsApp (opcional)"><input type="tel" value={form.phone} onChange={upd("phone")} className={inputCls}/></Field><Field label="Senha (mín. 8 caracteres)"><div className="relative"><input type={show?"text":"password"} autoComplete="new-password" required value={form.pass} onChange={upd("pass")} className={inputCls+" pr-11"}/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={show?"Ocultar senha":"Mostrar senha"} className="absolute right-2 top-1/2 grid h-8 w-8 -translate-y-1/2 place-items-center rounded-lg text-white/60 hover:bg-white/5">{show?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div></Field>{err&&<p className="rounded-lg border border-red-500/40 bg-red-500/10 px-3 py-2 text-sm text-red-300">{err}</p>}<button type="submit" disabled={loading} className="mt-2 inline-flex w-full items-center justify-center gap-2 rounded-full bg-gradient-to-r from-emerald-400 to-lime-400 px-6 py-3 text-sm font-black text-black disabled:opacity-70">{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<UserPlus className="h-4 w-4"/>}{loading?"Criando...":"Criar minha conta"}</button><p className="text-center text-[11px] text-white/40">Ao criar a conta, você concorda com os <Link to="/colors/termos" className="underline">Termos</Link> e a <Link to="/colors/privacidade" className="underline">Política de Privacidade</Link>.</p></form></AuthShell>}
