import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { CheckCircle2, MapPin, User, Loader2 } from "lucide-react";
import { AccountPageHeader } from "@/components/colors/account/AccountShell";
import { Field, inputCls } from "@/routes/colors.entrar";
import { useColorsDashboard } from "@/lib/colors-account";
import { supabase } from "@/integrations/supabase/client";
import { useQueryClient } from "@tanstack/react-query";

export const Route=createFileRoute("/colors/minha-conta/perfil")({head:()=>({meta:[{title:"Perfil — Colors Saúde"},{name:"robots",content:"noindex"}]}),component:PerfilPage});
function PerfilPage(){const qc=useQueryClient();const{data,isLoading}=useColorsDashboard();const[saving,setSaving]=useState(false);const[saved,setSaved]=useState(false);const[err,setErr]=useState<string|null>(null);const[form,setForm]=useState({name:"",email:"",phone:"",cep:"",street:"",number:"",complement:"",neighborhood:"",city:"",state:""});
useEffect(()=>{if(!data?.profile)return;setForm(f=>({...f,name:data.profile?.name??"",email:data.profile?.email??"",phone:data.profile?.whatsapp??""}));supabase.auth.getUser().then(({data:u})=>{const a=(u.user?.user_metadata as any)?.address??{};setForm(f=>({...f,cep:a.cep??f.cep,street:a.line1??f.street,number:a.number??f.number,complement:a.complement??f.complement,neighborhood:a.neighborhood??f.neighborhood,city:a.city??f.city,state:a.state??f.state}))});},[data]);
async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setErr(null);setSaved(false);try{const{error}=await supabase.rpc("colors_update_my_profile" as never,{p_full_name:form.name,p_whatsapp:form.phone||null,p_cep:form.cep||null,p_address_line1:form.street||null,p_address_number:form.number||null,p_address_complement:form.complement||null,p_neighborhood:form.neighborhood||null,p_city:form.city||null,p_state:form.state||null} as never);if(error)throw error;await supabase.auth.updateUser({data:{full_name:form.name,phone:form.phone,address:{cep:form.cep,line1:form.street,number:form.number,complement:form.complement,neighborhood:form.neighborhood,city:form.city,state:form.state}}});await qc.invalidateQueries({queryKey:["colors-my-dashboard"]});setSaved(true);}catch(error:any){setErr(error?.message??"Não foi possível salvar os dados.");}finally{setSaving(false)}}
if(isLoading)return<div className="flex items-center gap-2 text-sm text-white/60"><Loader2 className="h-4 w-4 animate-spin"/>Carregando perfil…</div>;
return<><AccountPageHeader title="Perfil e endereço" icon={User} description="Dados usados pela Colors para identificação, atendimento e entregas quando aplicável."/><form onSubmit={save} className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="text-sm font-black uppercase tracking-widest text-white/70">Dados pessoais</h2><div className="mt-4 space-y-3"><Field label="Nome completo"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className={inputCls}/></Field><Field label="E-mail verificado"><input type="email" value={form.email} disabled className={inputCls+" opacity-60"}/></Field><Field label="WhatsApp"><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className={inputCls}/></Field><p className="text-xs text-white/45">O e-mail é a identidade principal desta conta e não é alterado por este formulário.</p></div></section><section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="flex items-center gap-2 text-sm font-black uppercase tracking-widest text-white/70"><MapPin className="h-3.5 w-3.5 text-emerald-400"/>Endereço</h2><div className="mt-4 space-y-3"><div className="grid grid-cols-[1fr_2fr] gap-3"><Field label="CEP"><input value={form.cep} onChange={e=>setForm({...form,cep:e.target.value})} className={inputCls}/></Field><Field label="Rua/Avenida"><input value={form.street} onChange={e=>setForm({...form,street:e.target.value})} className={inputCls}/></Field></div><div className="grid grid-cols-2 gap-3"><Field label="Número"><input value={form.number} onChange={e=>setForm({...form,number:e.target.value})} className={inputCls}/></Field><Field label="Complemento"><input value={form.complement} onChange={e=>setForm({...form,complement:e.target.value})} className={inputCls}/></Field></div><div className="grid grid-cols-2 gap-3"><Field label="Bairro"><input value={form.neighborhood} onChange={e=>setForm({...form,neighborhood:e.target.value})} className={inputCls}/></Field><Field label="Cidade"><input value={form.city} onChange={e=>setForm({...form,city:e.target.value})} className={inputCls}/></Field></div><Field label="UF"><input maxLength={2} value={form.state} onChange={e=>setForm({...form,state:e.target.value.toUpperCase()})} className={inputCls}/></Field></div></section><div className="lg:col-span-2">{err&&<p className="mb-3 text-sm text-red-300">{err}</p>}<button disabled={saving} className="inline-flex items-center gap-2 rounded-full bg-emerald-500 px-5 py-2.5 text-sm font-bold text-black disabled:opacity-60">{saving?<Loader2 className="h-4 w-4 animate-spin"/>:saved?<CheckCircle2 className="h-4 w-4"/>:null}{saving?"Salvando...":saved?"Dados salvos":"Salvar dados"}</button></div></form></>}
