import { createFileRoute, Link } from "@tanstack/react-router";
import { Package, ShoppingBag, Truck, Users, ArrowRight, ShieldAlert, Loader2 } from "lucide-react";
import { AccountPageHeader, OrderStatusBadge } from "@/components/colors/account/AccountShell";
import { useColorsDashboard, formatBRL, formatDatePt, trackingCode, carrierName } from "@/lib/colors-account";

export const Route=createFileRoute("/colors/minha-conta/")({head:()=>({meta:[{title:"Painel — Minha conta Colors Saúde"},{name:"robots",content:"noindex"}]}),component:AccountIndex});
function AccountIndex(){const{data,isLoading}=useColorsDashboard();if(isLoading)return<div className="flex items-center gap-2 text-sm text-white/60"><Loader2 className="h-4 w-4 animate-spin"/>Carregando sua conta…</div>;const orders=data?.orders??[];const active=orders.find(o=>!["fulfilled","cancelled","refunded","delivered"].includes(o.status));const firstName=data?.profile?.name?.split(/\s+/)[0]||"cliente";const group=data?.group_access;
return<><AccountPageHeader title={`Olá, ${firstName}!`} description="Pedidos, atendimento e benefícios oficiais reunidos no seu Customer 360°."/><div className="grid gap-4 sm:grid-cols-3"><Kpi icon={ShoppingBag} label="Pedidos" value={String(orders.length)}/><Kpi icon={Truck} label="Em andamento" value={String(orders.filter(o=>!["fulfilled","cancelled","refunded"].includes(o.status)).length)} accent={!!active}/><Kpi icon={Users} label="Comunidade Colors" value={group?.status==="eligible"||group?.status==="invited"||group?.status==="joined"?"Elegível":"Aguardando"}/></div>
{active&&<section className="mt-6 rounded-2xl border border-emerald-400/25 bg-gradient-to-br from-emerald-500/10 to-lime-500/5 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-300">Pedido em andamento</p><h2 className="mt-1 text-xl font-bold">{active.number}</h2><p className="text-xs text-white/60">Feito em {formatDatePt(active.created_at)}</p></div><OrderStatusBadge status={active.status}/></div><p className="mt-4 text-sm text-white/70">{active.items?.[0]?.description? <span className="font-semibold text-white">{active.items[0].description}</span>:"Pedido Colors"}{carrierName(active)?` · ${carrierName(active)}`:""}</p><div className="mt-5 flex flex-wrap gap-2"><Link to="/colors/minha-conta/pedidos/$id" params={{id:active.id}} className="inline-flex items-center gap-1.5 rounded-full bg-emerald-500 px-4 py-2 text-sm font-bold text-black">Ver detalhes <ArrowRight className="h-3.5 w-3.5"/></Link>{trackingCode(active)&&<Link to="/colors/rastreio/$codigo" params={{codigo:trackingCode(active)}} className="rounded-full border border-white/15 bg-white/5 px-4 py-2 text-sm font-semibold">Rastrear</Link>}</div></section>}
<section className="mt-8"><div className="mb-3 flex items-end justify-between"><h2 className="text-lg font-bold">Últimos pedidos</h2>{orders.length>0&&<Link to="/colors/minha-conta/pedidos" className="text-sm font-semibold text-emerald-300">Ver todos →</Link>}</div>{orders.length===0?<div className="rounded-2xl border border-dashed border-white/15 p-8 text-center"><Package className="mx-auto h-8 w-8 text-white/30"/><p className="mt-3 text-sm text-white/60">Ainda não há pedidos vinculados ao e-mail desta conta.</p><Link to="/colors" className="mt-4 inline-flex rounded-full bg-emerald-400 px-5 py-2.5 text-sm font-black text-black">Conhecer produtos oficiais</Link></div>:<div className="grid gap-3">{orders.slice(0,3).map(o=><Link key={o.id} to="/colors/minha-conta/pedidos/$id" params={{id:o.id}} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-white/10 bg-white/[.03] p-4 hover:bg-white/[.06]"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-white/5 text-emerald-300"><Package className="h-5 w-5"/></div><div><p className="font-bold">{o.number} · {o.items?.[0]?.description??"Pedido Colors"}</p><p className="text-xs text-white/50">{formatDatePt(o.created_at)}{carrierName(o)?` · ${carrierName(o)}`:""}</p></div></div><div className="flex items-center gap-3"><OrderStatusBadge status={o.status}/><span className="text-sm font-bold">{formatBRL(o.total)}</span></div></Link>)}</div>}</section>
{group?.status==="eligible"&&<div className="mt-8 rounded-2xl border border-emerald-400/25 bg-emerald-500/10 p-5"><h2 className="font-black">Você está elegível para a comunidade Colors.</h2><p className="mt-2 text-sm text-white/65">A Íris pode liberar o convite após validar sua compra. O link não é exposto publicamente.</p></div>}
<div className="mt-8 flex items-start gap-3 rounded-2xl border border-amber-400/25 bg-amber-500/10 p-4"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-amber-300"/><p className="text-sm text-amber-100/90">Compre sempre pelos <strong>canais oficiais da Colors Saúde</strong>. Nenhum pedido, rastreio ou benefício é fabricado nesta área: exibimos somente dados associados à sua conta.</p></div></>}
function Kpi({icon:Icon,label,value,accent}:{icon:React.ComponentType<{className?:string}>;label:string;value:string;accent?:boolean}){return<div className={"rounded-2xl border p-4 "+(accent?"border-emerald-400/30 bg-emerald-500/10":"border-white/10 bg-white/[.03]")}><div className="flex items-center gap-2 text-xs uppercase tracking-widest text-white/60"><Icon className="h-4 w-4 text-emerald-400"/>{label}</div><div className="mt-2 text-2xl font-black">{value}</div></div>}
