import { createFileRoute, Link } from "@tanstack/react-router";
import { AlertTriangle, ArrowLeft, ArrowRight, Bell, BookOpenCheck, BriefcaseBusiness, FileText, Gauge, LockKeyhole, Radar, ShieldCheck, TrendingUp, UserRoundCheck } from "lucide-react";

export const Route = createFileRoute("/csi/portal")({ component: CsiInvestorPortal });

const cards = [
  { icon: Gauge, title: "Visão consolidada", text: "Patrimônio, alocação, evolução e concentração quando a fonte financeira homologada estiver conectada." },
  { icon: TrendingUp, title: "Mercados", text: "Índices, juros, câmbio, inflação e sinais macro com origem, horário e contexto." },
  { icon: Radar, title: "CSI Radar", text: "Fatos e eventos filtrados por impacto patrimonial, setor, risco e relevância." },
  { icon: Bell, title: "Alertas", text: "Preferências de comunicação, criticidade, vencimentos, documentos e eventos de mercado." },
  { icon: FileText, title: "Documentos", text: "Relatórios, comprovantes, termos e documentos com histórico e controle de acesso." },
  { icon: UserRoundCheck, title: "Perfil & suitability", text: "Objetivos, horizonte, liquidez, conhecimento, experiência e tolerância a risco." },
];
const journey = ["Identificação","Objetivos","Suitability","Consentimentos","Curadoria CSI","Parceiro regulado","Acompanhamento"];

function CsiInvestorPortal() {
  return <main className="min-h-screen bg-[#07111b] text-white selection:bg-amber-300 selection:text-slate-950">
    <header className="sticky top-0 z-20 border-b border-white/10 bg-[#08141f]/90 backdrop-blur-xl"><div className="mx-auto max-w-7xl px-5 py-4 flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-amber-300">CSI Invest</p><p className="font-semibold">Private Intelligence Hub</p></div><Link to="/csi" className="inline-flex items-center gap-2 text-sm text-slate-300 hover:text-white"><ArrowLeft className="h-4 w-4"/> Portal CSI</Link></div></header>
    <section className="mx-auto max-w-7xl px-5 py-12 md:py-16">
      <div className="grid lg:grid-cols-12 gap-8 items-start"><div className="lg:col-span-8"><span className="inline-flex items-center gap-2 rounded-full border border-emerald-300/20 bg-emerald-300/10 px-3 py-1 text-xs text-emerald-200"><ShieldCheck className="h-3.5 w-3.5"/> arquitetura private-by-design</span><h1 className="mt-5 text-4xl md:text-6xl font-semibold tracking-tight">Seu patrimônio merece contexto, não ruído.</h1><p className="mt-5 max-w-3xl text-lg text-slate-400">Um hub de relacionamento, inteligência e acompanhamento para investidores CSI. A experiência reúne informação, documentos, preferências, suitability e acesso ao assessor sem transformar a CSI em custodiante ou bolsa de valores.</p></div><aside className="lg:col-span-4 rounded-3xl border border-amber-300/20 bg-amber-300/[.07] p-6"><LockKeyhole className="h-6 w-6 text-amber-300"/><h2 className="mt-4 font-semibold">Regra de confiança</h2><p className="mt-2 text-sm leading-relaxed text-slate-400">Nenhum saldo, rentabilidade, produto ou posição é inventado. Sem fonte homologada, o sistema informa a indisponibilidade — nunca preenche o painel com dados fictícios.</p></aside></div>
      <div className="mt-12 grid md:grid-cols-2 lg:grid-cols-3 gap-4">{cards.map(({icon:Icon,title,text})=><article key={title} className="rounded-3xl border border-white/10 bg-white/[.04] p-6 transition hover:border-amber-300/25"><Icon className="h-6 w-6 text-amber-300"/><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="mt-2 text-sm leading-relaxed text-slate-400">{text}</p></article>)}</div>
      <section className="mt-12 rounded-[30px] border border-white/10 bg-[#0b1824] p-7 md:p-9"><div className="flex gap-4"><BriefcaseBusiness className="h-7 w-7 shrink-0 text-amber-300"/><div><p className="text-xs uppercase tracking-[.18em] text-amber-300">Jornada transparente</p><h2 className="mt-2 text-2xl font-semibold">Do interesse ao investimento, sem caixa-preta.</h2><p className="mt-2 max-w-3xl text-sm leading-relaxed text-slate-400">A CSI organiza a intenção, valida elegibilidade e suitability e prepara o encaminhamento à instituição regulada homologada. Confirmação de ordem, custódia e liquidação permanecem no parceiro autorizado até que exista integração formalmente homologada.</p></div></div><div className="mt-7 grid sm:grid-cols-2 lg:grid-cols-7 gap-2">{journey.map((x,i)=><div key={x} className="rounded-2xl border border-white/10 bg-black/10 p-3"><span className="text-[10px] text-slate-600">0{i+1}</span><p className="mt-1 text-xs font-medium text-slate-300">{x}</p></div>)}</div></section>
      <div className="mt-10 rounded-3xl border border-amber-300/20 bg-gradient-to-r from-amber-300/[.10] to-transparent p-7 flex flex-col md:flex-row gap-5 md:items-center md:justify-between"><div className="flex gap-4"><BookOpenCheck className="h-7 w-7 shrink-0 text-amber-300"/><div><h2 className="font-semibold">Checkout transparente CSI</h2><p className="mt-1 text-sm text-slate-400">A estrutura já está preparada para receber as APIs homologadas de broker, KYC e dados.</p></div></div><Link to="/csi/checkout" className="inline-flex items-center justify-center gap-2 rounded-full bg-amber-300 px-5 py-3 text-sm font-semibold text-slate-950">Abrir jornada <ArrowRight className="h-4 w-4"/></Link></div>
      <p className="mt-5 flex items-start gap-2 text-xs leading-relaxed text-slate-600"><AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0"/> Produtos, execução, custódia, liquidação e dados de carteira dependem das instituições reguladas e integrações efetivamente contratadas e homologadas. A interface CSI não constitui promessa de rentabilidade nem recomendação automática.</p>
    </section>
  </main>;
}
