import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, BarChart3, Building2, Calendar, Layers, MessageCircle, PlayCircle, ShoppingCart, Sparkles, UserRound, Users, Boxes, ReceiptText, Workflow, Mail, MessageSquareText, Headphones, Stethoscope, PackageSearch } from "lucide-react";
import { PublicHeader } from "@/components/marketing/PublicHeader";
import { PublicFooter } from "@/components/marketing/PublicFooter";
import { DemoModeBanner } from "@/components/demo/DemoModeBanner";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { NICHO_DETAILS } from "@/components/marketing/nichoDetails";
import { getDemoNichoLink } from "@/lib/demoResolver";
import { trackFunnelCta } from "@/lib/funnelTracking";
import { openImpulsionito } from "@/lib/impulsionito-tracking";

export const Route = createFileRoute("/demo/")({head:()=>({meta:[{title:"Demonstração guiada do Ecossistema Impulsionando"},{name:"description",content:"Ambiente exclusivamente demonstrativo para empresários conhecerem ERP, CRM, estoque, fiscal, agenda, automações, suporte e Impulsionito antes da contratação."}],links:[{rel:"canonical",href:"https://impulsionando.com.br/demo"}]}),component:DemoLanding});

const AUDIENCES=[{icon:Building2,badge:"Empresas",title:"Veja o que sua empresa recebe",description:"Dashboard guiado com ERP, CRM, vendas, estoque, fiscal, automações, BI e atendimento.",to:"/demo/modulos"},{icon:Layers,badge:"White Label",title:"Operação White Label",description:"Marca própria, provisionamento, módulos, clientes e governança multiempresa.",to:"/demo/white-label"},{icon:UserRound,badge:"Consumidor",title:"Jornada do cliente final",description:"Cadastro, relacionamento, benefícios, agenda, pedidos, satisfação e recorrência.",to:"/demo/cliente-final"}] as const;
const MODULES=[{icon:BarChart3,title:"Dashboard + BI",desc:"Indicadores, vendas, conversão, operação e relatórios exportáveis.",to:"/demo/modulos"},{icon:Users,title:"CRM",desc:"Lead, cliente, histórico, follow-up, segmentação e jornadas.",to:"/demo/crm"},{icon:Boxes,title:"ERP + estoque",desc:"Produtos, entradas, baixas, disponibilidade, compras e logística.",to:"/demo/modulos"},{icon:ReceiptText,title:"Fiscal",desc:"Fluxo de venda conectado à emissão fiscal e registros da operação.",to:"/demo/modulos"},{icon:ShoppingCart,title:"Checkout",desc:"Pix, cartão, recuperação e conciliação conforme integrações contratadas.",to:"/demo/checkout"},{icon:Workflow,title:"Automações",desc:"Boas-vindas, recuperação, lembretes, pós-venda, NPS e réguas configuráveis.",to:"/demo/modulos"},{icon:Mail,title:"Templates de e-mail",desc:"Cliente visualiza e edita textos autorizados ou solicita apoio da gestão.",to:"/demo/modulos"},{icon:MessageSquareText,title:"WhatsApp",desc:"Templates, jornadas, atendimento e mensagens editáveis conforme governança.",to:"/demo/whatsapp"},{icon:Stethoscope,title:"Clínicas e saúde",desc:"Agenda, pega-agenda, antecipação, confirmações, lembretes e fluxos assistenciais não clínicos.",to:"/demo/agenda"},{icon:PackageSearch,title:"Produtos e logística",desc:"SKU, estoque, baixa, localização e visão integrada da cadeia operacional.",to:"/demo/modulos"},{icon:Headphones,title:"Suporte e incrementos",desc:"Solicitação pelo Impulsionito, protocolo, SLA, validação e encaminhamento ao comitê.",to:"/demo/modulos"},{icon:Calendar,title:"Agenda inteligente",desc:"Disponibilidade, encaixes, antecipação, bloqueios e disparos automáticos.",to:"/demo/agenda"}] as const;

function DemoLanding(){return <div className="min-h-dvh flex flex-col bg-background"><PublicHeader/><DemoModeBanner/><main className="flex-1 mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 py-12 w-full"><header className="text-center max-w-4xl mx-auto mb-12"><Badge className="bg-gradient-primary mb-4">ÚNICA ÁREA DEMONSTRATIVA</Badge><h1 className="text-3xl sm:text-5xl font-bold tracking-tight">Veja exatamente como será operar com a Impulsionando</h1><p className="mt-4 text-base sm:text-lg text-muted-foreground leading-relaxed">Aqui os dados são sintéticos e identificados como demonstração. O desenho funcional reproduz a experiência contratada: macro nicho → micro nicho → dashboard → módulos → Impulsionito guiando cada etapa. Fora de /demo, o ecossistema usa somente dados reais.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><Button asChild size="lg"><Link to="/demo/modulos">Explorar dashboard e módulos <ArrowRight className="ml-2 h-4 w-4"/></Link></Button><Button type="button" size="lg" variant="outline" onClick={()=>openImpulsionito("demo-hub-hero")}><Sparkles className="mr-2 h-4 w-4"/>Impulsionito, me guie</Button></div></header>
<section className="mb-14"><div className="mb-5"><div className="text-xs font-semibold uppercase tracking-wider text-primary">Por público</div><h2 className="text-2xl font-semibold">Comece pela sua operação</h2></div><div className="grid gap-5 md:grid-cols-3">{AUDIENCES.map(({icon:Icon,badge,title,description,to})=><Card key={badge} className="p-6 flex flex-col"><Icon className="h-6 w-6 text-primary"/><Badge variant="outline" className="self-start mt-4">{badge}</Badge><h3 className="mt-3 text-xl font-semibold">{title}</h3><p className="mt-2 text-sm text-muted-foreground flex-1">{description}</p><Button asChild className="mt-5"><Link to={to}><PlayCircle className="mr-2 h-4 w-4"/>Abrir demonstração</Link></Button></Card>)}</div></section>
<section className="mb-14"><div className="mb-5 flex items-end justify-between"><div><div className="text-xs font-semibold uppercase tracking-wider text-primary">Macro → micro nichos</div><h2 className="text-2xl font-semibold">Entre no cenário do seu setor</h2></div><span className="text-xs text-muted-foreground">{NICHO_DETAILS.length} cenários</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{NICHO_DETAILS.map(n=>{const Icon=n.icon;const link=getDemoNichoLink(n.slug);return <Card key={n.slug} className="p-5 flex flex-col"><div className="flex items-start gap-3"><div className="w-10 h-10 rounded-lg bg-primary/10 text-primary grid place-items-center"><Icon className="h-5 w-5"/></div><div><h3 className="font-semibold">{n.shortLabel}</h3><Badge variant="outline" className="mt-1 text-[10px]">Cenário demonstrativo</Badge></div></div><p className="mt-3 text-sm text-muted-foreground flex-1">{n.cardDesc}</p><Button asChild size="sm" className="mt-4"><Link to={link.to} params={link.params} onClick={()=>trackFunnelCta({cta:"hub-demo-abrir-nicho",origem:"hub-demo",nicho_pedido:n.slug,alias_resolvido:link.slug,isFallback:link.isFallback,rotaDestino:`/demo/nicho/${link.slug}`})}>Abrir nicho</Link></Button></Card>})}</div></section>
<section className="mb-14"><div className="mb-5"><div className="text-xs font-semibold uppercase tracking-wider text-primary">O que o contratado recebe</div><h2 className="text-2xl font-semibold">Gestão completa, configurável e guiada</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{MODULES.map(({icon:Icon,title,desc,to})=><Card key={title} className="p-5 flex flex-col"><Icon className="h-5 w-5 text-primary"/><h3 className="font-semibold mt-3">{title}</h3><p className="mt-2 text-sm text-muted-foreground flex-1">{desc}</p><Button asChild size="sm" variant="outline" className="mt-4"><Link to={to}>Ver funcionando</Link></Button></Card>)}</div></section>
<section className="rounded-xl border-2 border-primary/40 bg-primary/5 p-6 sm:p-8"><div className="grid gap-5 md:grid-cols-[1fr_auto] md:items-center"><div><Badge className="mb-2 bg-gradient-primary"><Sparkles className="mr-1 h-3 w-3"/>Impulsionito guiado</Badge><h2 className="text-2xl font-semibold">Peça, fale ou digite o que quer entender</h2><p className="mt-2 text-sm text-muted-foreground max-w-2xl">Na demonstração, o Impulsionito explica módulos e cenários. No ambiente contratado, ele também organiza solicitações do cliente para validação e aceite antes do encaminhamento ao time/comitê Impulsionando.</p></div><Button type="button" onClick={()=>openImpulsionito("demo-hub-final")}><MessageCircle className="mr-2 h-4 w-4"/>Falar com Impulsionito</Button></div></section></main><PublicFooter/></div>}
