import { createFileRoute } from '@tanstack/react-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { getGrupoSmartDashboard, moveGrupoSmartLead, saveGrupoSmartLead } from '@/lib/gruposmart.functions';
import { BarChart3, Bot, CalendarDays, Coffee, LayoutDashboard, Plus, RefreshCw, ShoppingBasket, Sparkles, Users } from 'lucide-react';
import { useState } from 'react';

export const Route = createFileRoute('/gruposmart/app')({ component: GrupoSmartApp });
const stages:any = {new:'Novo',contacting:'Contato',qualified:'Qualificado',meeting:'Reunião',visit:'Visita',proposal:'Proposta',negotiation:'Negociação',won:'Ganho',lost:'Perdido'};

function GrupoSmartApp(){
 const qc=useQueryClient(); const [open,setOpen]=useState(false);
 const q=useQuery({queryKey:['gruposmart-dashboard'],queryFn:()=>getGrupoSmartDashboard()});
 const move=useMutation({mutationFn:(x:any)=>moveGrupoSmartLead({data:x}),onSuccess:()=>qc.invalidateQueries({queryKey:['gruposmart-dashboard']})});
 const save=useMutation({mutationFn:(x:any)=>saveGrupoSmartLead({data:x}),onSuccess:()=>{setOpen(false);qc.invalidateQueries({queryKey:['gruposmart-dashboard']})}});
 const d:any=q.data ?? {metrics:{},leads:[],activities:[]};
 return <main className="min-h-screen bg-slate-100 text-slate-950">
  <header className="border-b bg-slate-950 text-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4"><div><a href="/gruposmart" className="font-black">GRUPO <span className="text-sky-400">SMART</span></a><p className="text-xs text-slate-400">Plano Full · Impulsionando Tecnologia</p></div><div className="flex items-center gap-3"><span className="hidden text-xs text-slate-400 md:block">Smartito ativo · CRM + Jornadas + BI</span><button onClick={()=>q.refetch()} className="rounded-lg border border-white/15 p-2"><RefreshCw size={17}/></button><button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-lg bg-sky-500 px-4 py-2 text-sm font-bold text-slate-950"><Plus size={17}/> Novo lead</button></div></div></header>
  <div className="mx-auto max-w-[1500px] p-5 md:p-7">
   <section className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[[d.metrics.total,'Leads',Users],[d.metrics.wizmart,'wizMart',ShoppingBasket],[d.metrics.smartCafe,'Smart Café',Coffee],[d.metrics.qualified,'Qualificados',Sparkles],[d.metrics.won,'Ganhos',BarChart3],[d.metrics.crossSell,'Cross-sell',Bot]].map(([n,t,I]:any)=><article key={t} className="rounded-2xl border bg-white p-4 shadow-sm"><I size={18} className="text-sky-600"/><p className="mt-4 text-3xl font-black">{n??0}</p><p className="text-xs font-semibold text-slate-500">{t}</p></article>)}</section>
   <section className="grid gap-6 xl:grid-cols-[1fr_340px]"><div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><h1 className="text-xl font-black">Pipeline unificado</h1><p className="text-sm text-slate-500">Cicatriz por vertical, origem e estágio.</p></div><LayoutDashboard className="text-sky-600"/></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Conta</th><th>Vertical</th><th>Origem</th><th>Local</th><th>Estágio</th><th>Cross-sell</th></tr></thead><tbody>{q.isLoading?<tr><td className="p-6" colSpan={6}>Carregando cockpit...</td></tr>:d.leads.length===0?<tr><td className="p-8 text-center text-slate-500" colSpan={6}>Base pronta. Cadastre o primeiro lead para iniciar a operação.</td></tr>:d.leads.map((l:any)=><tr key={l.id} className="border-t"><td className="p-4"><b>{l.company_name}</b><div className="text-xs text-slate-500">{l.contact_name||l.email||'Contato a qualificar'}</div></td><td><span className="rounded-full bg-sky-50 px-2 py-1 text-xs font-bold text-sky-700">{l.vertical}</span></td><td>{l.source}</td><td>{[l.city,l.state].filter(Boolean).join(' / ')||'—'}</td><td><select value={l.stage} onChange={e=>move.mutate({id:l.id,stage:e.target.value})} className="rounded-lg border bg-white p-2">{Object.entries(stages).map(([v,n]:any)=><option value={v} key={v}>{n}</option>)}</select></td><td>{l.cross_sell_eligible?'Sim':'—'}</td></tr>)}</tbody></table></div></div>
    <aside className="space-y-4"><article className="rounded-2xl bg-slate-950 p-5 text-white"><Bot className="text-sky-400"/><h2 className="mt-4 text-xl font-black">Smartito</h2><p className="mt-2 text-sm leading-6 text-slate-400">Instância especializada do Impulsionito para identificar negócio, intenção, praça, ICP, estágio e próxima melhor ação.</p><div className="mt-4 rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-slate-300">Modo: copiloto comercial Full</div></article><article className="rounded-2xl border bg-white p-5"><CalendarDays className="text-sky-600"/><h2 className="mt-4 font-black">Próximas atividades</h2><div className="mt-3 space-y-2">{d.activities.slice(0,8).map((a:any)=><div key={a.id} className="rounded-xl bg-slate-50 p-3"><b className="text-sm">{a.title}</b><p className="text-xs text-slate-500">{a.type} · {new Date(a.scheduled_at).toLocaleString('pt-BR')}</p></div>)}{!d.activities.length&&<p className="text-sm text-slate-500">Agenda pronta para reuniões online, visitas e follow-ups.</p>}</div></article></aside>
   </section>
  </div>
  {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/70 p-4"><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save.mutate({company_name:f.get('company_name'),contact_name:f.get('contact_name')||null,email:f.get('email')||null,phone:f.get('phone')||null,city:f.get('city')||null,state:f.get('state')||null,vertical:f.get('vertical'),source:f.get('source'),stage:'new',cross_sell_eligible:f.get('cross_sell_eligible')==='on'})}} className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-2xl font-black">Novo lead</h2><p className="text-sm text-slate-500">Cadastro único Grupo Smart.</p></div><button type="button" onClick={()=>setOpen(false)}>✕</button></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><input required name="company_name" placeholder="Empresa / condomínio" className="rounded-xl border p-3 sm:col-span-2"/><input name="contact_name" placeholder="Contato" className="rounded-xl border p-3"/><input name="email" type="email" placeholder="E-mail" className="rounded-xl border p-3"/><input name="phone" placeholder="WhatsApp / telefone" className="rounded-xl border p-3"/><input name="city" placeholder="Cidade" className="rounded-xl border p-3"/><input name="state" placeholder="UF" className="rounded-xl border p-3"/><select name="vertical" className="rounded-xl border p-3"><option value="undetermined">A qualificar</option><option value="wizmart">wizMart</option><option value="smart_cafe">Smart Café</option><option value="both">Ambas</option></select><select name="source" className="rounded-xl border p-3"><option value="manual">Manual</option><option value="inbound">Inbound</option><option value="outbound">Outbound</option><option value="field_sales">Executivo de campo</option><option value="referral">Indicação</option></select><label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" name="cross_sell_eligible"/> Potencial de cross-sell entre as duas soluções</label></div><button disabled={save.isPending} className="mt-6 w-full rounded-xl bg-sky-500 p-3 font-black">{save.isPending?'Salvando...':'Criar lead e iniciar jornada'}</button></form></div>}
 </main>
}
