import { createFileRoute } from '@tanstack/react-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { getGrupoSmartDashboard, moveGrupoSmartLead, saveGrupoSmartLead } from '@/lib/gruposmart.functions';
import { BarChart3, Bot, CalendarDays, Coffee, FileText, LayoutDashboard, Mail, MessageCircle, PackageCheck, Plus, QrCode, RefreshCw, ShoppingBasket, Sparkles, Users, WalletCards } from 'lucide-react';
import { useState } from 'react';

export const Route = createFileRoute('/gruposmart/app')({ component: GrupoSmartApp });
const stages:any={new:'Novo',contacting:'Contato',qualified:'Qualificado',meeting:'Reunião',visit:'Visita',proposal:'Proposta',negotiation:'Negociação',won:'Ganho',lost:'Perdido'};
const audiences=['Leads e decisores','Clientes ativos','Síndicos e administradoras','RH e facilities','Colaboradores','Candidatos','Fornecedores','Executivos de campo'];
const channels=['Chat privado','WhatsApp','E-mail','Instagram','Facebook','TikTok'];
const fullModules=[['CRM & Pipeline','Cadastro único, ICP, origem, owner, SLA, histórico e cross-sell.',LayoutDashboard],['ERP','Cadastros, produtos/serviços, unidades, propostas, contratos e operação.',PackageCheck],['Agenda & vídeo','Reuniões, visitas, lembretes, no-show e teleatendimento com player próprio.',CalendarDays],['Cobrança & faturas','Links, documentos, histórico e régua financeira.',WalletCards],['Arquivos','Propostas, contratos, apresentações e documentos por público.',FileText],['Fornecedores','Cadastro, qualificação, documentos, SLA e relacionamento.',PackageCheck],['WhatsApp QR/API','Conexão por QR Code quando aplicável ou API oficial homologada.',QrCode],['Omnichannel','Uma inteligência e histórico contínuo em todos os canais.',MessageCircle]];
const chronology=[['1','Captação','Outbound/ABM é o motor principal; inbound e marketing entram como apoio e aquecimento.'],['2','Qualificação Hunter','ICP, decisor, aderência, região, vertical, potencial e próxima ação.'],['3','Agenda','Reunião online ou visita de campo, disponibilidade, lembretes e no-show.'],['4','Diagnóstico & proposta','Executivo recebe contexto, registra diagnóstico, proposta e negociação.'],['5','Conversão','Aceite, documentos e cobrança/contratação em ambiente autorizado.'],['6','Implantação ERP','Cliente, unidade, serviço, operação, responsáveis e histórico passam ao ERP.'],['7','Relacionamento','Smartito, jornadas, NPS, suporte, reativação e cross-sell wizMart ↔ Smart Café.']];

function GrupoSmartApp(){
 const qc=useQueryClient();const[open,setOpen]=useState(false);const q=useQuery({queryKey:['gruposmart-dashboard'],queryFn:()=>getGrupoSmartDashboard()});
 const move=useMutation({mutationFn:(x:any)=>moveGrupoSmartLead({data:x}),onSuccess:()=>qc.invalidateQueries({queryKey:['gruposmart-dashboard']})});
 const save=useMutation({mutationFn:(x:any)=>saveGrupoSmartLead({data:x}),onSuccess:()=>{setOpen(false);qc.invalidateQueries({queryKey:['gruposmart-dashboard']})}});
 const d:any=q.data??{metrics:{},leads:[],activities:[],journeys:[],agentEvents:[]};
 return <main className="min-h-screen bg-slate-100 text-slate-950" data-environment="demo">
  <div className="sticky top-0 z-50 border-b border-amber-400 bg-amber-300 px-4 py-2 text-center text-xs font-black uppercase tracking-[.14em]">DEMONSTRAÇÃO · Ambiente de avaliação · operações e cobranças são simulações</div>
  <header className="border-b bg-slate-950 text-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4"><div><a href="/gruposmart" className="font-black">GRUPO <span className="text-sky-400">SMART</span></a><p className="text-xs text-slate-400">Plano Full · Core Impulsionando</p></div><div className="flex items-center gap-3"><span className="hidden text-xs text-slate-400 md:block">Smartito · cérebro vivo omnichannel</span><button onClick={()=>q.refetch()} className="rounded-lg border border-white/15 p-2"><RefreshCw size={17}/></button><button onClick={()=>setOpen(true)} className="flex items-center gap-2 rounded-lg bg-sky-500 px-4 py-2 text-sm font-bold text-slate-950"><Plus size={17}/> Novo lead</button></div></div></header>
  <div className="mx-auto max-w-[1500px] p-5 md:p-7">
   <section className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{[[d.metrics.total,'Leads',Users],[d.metrics.wizmart,'wizMart',ShoppingBasket],[d.metrics.smartCafe,'Smart Café',Coffee],[d.metrics.qualified,'Qualificados',Sparkles],[d.metrics.won,'Ganhos',BarChart3],[d.metrics.crossSell,'Cross-sell',Bot],[d.metrics.journeys,'Jornadas',Mail],[d.metrics.agentEvents,'IA eventos',MessageCircle]].map(([n,t,I]:any)=><article key={t} className="rounded-2xl border bg-white p-4 shadow-sm"><I size={18} className="text-sky-600"/><p className="mt-3 text-2xl font-black">{n??0}</p><p className="text-xs font-semibold text-slate-500">{t}</p></article>)}</section>
   <section className="mb-6 rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-sky-600">Cronologia operacional Full</p><h1 className="mt-1 text-xl font-black">Uma ordem única do lead ao relacionamento</h1><p className="mt-1 text-sm text-slate-500">Marketing apoia e aquece; prospecção ativa e inteligência comercial alimentam prioritariamente os Hunters.</p></div><div className="rounded-xl border border-amber-300 bg-amber-50 p-3 text-xs text-amber-900"><b>DEMO:</b> mensagens, propostas e cobranças devem sair sempre chanceladas como demonstração.</div></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-7">{chronology.map(([n,t,desc])=><article key={n} className="rounded-xl bg-slate-50 p-4"><span className="grid h-7 w-7 place-items-center rounded-full bg-sky-600 text-xs font-black text-white">{n}</span><h3 className="mt-3 text-sm font-black">{t}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{desc}</p></article>)}</div></section>
   <section className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="space-y-6"><div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><h2 className="text-xl font-black">Pipeline unificado</h2><p className="text-sm text-slate-500">Cadastro único com cicatriz por vertical, origem e estágio.</p></div><LayoutDashboard className="text-sky-600"/></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Conta</th><th>Vertical</th><th>Origem</th><th>Local</th><th>Estágio</th><th>Cross-sell</th></tr></thead><tbody>{q.isLoading?<tr><td className="p-6" colSpan={6}>Carregando cockpit...</td></tr>:d.leads.length===0?<tr><td className="p-8 text-center text-slate-500" colSpan={6}>Base pronta. Cadastre o primeiro lead para iniciar a operação.</td></tr>:d.leads.map((l:any)=><tr key={l.id} className="border-t"><td className="p-4"><b>{l.company_name}</b><div className="text-xs text-slate-500">{l.contact_name||l.email||'Contato a qualificar'}</div></td><td><span className="rounded-full bg-sky-50 px-2 py-1 text-xs font-bold text-sky-700">{l.vertical}</span></td><td>{l.source}</td><td>{[l.city,l.state].filter(Boolean).join(' / ')||'—'}</td><td><select value={l.stage} onChange={e=>move.mutate({id:l.id,stage:e.target.value})} className="rounded-lg border bg-white p-2">{Object.entries(stages).map(([v,n]:any)=><option value={v} key={v}>{n}</option>)}</select></td><td>{l.cross_sell_eligible?'Sim':'—'}</td></tr>)}</tbody></table></div></div>
    <section><div className="mb-3"><p className="text-xs font-black uppercase tracking-[.18em] text-sky-600">Módulos do Plano Full</p><h2 className="text-xl font-black">Core integrado, sem ilhas</h2></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{fullModules.map(([title,desc,I]:any)=><article key={title} className="rounded-2xl border bg-white p-5"><I className="text-sky-600"/><h3 className="mt-4 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{desc}</p></article>)}</div></section>
    <div className="grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border bg-white p-5"><h2 className="font-black">Públicos atendidos</h2><p className="mt-1 text-sm text-slate-500">Smartito muda contexto, permissão e jornada conforme quem conversa.</p><div className="mt-4 flex flex-wrap gap-2">{audiences.map(x=><span key={x} className="rounded-full bg-slate-100 px-3 py-2 text-xs font-semibold">{x}</span>)}</div></article><article className="rounded-2xl border bg-white p-5"><h2 className="font-black">Jornadas configuradas</h2><div className="mt-3 space-y-2">{d.journeys.length?d.journeys.slice(0,10).map((j:any)=><div key={j.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div><b className="text-sm">{j.name}</b><p className="text-xs text-slate-500">{j.audience||j.trigger_type||'Automação Grupo Smart'}</p></div><span className={`rounded-full px-2 py-1 text-[11px] font-bold ${j.active?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{j.active?'Ativa':'Homologação'}</span></div>):<p className="text-sm text-slate-500">Jornadas serão exibidas após aplicação da migration homologada.</p>}</div></article></div>
   </div>
    <aside className="space-y-4"><article className="rounded-2xl bg-slate-950 p-5 text-white"><Bot className="text-sky-400"/><h2 className="mt-4 text-xl font-black">Smartito</h2><p className="mt-2 text-sm leading-6 text-slate-400">Agente próprio do Grupo Smart: conversa, guia, vende, atende e atua como concierge 24h, em qualquer idioma, respeitando perfil e permissões.</p><div className="mt-4 flex flex-wrap gap-2">{channels.map(x=><span key={x} className="rounded-full border border-white/10 bg-white/5 px-2 py-1 text-[11px] text-slate-300">{x}</span>)}</div><p className="mt-4 text-xs leading-5 text-slate-400">Acessa somente dados autorizados, faturas, clientes, colaboradores e arquivos; envia orientações e mantém contexto entre canais.</p></article><article className="rounded-2xl border border-sky-200 bg-sky-50 p-5"><QrCode className="text-sky-700"/><h2 className="mt-4 font-black">WhatsApp</h2><p className="mt-2 text-sm leading-6 text-slate-600">Fluxo padrão Full: conectar canal → QR Code quando o conector homologado exigir pareamento, ou API oficial → validar número → templates → consentimento → teste DEMO → ativação.</p><button type="button" disabled className="mt-4 w-full rounded-xl border border-sky-300 bg-white p-3 text-sm font-black text-sky-800">QR Code · aguardando canal homologado</button><p className="mt-2 text-[11px] leading-4 text-slate-500">Nenhum QR fictício é exibido. O código real só nasce da integração autorizada.</p></article><article className="rounded-2xl border bg-white p-5"><CalendarDays className="text-sky-600"/><h2 className="mt-4 font-black">Próximas atividades</h2><div className="mt-3 space-y-2">{d.activities.slice(0,8).map((a:any)=><div key={a.id} className="rounded-xl bg-slate-50 p-3"><b className="text-sm">{a.title}</b><p className="text-xs text-slate-500">{a.type} · {new Date(a.scheduled_at).toLocaleString('pt-BR')}</p></div>)}{!d.activities.length&&<p className="text-sm text-slate-500">Agenda pronta para reuniões online, visitas e follow-ups.</p>}</div></article></aside>
   </section>
  </div>
  {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/70 p-4"><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save.mutate({company_name:f.get('company_name'),contact_name:f.get('contact_name')||null,email:f.get('email')||null,phone:f.get('phone')||null,city:f.get('city')||null,state:f.get('state')||null,vertical:f.get('vertical'),source:f.get('source'),stage:'new',cross_sell_eligible:f.get('cross_sell_eligible')==='on'})}} className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-2xl font-black">Novo lead · DEMO</h2><p className="text-sm text-slate-500">Cadastro único Grupo Smart. A jornada gerada deve permanecer identificada como demonstração.</p></div><button type="button" onClick={()=>setOpen(false)}>✕</button></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><input required name="company_name" placeholder="Empresa / condomínio" className="rounded-xl border p-3 sm:col-span-2"/><input name="contact_name" placeholder="Contato" className="rounded-xl border p-3"/><input name="email" type="email" placeholder="E-mail" className="rounded-xl border p-3"/><input name="phone" placeholder="WhatsApp / telefone" className="rounded-xl border p-3"/><input name="city" placeholder="Cidade" className="rounded-xl border p-3"/><input name="state" placeholder="UF" className="rounded-xl border p-3"/><select name="vertical" className="rounded-xl border p-3"><option value="undetermined">A qualificar</option><option value="wizmart">wizMart</option><option value="smart_cafe">Smart Café</option><option value="both">Ambas</option></select><select name="source" className="rounded-xl border p-3"><option value="outbound">Outbound / lista</option><option value="manual">Manual</option><option value="inbound">Inbound / marketing</option><option value="field_sales">Executivo de campo</option><option value="referral">Indicação</option></select><label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" name="cross_sell_eligible"/> Potencial de cross-sell entre as duas soluções</label></div><button disabled={save.isPending} className="mt-6 w-full rounded-xl bg-sky-500 p-3 font-black">{save.isPending?'Salvando...':'Criar lead DEMO e iniciar jornada'}</button></form></div>}
 </main>
}
