import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Building2, HeartPulse, Pill, Stethoscope } from "lucide-react";

export const Route = createFileRoute("/grupo-evr/empresas")({ component: GrupoEvrEmpresas });

const companies = [
  { name: "Instituto EVR", icon: HeartPulse, to: "/grupo-evr/instituto", text: "Operação clínica, agenda, atendimento, programas, acompanhamento e relacionamento com pacientes." },
  { name: "Dr. Responde", icon: Stethoscope, to: "/grupo-evr/dr-responde", text: "Operação médica independente com CRM, agenda, jornadas, indicadores e faturamento próprios." },
  { name: "Ative-se Pharma", icon: Pill, to: "/grupo-evr/ativese-pharma", text: "Farmácia do grupo com pedidos, manipulação, PDV, estoque, compras, produção, qualidade e recorrência." },
] as const;

function GrupoEvrEmpresas(){return <main className="min-h-screen bg-[#f5f7f5] px-5 py-14 text-[#17221d]"><section className="mx-auto max-w-7xl"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#6d7f75]">Grupo EVR · Empresas</p><h1 className="mt-3 text-5xl font-semibold tracking-tight">Três empresas. Uma inteligência de gestão.</h1><p className="mt-5 text-lg leading-8 text-[#617067]">Cada empresa mantém sua operação, faturamento e indicadores próprios. O portal central permite acompanhar o grupo sem misturar responsabilidades ou dados.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{companies.map(({name,icon:Icon,to,text})=><Link key={name} to={to} className="group rounded-[2rem] border border-[#dbe2dc] bg-white p-7 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#edf2ee] text-[#173e31]"><Icon className="h-6 w-6"/></span><ArrowRight className="h-5 w-5 text-[#94a198] transition group-hover:translate-x-1"/></div><h2 className="mt-8 text-2xl font-semibold">{name}</h2><p className="mt-3 leading-7 text-[#637168]">{text}</p></Link>)}</div><div className="mt-8 rounded-3xl bg-[#12231d] p-7 text-white"><div className="flex items-start gap-4"><Building2 className="mt-1 h-6 w-6 text-[#d5bc75]"/><div><h2 className="text-2xl font-semibold">Visão consolidada sem confusão contábil</h2><p className="mt-3 max-w-4xl leading-7 text-white/70">Origem, destino, indicação, empresa faturadora e documento fiscal permanecem rastreáveis em cada jornada intercompany.</p></div></div></div></section></main>}
