import { createFileRoute, Link } from "@tanstack/react-router";
import { LifeBuoy, MessageCircle, Mail, Ticket, BookOpen, ArrowRight, Clock3, CheckCircle2, Workflow } from "lucide-react";
import { PublicHeader } from "@/components/marketing/PublicHeader";
import { PublicFooter } from "@/components/marketing/PublicFooter";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { openImpulsionito } from "@/lib/impulsionito-tracking";
const SUPPORT_EMAIL="sac@impulsionando.com.br";
export const Route=createFileRoute("/suporte")({head:()=>({meta:[{title:"Suporte e solicitações — Impulsionando"},{name:"description",content:"Tickets numerados, SLA, suporte e solicitações de melhoria organizadas pelo Impulsionito."}]}),component:SuportePage});
function talk(){openImpulsionito("suporte-central");}
function SuportePage(){return <div className="min-h-screen flex flex-col bg-background"><PublicHeader/><main className="flex-1"><section className="border-b border-border bg-gradient-to-br from-primary/5 via-background to-accent/5"><div className="mx-auto max-w-5xl px-4 py-16 text-center"><div className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/5 px-3 py-1 text-xs font-medium text-primary"><LifeBuoy className="h-3.5 w-3.5"/>Central de Gestão e Suporte</div><h1 className="mt-4 text-4xl sm:text-5xl font-bold">Suporte, ajustes e novos recursos em uma jornada rastreável</h1><p className="mt-4 text-muted-foreground max-w-3xl mx-auto">O cliente pode escrever, digitar por voz ou conversar com o Impulsionito. A solicitação é organizada, apresentada para validação e, após o aceite, registrada para atendimento ou encaminhada ao comitê Impulsionando quando envolver incremento de produto.</p><Button className="mt-6" onClick={talk}><MessageCircle className="mr-2 h-4 w-4"/>Abrir Impulsionito</Button></div></section>
<section className="mx-auto max-w-5xl px-4 py-12"><div className="grid md:grid-cols-3 gap-4"><Card className="p-6"><Ticket className="h-5 w-5 text-primary"/><h2 className="font-semibold mt-3">Ticket numerado</h2><p className="text-sm text-muted-foreground mt-2">Todo atendimento formal registra protocolo, abertura, horário, categoria, prioridade, histórico e status.</p></Card><Card className="p-6"><Clock3 className="h-5 w-5 text-primary"/><h2 className="font-semibold mt-3">SLA em dias úteis</h2><p className="text-sm text-muted-foreground mt-2">Emergências: resposta inicial em até 24 horas úteis. Solicitações de incremento de recurso: triagem e posicionamento em até 72 horas úteis.</p></Card><Card className="p-6"><Workflow className="h-5 w-5 text-primary"/><h2 className="font-semibold mt-3">Aceite antes do comitê</h2><p className="text-sm text-muted-foreground mt-2">O Impulsionito consolida a demanda. O cliente revisa e aceita. Só então a proposta de melhoria segue ao comitê para análise e implementação.</p></Card></div>
<div className="mt-10 rounded-2xl border p-7"><h2 className="text-2xl font-semibold">Fluxo oficial</h2><div className="grid md:grid-cols-5 gap-4 mt-6">{["Cliente descreve ou grava","Impulsionito organiza","Cliente valida e aceita","Ticket recebe SLA","Gestão ou comitê executa"].map((x,i)=><div key={x} className="rounded-xl bg-muted/40 p-4"><div className="text-xs text-primary font-bold">0{i+1}</div><div className="text-sm font-medium mt-2">{x}</div></div>)}</div></div>
<div className="grid sm:grid-cols-3 gap-4 mt-10"><Card className="p-6"><Ticket className="h-5 w-5 text-primary"/><h3 className="font-semibold mt-2">Abrir chamado</h3><p className="text-sm text-muted-foreground mt-1">Problema, emergência, configuração ou solicitação.</p><Button asChild variant="outline" size="sm" className="mt-4"><Link to="/abrir-ticket">Abrir ticket <ArrowRight className="ml-2 h-3.5 w-3.5"/></Link></Button></Card><Card className="p-6"><Mail className="h-5 w-5 text-primary"/><h3 className="font-semibold mt-2">E-mail</h3><p className="text-sm text-muted-foreground mt-1">{SUPPORT_EMAIL}</p><Button asChild variant="outline" size="sm" className="mt-4"><a href={`mailto:${SUPPORT_EMAIL}`}>Enviar e-mail</a></Button></Card><Card className="p-6"><BookOpen className="h-5 w-5 text-primary"/><h3 className="font-semibold mt-2">Central de Ajuda</h3><p className="text-sm text-muted-foreground mt-1">Guias e orientações operacionais.</p><Button asChild variant="outline" size="sm" className="mt-4"><Link to="/central-de-ajuda">Abrir base</Link></Button></Card></div>
<div className="mt-10 flex items-start gap-3 rounded-xl border border-primary/20 bg-primary/5 p-5"><CheckCircle2 className="h-5 w-5 text-primary shrink-0"/><p className="text-sm">Templates de e-mail, WhatsApp e jornadas configuráveis podem ser ajustados pelo cliente quando o permissionamento permitir ou solicitados ao time de gestão por esta mesma jornada.</p></div></section></main><PublicFooter/></div>}
