export {
  CORRELATION_ID_HEADER,
  IDEMPOTENCY_KEY_HEADER,
  StableErrorCode,
  ErrorCode,
  ErrorDetailSchema,
  ErrorBodySchema,
  ErrorEnvelopeSchema,
  PaginationMetaSchema,
  SuccessMetaSchema,
  successEnvelopeSchema,
  CursorPaginationQuerySchema,
  CursorPaginationMetaSchema,
  type ErrorDetail,
  type ErrorBody,
  type ErrorEnvelope,
  type PaginationMeta,
  type SuccessMeta,
  type SuccessEnvelope,
  type CursorPaginationQuery,
  type CursorPaginationMeta,
} from "./http-envelope";

export {
  SupportTicketType,
  SupportTicketPriority,
  SupportTicketStatus,
  SupportTicketRequesterSchema,
  SupportTicketCreateBodySchema,
  SupportTicketCreateDataSchema,
  SupportTicketCreateResponseSchema,
  SupportTicketListQuerySchema,
  SupportTicketSummarySchema,
  SupportTicketListResponseSchema,
  SupportTicketUpdateStatusBodySchema,
  SupportTicketUpdateStatusDataSchema,
  SupportTicketUpdateStatusResponseSchema,
  SupportTicketAuditAction,
  SupportTicketAuditV1Schema,
  type SupportTicketRequester,
  type SupportTicketCreateBody,
  type SupportTicketCreateData,
  type SupportTicketCreateResponse,
  type SupportTicketListQuery,
  type SupportTicketSummary,
  type SupportTicketListResponse,
  type SupportTicketUpdateStatusBody,
  type SupportTicketUpdateStatusData,
  type SupportTicketUpdateStatusResponse,
  type SupportTicketAuditV1,
} from "./support";

export {
  TENANT_CONFIG_SCHEMA_VERSION,
  TENANT_ENTITLEMENTS_SCHEMA_VERSION,
  TenantBrandingSchema,
  TenantConfigV1Schema,
  TenantEntitlementsV1Schema,
  TenantLocaleSchema,
  featureFlagKey,
  mergeModuleLimits,
  resolveEffectiveFlags,
  resolveEffectiveModules,
  resolveFlagValue,
  type FeatureFlagCatalogRow,
  type FeatureFlagOverrideRow,
  type TenantBranding,
  type TenantConfigV1,
  type TenantEntitlementsV1,
  type TenantLocale,
} from "./tenant";

export {
  DEFAULT_MAX_JOB_ATTEMPTS,
  DEFAULT_VISIBILITY_TIMEOUT_SECONDS,
  INVALID_ENVELOPE_DLQ_REASON,
  JOB_SCHEMA_VERSION,
  JobEnvelopeSchema,
  JobMessageSchema,
  REENGINEERING_JOBS_DLQ,
  REENGINEERING_JOBS_QUEUE,
  computeBackoffMs,
  dispositionForQueueMessage,
  idempotencyScopeKey,
  shouldMoveToDlq,
  shouldSkipDuplicate,
  type IdempotencyState,
  type JobEnvelope,
  type JobMessage,
  type QueueMessageDisposition,
} from "./job";

export {
  EVENT_SCHEMA_VERSION,
  EVENT_TYPE_CATALOG,
  EventActorSchema,
  EventActorTypeSchema,
  EventEnvelopeSchema,
  EventType,
  EventTypeSchema,
  OutboxRowInsertSchema,
  OutboxStatusSchema,
  REENGINEERING_EVENT_OUTBOX_TABLE,
  domainMutationToOutboxRow,
  outboxIdempotencyScopeKey,
  payloadSchemaRefFor,
  type DomainMutationToOutboxInput,
  type EventActor,
  type EventActorType,
  type EventEnvelope,
  type EventTypeCatalog,
  type EventTypeName,
  type OutboxRowInsert,
  type OutboxStatus,
} from "./event";

/* --- Phase 5D webhook boundary (minimal export block) --- */
export {
  DEFAULT_WEBHOOK_REPLAY_WINDOW_SECONDS,
  WEBHOOK_IDEMPOTENCY_HEADER,
  WEBHOOK_PROVIDERS,
  WEBHOOK_SCHEMA_VERSION,
  WEBHOOK_SECRET_ENV_NAMES,
  WEBHOOK_SIGNATURE_HEADER,
  WEBHOOK_TIMESTAMP_HEADER,
  WebhookEnvelopeSchema,
  buildWebhookSignedPayload,
  computeWebhookHmacHex,
  isKnownWebhookProvider,
  isTimestampWithinSkew,
  normalizeWebhookSignatureHeader,
  redactWebhookPayload,
  redactWebhookPayloadRecord,
  resolveWebhookSecretEnvName,
  sha256Hex,
  shouldRejectReplay,
  timingSafeEqualString,
  verifyWebhookIngress,
  webhookIdempotencyScopeKey,
  type WebhookEnvelope,
  type WebhookProvider,
  type WebhookVerifyFailureReason,
  type WebhookVerifyResult,
} from "./webhook";
/* --- end Phase 5D --- */

/* --- Phase 5E communication platform (minimal export block) --- */
export {
  COMMUNICATION_DISPATCH_JOB_TYPE,
  COMMUNICATION_ENV_NAMES,
  COMMUNICATION_SCHEMA_VERSION,
  CommunicationChannel,
  CommunicationChannelSchema,
  CommunicationConsentSchema,
  CommunicationCooldownSchema,
  CommunicationIntentSchema,
  CommunicationRecipientSchema,
  CommunicationTemplateRefSchema,
  DeliveryStatus,
  DeliveryStatusSchema,
  REENGINEERING_COMMUNICATION_DELIVERY_TABLE,
  communicationCooldownScopeKey,
  communicationDedupScopeKey,
  evaluateCommunicationPolicy,
  isCooldownActive,
  isRecipientAllowlisted,
  mapProviderFailure,
  parseRecipientAllowlist,
  runCommunicationDispatch,
  shouldSkipDedup,
  type CommunicationAdapter,
  type CommunicationAdapterSendInput,
  type CommunicationAdapterSendResult,
  type CommunicationChannelName,
  type CommunicationConsent,
  type CommunicationCooldown,
  type CommunicationDispatchOutcome,
  type CommunicationIntent,
  type CommunicationPolicyDecision,
  type CommunicationPolicyReason,
  type CommunicationRecipient,
  type CommunicationTemplateRef,
  type DeliveryStatusName,
  type EmailCommunicationAdapter,
  type ProviderFailureMapping,
  type WhatsAppCommunicationAdapter,
} from "./communication";
/* --- end Phase 5E --- */

/* --- Phase 5F CRM invitation journey (minimal export block) --- */
export {
  CreateInviteBodySchema,
  InviteV1Schema,
  InviteStatusSchema,
  JOURNEY_DEFAULT_REMINDER_KEYS,
  JOURNEY_ENV_NAMES,
  JOURNEY_INCOMPATIBLE_ON_FIRST_LOGIN,
  JOURNEY_SCHEMA_VERSION,
  JourneyStateV1Schema,
  JourneyStatusSchema,
  JourneySupportContextSchema,
  REENGINEERING_CRM_INVITE_TABLE,
  REENGINEERING_CRM_JOURNEY_TABLE,
  RecordFirstLoginBodySchema,
  RecordInviteClickBodySchema,
  applyInviteClick,
  applyJourneyTransition,
  cancelIncompatibleReminders,
  evaluateInviteAction,
  isInviteExpired,
  isInviteRevoked,
  isJourneyRecipientAllowlisted,
  parseJourneyRecipientAllowlist,
  type CancelRemindersInput,
  type CancelRemindersResult,
  type CreateInviteBody,
  type InviteActionDecision,
  type InviteDenyReason,
  type InviteStatus,
  type InviteV1,
  type JourneyReminderKey,
  type JourneyStateV1,
  type JourneyStatus,
  type JourneySupportContext,
  type JourneyTransitionEvent,
  type RecordFirstLoginBody,
  type RecordInviteClickBody,
} from "./journey";
/* --- end Phase 5F --- */

/* --- Phase 5G operational readiness (minimal export block) --- */
export {
  INTEGRATION_REGISTRY_SEED,
  OPS_QUEUES,
  OPS_SCHEMA_VERSION,
  IdempotencyCountsSchema,
  IntegrationEnvironmentSchema,
  IntegrationRegistryEnvelopeSchema,
  IntegrationRegistryRowSchema,
  IntegrationStatusSchema,
  QueueMetricRowSchema,
  QueueMetricsEnvelopeSchema,
  assertNoSecretFields,
  buildIntegrationRegistryEnvelope,
  computeFailureRate,
  type IdempotencyCounts,
  type IntegrationEnvironment,
  type IntegrationRegistryEnvelope,
  type IntegrationRegistryRow,
  type IntegrationStatus,
  type QueueMetricRow,
  type QueueMetricsEnvelope,
} from "./ops";
/* --- end Phase 5G --- */

/* --- Phase 6A–6F governed AI gateway + tool registry + pilot + telemetry + tenant agent --- */
export {
  AI_DEFAULT_PROMPT_VERSION,
  AI_DEFAULT_TENANT_AGENT_ALLOWLIST,
  AI_DEFAULT_TENANT_AGENT_ID,
  AI_DETERMINISTIC_MODEL_ID,
  AI_ENV_NAMES,
  AI_EVAL_FIXTURES,
  AI_SCHEMA_VERSION,
  DEFAULT_AI_REDACTION_POLICY,
  AiBudgetEnvelopeSchema,
  AiCapabilitiesEnvelopeSchema,
  AiCapabilityIdSchema,
  AiCapabilityRowSchema,
  AiChatContextAssemblySchema,
  AiChatRefuseCodeSchema,
  AiChatRefuseSchema,
  AiChatRequestBodySchema,
  AiEvalCaseSchema,
  AiEvalExpectedOutcomeSchema,
  AiKillSwitchSchema,
  AiMetricsEnvelopeSchema,
  AiPilotIntentSchema,
  AiPilotReplySchema,
  AiPilotSourceSchema,
  AiPilotToolPlanSchema,
  AiPolicyEnvelopeSchema,
  AiRedactionPolicySchema,
  AiRiskClass,
  AiTelemetryEventSchema,
  AiTelemetryOutcomeSchema,
  AiTenantAgentConfigSchema,
  AiToolIdSchema,
  AiToolJourneyGetInputSchema,
  AiToolMetaSchema,
  AiToolSupportGetInputSchema,
  AiToolSupportListInputSchema,
  AiToolTenantActiveContextInputSchema,
  AiToolTenantResolveHostInputSchema,
  AiToolsEnvelopeSchema,
  buildAiMetricsEnvelope,
  buildDefaultCapabilities,
  buildSeededTenantAgentConfig,
  defaultAiToolAllowPolicy,
  isToolAllowed,
  isTruthyEnv,
  parseNonNegativeIntEnv,
  parsePositiveIntEnv,
  parseTenantAgentAllowlist,
  percentileSorted,
  redactAiPayload,
  routePilotIntent,
  synthesizePilotAnswer,
  type AiBudgetEnvelope,
  type AiCapabilitiesEnvelope,
  type AiCapabilityId,
  type AiCapabilityRow,
  type AiChatContextAssembly,
  type AiChatRefuse,
  type AiChatRefuseCode,
  type AiChatRequestBody,
  type AiEnvName,
  type AiEvalCase,
  type AiEvalExpectedOutcome,
  type AiKillSwitch,
  type AiMetricsEnvelope,
  type AiPilotIntent,
  type AiPilotReply,
  type AiPilotSource,
  type AiPilotToolPlan,
  type AiPolicyEnvelope,
  type AiRedactionPolicy,
  type AiRiskClassName,
  type AiTelemetryEvent,
  type AiTelemetryOutcome,
  type AiTenantAgentConfig,
  type AiToolAllowPolicy,
  type AiToolId,
  type AiToolJourneyGetInput,
  type AiToolMeta,
  type AiToolSupportGetInput,
  type AiToolSupportListInput,
  type AiToolTenantActiveContextInput,
  type AiToolTenantResolveHostInput,
  type AiToolsEnvelope,
} from "./ai";
/* --- end Phase 6A–6F --- */

/* --- Phase 6E gated effects / approval (minimal export block) --- */
export {
  AI_EFFECT_ENV_NAMES,
  AI_EFFECT_EXECUTE_JOB_TYPE,
  AiApprovalRequiredToolExecRequestSchema,
  AiEffectApprovalCreateBodySchema,
  AiEffectApprovalDecisionBodySchema,
  AiEffectApprovalRequestSchema,
  AiEffectApprovalStatusSchema,
  AiEffectDecisionKindSchema,
  AiEffectDecisionRecordSchema,
  AiEffectExecuteJobPayloadSchema,
  AiEffectExecuteReasonSchema,
  AiEffectExecutionRecordSchema,
  AiEffectGatedToolIdSchema,
  aiEffectIdempotencyScopeKey,
  assertApprovalRequiredRisk,
  canTransitionApprovalStatus,
  isAiEffectsEnqueueEnabled,
  isApprovalExpired,
  isGatedEffectToolId,
  parseApprovalTtlSeconds,
  type AiApprovalRequiredToolExecRequest,
  type AiEffectApprovalCreateBody,
  type AiEffectApprovalDecisionBody,
  type AiEffectApprovalRequest,
  type AiEffectApprovalStatus,
  type AiEffectDecisionKind,
  type AiEffectDecisionRecord,
  type AiEffectEnvName,
  type AiEffectExecuteJobPayload,
  type AiEffectExecuteReason,
  type AiEffectExecutionRecord,
  type AiEffectGatedToolId,
} from "./ai-effects";
/* --- end Phase 6E --- */
