import { createFileRoute } from "@tanstack/react-router";
import { timingSafeEqual } from "crypto";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { reconcileColorsSale } from "@/lib/colors-reconcile.server";

function eq(a:string,b:string){try{const aa=Buffer.from(a),bb=Buffer.from(b);return aa.length===bb.length&&timingSafeEqual(aa,bb)}catch{return false}}
async function parse(request:Request){const type=request.headers.get("content-type")??"";if(type.includes("application/json"))return await request.json();const text=await request.text();const p=new URLSearchParams(text);const out:any={};for(const[k,v]of p.entries()){const parts=k.replace(/\]/g,"").split("[");let cur=out;for(let i=0;i<parts.length;i++){const part=parts[i];if(i===parts.length-1)cur[part]=v;else cur=cur[part]??=(/^\d+$/.test(parts[i+1])?[]:{});} }return out;}
const statusFor=(code:number)=>code===2||code===6?"approved":code===1||code===98||code===99?"pending":code===3?"cancelled":code===4?"refunded":code===5?"rejected":code===7?"abandoned":code===9?"refund_requested":"pending";
const eventFor=(code:number)=>code===1?"PAYMENT_PENDING":code===2?"PAYMENT_APPROVED":code===3?"ORDER_CANCELED":code===4?"ORDER_REFUNDED":code===5?"PAYMENT_FAILED":code===6?"ORDER_COMPLETED":code===7?"CHECKOUT_ABANDONED":code===9?"REFUND_REQUESTED":code===120?"DELIVERY_UPDATED":code>=101&&code<=106?"SUBSCRIPTION_UPDATED":"ORDER_UPDATED";
const cents=(v:any)=>{const n=Number(String(v??0).replace(",","."));return Number.isFinite(n)?Math.round(n*100):undefined};
export const Route=createFileRoute("/api/public/webhooks/monetizze-colors")({server:{handlers:{GET:async()=>Response.json({ok:true,provider:"monetizze",idempotency:"payload.id"}),POST:async({request})=>{let p:any;try{p=await parse(request)}catch{return new Response("invalid payload",{status:400})}const expected=process.env.COLORS_MONETIZZE_UNIQUE_KEY??"";if(!expected)return new Response("integration key not configured",{status:424});if(!p?.chave_unica||!eq(expected,String(p.chave_unica)))return new Response("invalid integration key",{status:401});const eventId=String(p.id??"");if(!eventId)return new Response("missing webhook id",{status:400});const code=Number(p.postback_evento??p.tipoEvento?.codigo??0);const saleId=String(p.codigo_venda??p.venda?.codigo??"");const eventType=eventFor(code);
const{data:dup}=await(supabaseAdmin as any).from("colors_event_bus").select("id").eq("event_id",`monetizze:${eventId}`).maybeSingle();if(dup?.id)return Response.json({ok:true,duplicate:true});
if(code===7){await(supabaseAdmin as any).from("colors_event_bus").insert({event_id:`monetizze:${eventId}`,event_type:"CHECKOUT_ABANDONED",aggregate_type:"checkout",aggregate_id:saleId||eventId,payload:{provider:"monetizze",url_recuperacao:p.url_recuperacao??null,sale_id:saleId,buyer:p.comprador??null,utm:{src:p.venda?.src??null,utm_source:p.venda?.utm_source??null,utm_medium:p.venda?.utm_medium??null,utm_campaign:p.venda?.utm_campaign??null,utm_content:p.venda?.utm_content??null,utm_term:p.venda?.utm_term??null}}});return Response.json({ok:true,event:eventType});}
if(code>=101&&code<=106){await(supabaseAdmin as any).from("colors_event_bus").insert({event_id:`monetizze:${eventId}`,event_type:"SUBSCRIPTION_UPDATED",aggregate_type:"subscription",aggregate_id:String(p.assinatura?.codigo??p.recuperacao_parcelada?.codigo??eventId),payload:{provider:"monetizze",event_code:code,subscription:p.assinatura??null,installment_recovery:p.recuperacao_parcelada??null,sale:p.venda??null,product:p.produto??null,buyer:p.comprador??null}});return Response.json({ok:true,event:"SUBSCRIPTION_UPDATED"});}
if(code===120){const result=saleId?await reconcileColorsSale(supabaseAdmin as any,{platform:"monetizze",external_sale_id:saleId,external_order_id:saleId,external_status:String(p.rastreio?.status) === "6"?"delivered":"shipped",customer_name:p.comprador?.nome,product_name:p.produto?.nome,source:"webhook",raw:p}):null;await(supabaseAdmin as any).from("colors_event_bus").upsert({event_id:`monetizze:${eventId}`,event_type:String(p.rastreio?.status)==="6"?"ORDER_DELIVERED":"DELIVERY_UPDATED",aggregate_type:"order",aggregate_id:result?.order_id??saleId??eventId,payload:{provider:"monetizze",tracking_code:p.rastreio?.codigo??null,tracking_status:p.rastreio?.descricao??null,carrier:p.venda?.transportadora?.nome??null,sale_id:saleId}},{onConflict:"event_id",ignoreDuplicates:true});return Response.json({ok:true,event:"DELIVERY_UPDATED"});}
if(!saleId){await(supabaseAdmin as any).from("colors_event_bus").insert({event_id:`monetizze:${eventId}`,event_type:eventType,aggregate_type:"webhook",aggregate_id:eventId,payload:{provider:"monetizze",event_code:code}});return Response.json({ok:true,event:eventType});}
const result=await reconcileColorsSale(supabaseAdmin as any,{platform:"monetizze",external_sale_id:saleId,external_order_id:saleId,external_status:statusFor(code),customer_name:p.comprador?.nome,customer_email:p.comprador?.email,customer_whatsapp:p.comprador?.telefone,customer_cpf:p.comprador?.cnpj_cpf,product_slug:p.codigo_produto?String(p.codigo_produto):undefined,product_name:p.produto?.nome,quantity:Number(p.venda?.quantidade??1),total_price_cents:cents(p.venda?.valor),coupon:p.codigo_cupom?String(p.codigo_cupom):undefined,affiliate_code:Array.isArray(p.comissoes)?p.comissoes.find((c:any)=>String(c.tipo??c.tipo_comissao??"").toLowerCase().includes("afili"))?.codigo_afiliado:undefined,approved_at:p.venda?.dataFinalizada,raw:p,source:"webhook"});await(supabaseAdmin as any).from("colors_event_bus").upsert({event_id:`monetizze:${eventId}`,event_type:eventType,aggregate_type:"order",aggregate_id:result.order_id??saleId,payload:{provider:"monetizze",event_code:code,sale_id:saleId,order_id:result.order_id,opportunity_id:result.opportunity_id,url_recuperacao:p.url_recuperacao??null,pix_url:p.pix_url??null}},{onConflict:"event_id",ignoreDuplicates:true});return Response.json({ok:true,event:eventType,...result});}}}});
