import { createFileRoute } from "@tanstack/react-router";
import { timingSafeEqual } from "crypto";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { reconcileColorsSale } from "@/lib/colors-reconcile.server";
function eq(a:string,b:string){try{const aa=Buffer.from(a),bb=Buffer.from(b);return aa.length===bb.length&&timingSafeEqual(aa,bb)}catch{return false}}
const STATUS:Record<number,string>={0:"pending",1:"pending",2:"approved",3:"in_process",4:"in_process",5:"rejected",6:"cancelled",7:"refunded",8:"pending",9:"chargeback",10:"approved",11:"rejected",12:"abandoned",13:"cancelled",16:"in_process"};
const EVENT:Record<number,string>={1:"PAYMENT_PENDING",2:"PAYMENT_APPROVED",3:"PAYMENT_PENDING",4:"PAYMENT_PENDING",5:"PAYMENT_FAILED",6:"ORDER_CANCELED",7:"ORDER_REFUNDED",8:"PAYMENT_PENDING",9:"ORDER_CHARGEBACK",10:"ORDER_COMPLETED",11:"CHECKOUT_ERROR",12:"CHECKOUT_ABANDONED",13:"PAYMENT_EXPIRED",16:"PAYMENT_PENDING"};
const cents=(v:any)=>{const n=Number(v);return Number.isFinite(n)?Math.round(n*100):undefined};
async function persistCommission(result:any,p:any,saleId:string,code:number){if(!result?.affiliate_id)return;const rows=(Array.isArray(p.commission)?p.commission:[]).filter((c:any)=>Number(c.affiliation_type_enum)===5);for(const c of rows){const amount=cents(c.commission_value??c.commission_amount??c.amount??c.value);const commissionType=String(c.affiliation_type??c.affiliation_type_enum??"affiliate")||"affiliate";const{error}=await(supabaseAdmin as any).from("colors_affiliate_commissions").upsert({affiliate_id:result.affiliate_id,order_id:result.order_id??null,platform:"perfectpay",external_sale_id:saleId,commission_type:commissionType,amount_cents:amount??null,currency:"BRL",status:[2,10].includes(code)?"approved":[6,7,9].includes(code)?"reversed":"reported",raw:c,occurred_at:p.date_approved??p.date_created??null},{onConflict:"platform,external_sale_id,affiliate_id,commission_type"});if(error)console.error("[perfectpay-colors] commission sync failed",error.message);}}
export const Route=createFileRoute("/api/public/webhooks/perfectpay-colors")({server:{handlers:{GET:async()=>Response.json({ok:true,provider:"perfectpay"}),POST:async({request})=>{let p:any;try{p=await request.json()}catch{return new Response("invalid json",{status:400})}const expected=process.env.COLORS_PERFECTPAY_WEBHOOK_TOKEN??"";if(!expected)return new Response("webhook token not configured",{status:424});if(!p?.token||!eq(expected,String(p.token)))return new Response("invalid token",{status:401});const saleId=String(p.code??"");if(!saleId)return new Response("missing sale code",{status:400});const code=Number(p.sale_status_enum??0),eventType=EVENT[code]??"ORDER_UPDATED";const eventId=`perfectpay:${saleId}:${code}:${String(p.date_created??p.date_approved??"")}`;const{data:dup}=await(supabaseAdmin as any).from("colors_event_bus").select("id").eq("event_id",eventId).maybeSingle();if(dup?.id)return Response.json({ok:true,duplicate:true});
if(code===12||code===11){await(supabaseAdmin as any).from("colors_event_bus").insert({event_id:eventId,event_type:eventType,aggregate_type:"checkout",aggregate_id:saleId,payload:{provider:"perfectpay",sale_code:saleId,status_detail:p.sale_status_detail??null,customer:p.customer??null,product:p.product??null,plan:p.plan??null,utm:p.metadata??{},affiliate:Array.isArray(p.commission)?p.commission.filter((c:any)=>Number(c.affiliation_type_enum)===5):[]}});return Response.json({ok:true,event:eventType});}
const affiliate=Array.isArray(p.commission)?p.commission.find((c:any)=>Number(c.affiliation_type_enum)===5):null;const phone=[p.customer?.phone_area_code,p.customer?.phone_number].filter(Boolean).join("");const result=await reconcileColorsSale(supabaseAdmin as any,{platform:"perfectpay",external_sale_id:saleId,external_order_id:saleId,external_status:STATUS[code]??"pending",customer_name:p.customer?.full_name,customer_email:p.customer?.email,customer_whatsapp:phone||undefined,customer_cpf:p.customer?.identification_number,product_slug:p.product?.external_reference??p.product?.code,product_name:p.product?.name,quantity:Number(p.quantity??p.plan?.quantity??1),kit_size:Number(p.plan?.quantity??1),total_price_cents:cents(p.sale_amount),coupon:p.coupon_code??undefined,affiliate_code:affiliate?.affiliation_code,affiliate_name:affiliate?.name,approved_at:p.date_approved??undefined,raw:p,source:"webhook"});await persistCommission(result,p,saleId,code);await(supabaseAdmin as any).from("colors_event_bus").upsert({event_id:eventId,event_type:eventType,aggregate_type:"order",aggregate_id:result.order_id??saleId,payload:{provider:"perfectpay",sale_code:saleId,sale_status_enum:code,status_detail:p.sale_status_detail??null,payment_type_enum:p.payment_type_enum??null,installments:p.installments??null,utm:p.metadata??{},affiliate_code:affiliate?.affiliation_code??null,order_id:result.order_id,opportunity_id:result.opportunity_id}},{onConflict:"event_id",ignoreDuplicates:true});return Response.json({ok:true,event:eventType,...result});}}}});
