import {
  LayoutDashboard, Building2, Tags, MapPin, Layers, Users, KeyRound,
  SlidersHorizontal, FileSearch, Boxes, KanbanSquare, UserPlus, GitBranch, CalendarClock,
  Calendar, Users2, Wrench, Clock, UsersRound,
  Wallet, ArrowLeftRight, FolderTree, CreditCard, Percent,
  Package, Truck, ArrowDownUp,
  ShoppingCart, Receipt, Plus, Wallet as WalletIcon,
  Contact, BarChart3, ShieldCheck, Inbox, GraduationCap, Stethoscope, Sparkles, Crown,
  Handshake, Link2, Briefcase, BadgeDollarSign, TrendingUp, Banknote, Copy,
  Home, Search as SearchIcon, Zap, Bot, MessageSquare, QrCode,
  History as HistoryIcon, Headphones, UserRound, Megaphone,
  Calculator, Activity, RefreshCw, BookOpen,
  Beer, Store, Send, Ticket, Utensils,
  Settings as SettingsIcon, Globe, FlaskConical, Server, Flag, FileCode,
  Rocket, Gauge, LineChart, ClipboardList, Workflow, ScrollText, Filter,
} from "lucide-react";

export type NavAudience = "core" | "white-label" | "empresa" | "consumidor";

export interface NavItem {
  to?: string;
  label: string;
  icon: React.ComponentType<{ className?: string }>;
  superOnly?: boolean;
  /** Código de permissão necessário. Se ausente, o item é visível por padrão. */
  perm?: string;
  /** Renderiza um contador dinâmico ao lado do label. */
  badge?: "pendingPix";
  /** Audiências para as quais este item é relevante. Se ausente = todas. */
  audiences?: NavAudience[];
  /** Tiers de plano que liberam este item. Se ausente = todos. Staff sempre vê. */
  requiresPlanTier?: Array<"essencial" | "profissional" | "completo">;
  /** Submenu (até 1 nível). Quando presente, o item vira um agrupador colapsável. */
  children?: NavItem[];
}


export interface NavGroup {
  label: string;
  items: NavItem[];
  defaultOpen?: boolean;
  /** Audiências para as quais este grupo é relevante. Se ausente = todas. */
  audiences?: NavAudience[];
}

export const TOP_ITEMS: NavItem[] = [
  { to: "/dashboard", label: "Dashboard", icon: LayoutDashboard, perm: "dashboard.read" },
  { to: "/dashboards/core", label: "Dashboard Core", icon: LayoutDashboard, audiences: ["core"] },
  { to: "/dashboards/white-label", label: "Dashboard WL", icon: LayoutDashboard, audiences: ["white-label", "core"] },
  { to: "/dashboards/empresa", label: "Dashboard Empresa", icon: LayoutDashboard, audiences: ["empresa"] },
  { to: "/dashboards/operacao", label: "Operação Core", icon: LayoutDashboard, audiences: ["core", "empresa"] },
  { to: "/cockpits", label: "Cockpits", icon: TrendingUp, superOnly: true },
  { to: "/notifications", label: "Notificações", icon: Inbox },
  { to: "/onboarding", label: "Começar / Melhorar", icon: Sparkles },
  { to: "/saiba-mais", label: "Saiba Mais", icon: BookOpen },
];

export const NAV_GROUPS: NavGroup[] = [
  {
    label: "Minha Área",
    audiences: ["consumidor"],
    defaultOpen: true,
    items: [
      { to: "/dashboards/consumidor", label: "Início", icon: Home, audiences: ["consumidor"] },
      { to: "/clube", label: "Clube — Benefícios", icon: Sparkles, audiences: ["consumidor"] },
      { to: "/clube/notificacoes", label: "Notificações do Clube", icon: Inbox, audiences: ["consumidor"] },
      { to: "/minha-assinatura", label: "Minha Assinatura", icon: CreditCard, audiences: ["consumidor"] },
    ],
  },
  {
    label: "Descobrir",
    audiences: ["consumidor"],
    defaultOpen: true,
    items: [
      { to: "/vitrine", label: "Restaurantes & Parceiros", icon: SearchIcon, audiences: ["consumidor"] },
      { to: "/saiba-mais", label: "Conheça os planos", icon: BookOpen, audiences: ["consumidor"] },
    ],
  },
  {
    label: "Configurações",
    audiences: ["consumidor"],
    items: [
      { to: "/privacy", label: "Privacidade & Notificações", icon: ShieldCheck, audiences: ["consumidor"] },
    ],
  },
  {
    label: "Microcervejaria",
    audiences: ["core", "white-label", "empresa"],
    defaultOpen: true,
    items: [
      { to: "/cervejaria", label: "Painel da Cervejaria", icon: Beer },
      { to: "/cervejaria/pdvs", label: "PDVs Parceiros", icon: Store },
      { to: "/cervejaria/catalogo", label: "Catálogo & Campanhas", icon: Megaphone },
      { to: "/cervejaria/relacionamento", label: "Relacionamento", icon: Users },
      { to: "/cervejaria/retorno", label: "Retorno por PDV/Cupom", icon: BarChart3 },
    ],
  },

  {
    label: "Marketplace B2B",
    audiences: ["core", "white-label", "empresa"],
    items: [
      { to: "/core/marketplace", label: "Visão geral", icon: TrendingUp, superOnly: true },
      { to: "/core/marketplace/fornecedores", label: "Fornecedores", icon: Store, superOnly: true },
      { to: "/core/marketplace/compradores", label: "Compradores", icon: Users2, superOnly: true },
      { to: "/core/marketplace/pedidos", label: "Pedidos", icon: Receipt, superOnly: true },
      { to: "/core/marketplace/financeiro", label: "Financeiro B2B", icon: Banknote, superOnly: true },
      { to: "/cervejaria/marketplace", label: "Meu Marketplace (Cervejaria)", icon: Beer },
      { to: "/bar/marketplace", label: "Comprar do Marketplace (Bar)", icon: ShoppingCart },
    ],
  },

  {
    label: "Ecossistema",
    audiences: ["core"],
    items: [
      { to: "/core/ecossistema", label: "Painel do Ecossistema", icon: Sparkles, superOnly: true },
      { to: "/ecossistema", label: "Vitrine pública", icon: Store },
    ],
  },

  {
    label: "Captar",
    audiences: ["core", "white-label", "empresa"],
    items: [
      { to: "/commercial/cockpit", label: "Cockpit Comercial", icon: TrendingUp, perm: "crm.opportunity.read" },
      { to: "/crm/board", label: "Kanban de oportunidades", icon: KanbanSquare, perm: "crm.opportunity.read" },
      { to: "/crm/leads", label: "Leads", icon: UserPlus, perm: "crm.lead.read" },
      { to: "/crm/pipelines", label: "Funis", icon: GitBranch, perm: "crm.pipeline.read" },
      { to: "/crm/activities", label: "Atividades", icon: CalendarClock, perm: "crm.activity.read" },
      { to: "/marketing/leads", label: "Leads do site", icon: Inbox, superOnly: true },
      { to: "/marketing/cockpit", label: "Cockpit de Marketing", icon: Megaphone, superOnly: true },
      { to: "/talents", label: "Banco de Talentos", icon: GraduationCap, superOnly: true },
    ],
  },
  {
    label: "Relacionar",
    items: [
      { to: "/customers", label: "Clientes", icon: Contact, perm: "customer.read" },
      {
        label: "Agenda",
        icon: Calendar,
        perm: "agenda.appointment.read",
        children: [
          { to: "/agenda", label: "Agenda — hoje", icon: Calendar, perm: "agenda.appointment.read" },
          { to: "/agenda/appointments", label: "Agendamentos", icon: CalendarClock, perm: "agenda.appointment.read" },
          { to: "/agenda/professionals", label: "Profissionais", icon: Users2, perm: "agenda.professional.read" },
          { to: "/agenda/services", label: "Serviços", icon: Wrench, perm: "agenda.service.read" },
          { to: "/agenda/schedules", label: "Horários", icon: Clock, perm: "agenda.schedule.write" },
          { to: "/agenda/waitlist", label: "Fila de espera", icon: UsersRound, perm: "agenda.waitlist.write" },
          { to: "/agenda/gestor", label: "Agenda — gestor", icon: CalendarClock, perm: "agenda.metrics.read" },
          { to: "/agenda/profissional", label: "Pega-Horário", icon: Calendar, perm: "agenda.slot.claim" },
          { to: "/agenda/cliente", label: "Meus agendamentos", icon: Calendar },
        ],
      },
      { to: "/ehr", label: "Prontuário Eletrônico", icon: Stethoscope, perm: "ehr.record.read" },
      { to: "/imobiliaria/interessados", label: "Interessados (Imob.)", icon: Users2, perm: "realestate.interest.read" },
      { to: "/clube", label: "Minha área Clube", icon: Sparkles },
      { to: "/consumer/unified", label: "Clube — Membros", icon: UserRound, perm: "users.read" },
    ],
  },
  {
    label: "Operar",
    audiences: ["core", "white-label", "empresa"],
    items: [
      { to: "/operations/cockpit", label: "Cockpit de Operações", icon: TrendingUp, perm: "sales.order.read" },
      {
        label: "Vendas",
        icon: ShoppingCart,
        perm: "sales.order.read",
        children: [
          { to: "/sales", label: "Vendas — visão geral", icon: ShoppingCart, perm: "sales.order.read" },
          { to: "/sales/new", label: "Nova venda (PDV)", icon: Plus, perm: "sales.order.write" },
          { to: "/sales/orders", label: "Pedidos", icon: Receipt, perm: "sales.order.read" },
          { to: "/sales/cash", label: "Fechamento de caixa", icon: WalletIcon, perm: "sales.cashsession.read" },
        ],
      },
      {
        label: "Estoque",
        icon: Package,
        perm: "inventory.product.read",
        children: [
          { to: "/inventory", label: "Estoque — visão geral", icon: Package, perm: "inventory.product.read" },
          { to: "/inventory/products", label: "Produtos", icon: Boxes, perm: "inventory.product.read" },
          { to: "/inventory/movements", label: "Movimentações", icon: ArrowDownUp, perm: "inventory.movement.read" },
          { to: "/inventory/categories", label: "Categorias", icon: FolderTree, perm: "inventory.category.read" },
          { to: "/inventory/suppliers", label: "Fornecedores", icon: Truck, perm: "inventory.supplier.read" },
        ],
      },
      {
        label: "Imobiliária",
        icon: Home,
        children: [
          { to: "/imobiliaria/vitrine", label: "Vitrine", icon: Home },
          { to: "/realestate/cockpit", label: "Cockpit", icon: Home },
          { to: "/imobiliaria/imoveis", label: "Imóveis", icon: Home },
          { to: "/imobiliaria/intencoes", label: "Buscas salvas", icon: SearchIcon },
          { to: "/imobiliaria/matches", label: "Matches", icon: Zap },
          { to: "/imobiliaria/campanhas", label: "Campanhas & Disparo", icon: Send, perm: "realestate.property.write" },
          { to: "/imobiliaria/parceiros", label: "Corretores parceiros", icon: Handshake, perm: "realestate.property.write" },
          { to: "/imobiliaria/modulos", label: "Módulos do nicho", icon: Boxes },
        ],
      },
    ],
  },
  {
    label: "Cobrar",
    audiences: ["core", "white-label", "empresa"],
    items: [
      { to: "/finance/cockpit", label: "Cockpit Financeiro", icon: TrendingUp, perm: "finance.transaction.read" },
      {
        label: "Financeiro",
        icon: Wallet,
        perm: "finance.transaction.read",
        children: [
          { to: "/finance", label: "Visão geral", icon: Wallet, perm: "finance.transaction.read" },
          { to: "/finance/transactions", label: "Lançamentos", icon: ArrowLeftRight, perm: "finance.transaction.read" },
          { to: "/finance/accounts", label: "Contas", icon: Wallet, perm: "finance.account.write" },
          { to: "/finance/categories", label: "Categorias", icon: FolderTree, perm: "finance.category.write" },
          { to: "/finance/methods", label: "Métodos de pagamento", icon: CreditCard, perm: "finance.method.write" },
          { to: "/finance/integracoes", label: "Integrações de pagamento", icon: Wallet, perm: "finance.method.write", badge: "pendingPix" },
          { to: "/finance/commissions", label: "Comissões", icon: Percent, perm: "finance.commission.read" },
        ],
      },
      { to: "/minha-assinatura", label: "Minha Assinatura", icon: CreditCard },
      {
        label: "Afiliados",
        icon: Handshake,
        perm: "aff.module.read",
        requiresPlanTier: ["profissional", "completo"],
        children: [
          { to: "/affiliates", label: "Dashboard", icon: LayoutDashboard, perm: "aff.module.read" },
          { to: "/affiliates/sales", label: "Vendas", icon: ShoppingCart, perm: "aff.module.read" },
          { to: "/affiliates/commissions", label: "Comissões", icon: Percent, perm: "aff.module.read" },
          { to: "/affiliates/payouts", label: "Saques & Repasses", icon: Banknote, perm: "aff.module.read" },
          { to: "/affiliates/wallet", label: "Carteira & Alertas", icon: Wallet, perm: "aff.module.read" },
          { to: "/affiliates/links", label: "Links / Cupons / QR", icon: Link2, perm: "aff.module.read" },
          { to: "/affiliates/affiliates", label: "Afiliados (cadastro)", icon: Handshake, perm: "aff.module.read" },
          { to: "/affiliates/coproducers", label: "Coprodutores", icon: Users2, perm: "aff.module.read" },
          { to: "/affiliates/managers", label: "Gerentes", icon: Briefcase, perm: "aff.module.read" },
          { to: "/affiliates/products", label: "Produtos", icon: Boxes, perm: "aff.module.read" },
          { to: "/affiliates/offers", label: "Ofertas", icon: BadgeDollarSign, perm: "aff.module.read" },
          { to: "/affiliates/reports", label: "Relatórios", icon: TrendingUp, perm: "aff.module.read" },
        ],
      },
    ],
  },
  {
    label: "Comunicar",
    audiences: ["core", "white-label", "empresa"],
    items: [
      { to: "/ops/mensageria", label: "Mensageria (WhatsApp/E-mail)", icon: MessageSquare },
      { to: "/ops/voz-cliente", label: "Voz do Cliente", icon: Megaphone },
      { to: "/imobiliaria/mensagens", label: "Mensagens (Imob.)", icon: MessageSquare, perm: "realestate.message.read" },
      { to: "/notifications", label: "Notificações", icon: Inbox },
      { to: "/privacy", label: "Privacidade & Notificações", icon: ShieldCheck },
    ],
  },
  {
    label: "Automatizar",
    audiences: ["core", "white-label", "empresa"],
    items: [
      { to: "/ops/versoes", label: "Versões & Atualizações", icon: RefreshCw },
      { to: "/finance/webhook-log", label: "Log de Webhooks", icon: HistoryIcon, perm: "finance.transaction.read" },
    ],
  },
  {
    label: "Analisar",
    audiences: ["core", "white-label", "empresa"],
    items: [
      { to: "/insights/percebido", label: "O que a Impulsionando percebeu", icon: Sparkles },
      { to: "/radar", label: "Radar do Nicho", icon: TrendingUp, superOnly: true },
      { to: "/insights/respostas", label: "Dashboard de Respostas", icon: Sparkles },
      { to: "/insights/oportunidades", label: "Central de Oportunidades", icon: Zap },
      {
        label: "Relatórios",
        icon: BarChart3,
        perm: "report.read",
        children: [
          { to: "/reports", label: "Visão geral", icon: BarChart3, perm: "report.read" },
          { to: "/reports/sales", label: "Vendas", icon: ShoppingCart, perm: "report.read" },
          { to: "/reports/finance", label: "Financeiro", icon: Wallet, perm: "report.read" },
          { to: "/reports/inventory", label: "Estoque", icon: Package, perm: "report.read" },
          { to: "/reports/agenda", label: "Agenda", icon: Calendar, perm: "report.read" },
          { to: "/reports/crm", label: "CRM", icon: UserPlus, perm: "report.read" },
        ],
      },
      {
        label: "BI",
        icon: BarChart3,
        perm: "bi.read",
        children: [
          { to: "/bi", label: "Visão geral", icon: BarChart3, perm: "bi.read" },
          { to: "/bi/company", label: "Por cliente", icon: Building2, perm: "bi.read" },
          { to: "/bi/master", label: "Master", icon: Building2, superOnly: true },
          { to: "/bi/niches", label: "Por nicho", icon: Tags, superOnly: true },
        ],
      },
    ],
  },
  {
    label: "Melhorar",
    items: [
      { to: "/onboarding", label: "Onboarding / Melhorar", icon: Sparkles },
      { to: "/ops/saude", label: "Saúde da Conta", icon: Activity },
      {
        label: "Saiba Mais",
        icon: BookOpen,
        children: [
          { to: "/saiba-mais", label: "Planos, módulos, nichos", icon: BookOpen },
          { to: "/saiba-mais/saude", label: "Saúde — Metodologia", icon: BookOpen },
          { to: "/saiba-mais/versoes", label: "Versões — Pipeline", icon: RefreshCw },
        ],
      },
    ],
  },

  // ============================================================
  // ADMINISTRAÇÃO — reorganizada com submenus por domínio.
  // Lógica: 1 grupo, 10 submenus coesos, hierarquia previsível.
  // ============================================================
  {
    label: "Administração",
    audiences: ["empresa", "core"],
    items: [
      {
        label: "Central Impulsionando",
        icon: ShieldCheck,
        superOnly: true,
        children: [
          { to: "/adm", label: "Central /adm", icon: ShieldCheck, superOnly: true },
          { to: "/adm/master", label: "Painel Master", icon: Crown, superOnly: true },
          { to: "/adm/agentes", label: "Central de Agentes", icon: Bot, superOnly: true },
          { to: "/core", label: "Core — Início", icon: Sparkles, superOnly: true },
          { to: "/core/master", label: "Core Master", icon: Crown, superOnly: true },
          { to: "/core/dashboard-macro", label: "Dashboard Macro", icon: LayoutDashboard, superOnly: true },
          { to: "/core/dashboards", label: "Dashboards Core", icon: LayoutDashboard, superOnly: true },
          { to: "/contabilidade/cockpit", label: "Cockpit Contábil", icon: Calculator, superOnly: true },
        ],
      },
      {
        label: "Organização",
        icon: Building2,
        children: [
          { to: "/companies", label: "Empresas", icon: Building2, superOnly: true },
          { to: "/niches", label: "Nichos", icon: Tags, superOnly: true },
          { to: "/units", label: "Unidades", icon: MapPin, perm: "units.read" },
          { to: "/sectors", label: "Setores", icon: Layers, perm: "sectors.read" },
        ],
      },
      {
        label: "Pessoas & Acessos",
        icon: Users,
        children: [
          { to: "/users", label: "Usuários", icon: Users, perm: "users.read" },
          { to: "/users/corporate", label: "Visão Corporativa", icon: Users, perm: "users.read" },
          { to: "/access-profiles", label: "Perfis de acesso", icon: KeyRound, perm: "profiles.read" },
          { to: "/access-profiles/matrix", label: "Matriz de Permissões", icon: KeyRound, perm: "profiles.read" },
          { to: "/permissions", label: "Permissões", icon: KeyRound, superOnly: true },
        ],
      },
      {
        label: "Módulos & Configurações",
        icon: Boxes,
        children: [
          { to: "/modules", label: "Módulos", icon: Boxes, perm: "modules.read" },
          { to: "/settings", label: "Configurações", icon: SlidersHorizontal, perm: "settings.read" },
          { to: "/core/modulos", label: "Catálogo de Módulos", icon: Boxes, superOnly: true },
          { to: "/core/modulos/agenda", label: "Módulo Agenda", icon: Calendar, superOnly: true },
          { to: "/core/parametros", label: "Parâmetros do Core", icon: SettingsIcon, superOnly: true },
          { to: "/core/flags", label: "Feature Flags", icon: Flag, superOnly: true },
          { to: "/core/menus", label: "Menus & Navegação", icon: Layers, superOnly: true },
          { to: "/admin/modulos/clonagem", label: "Clonagem de Módulos", icon: Copy, superOnly: true },
        ],
      },
      {
        label: "Tenants & White-Label",
        icon: Globe,
        superOnly: true,
        children: [
          { to: "/core/clientes", label: "Clientes (Tenants)", icon: Building2, superOnly: true },
          { to: "/core/tenants/novo", label: "Novo Tenant", icon: Plus, superOnly: true },
          { to: "/core/dominios", label: "Domínios", icon: Globe, superOnly: true },
          { to: "/core/tenants/dominios", label: "Domínios por Tenant", icon: Globe, superOnly: true },
          { to: "/core/implantacoes", label: "Implantações", icon: Rocket, superOnly: true },
          { to: "/core/nova-implantacao", label: "Nova Implantação", icon: Rocket, superOnly: true },
          { to: "/core/importar-clientes", label: "Importar Clientes", icon: UserPlus, superOnly: true },
          { to: "/white-label/cockpit", label: "WL — Cockpit", icon: Layers, superOnly: true },
          { to: "/white-label/capacidade", label: "WL — Capacidade", icon: Gauge, superOnly: true },
        ],
      },
      {
        label: "Faturamento & Planos",
        icon: CreditCard,
        superOnly: true,
        children: [
          { to: "/admin/billing", label: "Billing", icon: CreditCard, superOnly: true },
          { to: "/admin/billing-contracts", label: "Contratos recorrentes", icon: ScrollText, superOnly: true },
          { to: "/admin/billing-policy", label: "Régua de cobrança", icon: ClipboardList, superOnly: true },
          { to: "/admin/niche-plans", label: "Planos por Nicho", icon: Tags, superOnly: true },
          { to: "/core/planos", label: "Catálogo de Planos", icon: BadgeDollarSign, superOnly: true },
          { to: "/admin/trials", label: "Trials (7 dias)", icon: Sparkles, superOnly: true },
          { to: "/admin/pix-pendentes", label: "PIX Pendentes", icon: QrCode, superOnly: true, badge: "pendingPix" },
          { to: "/admin/integracoes/mercado-pago", label: "Mercado Pago", icon: Wallet, superOnly: true },
          { to: "/core/integracoes/mercadopago", label: "MP (Core)", icon: Wallet, superOnly: true },
          { to: "/core/financeiro-consolidado", label: "Financeiro Consolidado", icon: Banknote, superOnly: true },
          { to: "/core/financeiro-master", label: "Financeiro Master", icon: Banknote, superOnly: true },
          { to: "/core/repasses", label: "Repasses", icon: ArrowLeftRight, superOnly: true },
          { to: "/core/monetizacao", label: "Monetização", icon: TrendingUp, superOnly: true },
          { to: "/core/contratos", label: "Contratos", icon: ScrollText, superOnly: true },
        ],
      },
      {
        label: "Catálogo & Plataforma",
        icon: FileCode,
        superOnly: true,
        children: [
          { to: "/core/templates", label: "Templates", icon: FileCode, superOnly: true },
          { to: "/core/prompts", label: "Prompts (IA)", icon: Bot, superOnly: true },
          { to: "/core/releases", label: "Releases", icon: RefreshCw, superOnly: true },
          { to: "/core/metricas-reguas", label: "Métricas & Réguas", icon: LineChart, superOnly: true },
          { to: "/core/instalar-modulo", label: "Instalar Módulo", icon: Plus, superOnly: true },
          { to: "/admin/catalog-analytics", label: "Catálogo — Analytics", icon: BarChart3, superOnly: true },
          { to: "/admin/catalog-intents", label: "Catálogo — Intents", icon: Workflow, superOnly: true },
        ],
      },
      {
        label: "Marketing & Comercial",
        icon: Megaphone,
        superOnly: true,
        children: [
          { to: "/core/marketing-leads", label: "Leads (Marketing)", icon: Inbox, superOnly: true },
          { to: "/core/marketing-pages", label: "Páginas de Marketing", icon: FileCode, superOnly: true },
          { to: "/core/feira-leads", label: "Feira de Leads", icon: Store, superOnly: true },
          { to: "/core/briefings", label: "Briefings", icon: ClipboardList, superOnly: true },
          { to: "/core/finalizacao-comercial", label: "Finalização Comercial", icon: Handshake, superOnly: true },
          { to: "/core/demos", label: "Demos", icon: FlaskConical, superOnly: true },
          { to: "/core/demo-insights", label: "Insights de Demos", icon: Sparkles, superOnly: true },
          { to: "/core/eventos", label: "Eventos", icon: Calendar, superOnly: true },
          { to: "/core/criar-projeto", label: "Criar Projeto", icon: Plus, superOnly: true },
        ],
      },
      {
        label: "Qualidade & Observabilidade",
        icon: Activity,
        children: [
          { to: "/admin/qualidade", label: "Qualidade", icon: ShieldCheck, superOnly: true },
          { to: "/admin/uptime", label: "Uptime", icon: Activity, superOnly: true },
          { to: "/admin/whatsapp-metrics", label: "WhatsApp — Métricas", icon: MessageSquare, superOnly: true },
          { to: "/core/observabilidade", label: "Observabilidade", icon: Server, superOnly: true },
          { to: "/core/saude", label: "Saúde da Plataforma", icon: Activity, superOnly: true },
          { to: "/core/diagnostico-geral", label: "Diagnóstico Geral", icon: Gauge, superOnly: true },
          { to: "/core/integracoes/diagnostico", label: "Integrações — Diagnóstico", icon: Gauge, superOnly: true },
          { to: "/core/integracoes/n8n", label: "n8n", icon: Workflow, superOnly: true },
          { to: "/admin/n8n-console", label: "Console N8N", icon: Workflow, superOnly: true },
          { to: "/admin/funil-reguas", label: "Réguas de Funil", icon: Workflow, superOnly: true },
          { to: "/admin/inbox-eventos", label: "Inbox de Eventos", icon: Activity, superOnly: true },
          { to: "/admin/audit-trail", label: "Audit Trail", icon: ShieldCheck, superOnly: true },
          { to: "/admin/cofre-credenciais", label: "Cofre de Credenciais", icon: ShieldCheck, superOnly: true },
          { to: "/admin/financeiro-consolidado-v2", label: "Financeiro Consolidado v2", icon: Banknote, superOnly: true },
          { to: "/admin/catalogo-matriz", label: "Catálogo Unificado", icon: Layers, superOnly: true },
          { to: "/admin/cockpit-tenants", label: "Cockpit de Tenants", icon: Building2, superOnly: true },
          { to: "/admin/acoes", label: "Ações Administrativas", icon: ShieldCheck, superOnly: true },
          { to: "/admin/health-score", label: "Health Score Global", icon: Activity, superOnly: true },
          { to: "/admin/cohort-retention", label: "Cohort & Retention", icon: LineChart, superOnly: true },
          { to: "/admin/unit-economics", label: "Unit Economics", icon: TrendingUp, superOnly: true },
          { to: "/admin/revenue-quality", label: "Revenue Quality", icon: Gauge, superOnly: true },
          { to: "/admin/sla-compliance", label: "SLA Compliance", icon: ShieldCheck, superOnly: true },
          { to: "/admin/security-compliance", label: "Security & Compliance", icon: ShieldCheck, superOnly: true },
          { to: "/admin/customer-success", label: "Customer Success", icon: Headphones, superOnly: true },
          { to: "/admin/conversion-funnel", label: "Conversion Funnel", icon: Filter, superOnly: true },
          { to: "/admin/expansion-engine", label: "Expansion & Upsell", icon: Rocket, superOnly: true },
          { to: "/admin/churn-radar", label: "Churn Radar", icon: ShieldCheck, superOnly: true },
          { to: "/admin/pricing-intelligence", label: "Pricing & Discount", icon: BadgeDollarSign, superOnly: true },
          { to: "/admin/treasury-forecast", label: "Treasury Forecast", icon: Banknote, superOnly: true },
          { to: "/admin/tax-compliance", label: "Tax & Compliance", icon: Receipt, superOnly: true },
          { to: "/admin/vendor-performance", label: "Vendor & Partner Perf", icon: Handshake, superOnly: true },
          { to: "/admin/data-quality", label: "Data Quality & Dedupe", icon: Copy, superOnly: true },
          { to: "/admin/notification-delivery", label: "Notification Delivery", icon: Send, superOnly: true },
          { to: "/admin/adoption-usage", label: "Adoption & Usage", icon: Rocket, superOnly: true },
          { to: "/admin/tenant-lifecycle", label: "Tenant Lifecycle", icon: CalendarClock, superOnly: true },
          { to: "/admin/marketplace-ops", label: "Marketplace Ops", icon: Store, superOnly: true },
          { to: "/admin/agenda-health", label: "Agenda & Booking Health", icon: Calendar, superOnly: true },
          { to: "/admin/ehr-compliance", label: "EHR & Clinical Compliance", icon: Stethoscope, superOnly: true },
          { to: "/admin/fiscal-health", label: "Fiscal & NF-e Health", icon: Receipt, superOnly: true },
          { to: "/admin/comms-health", label: "Comunicação Omnichannel", icon: Send, superOnly: true },
          { to: "/admin/compliance-health", label: "LGPD & Compliance", icon: ShieldCheck, superOnly: true },
          { to: "/admin/trial-onboarding-health", label: "Trial & Onboarding", icon: Rocket, superOnly: true },
          { to: "/admin/marketplace-health", label: "Marketplace & Afiliados", icon: Store, superOnly: true },
          { to: "/admin/realestate-health", label: "Imobiliário & Temporada", icon: Home, superOnly: true },
          { to: "/admin/cofre-credenciais", label: "Cofre de Credenciais", icon: KeyRound, superOnly: true },
          { to: "/admin/affiliates-health", label: "Affiliates & Co-producer", icon: Handshake, superOnly: true },
          { to: "/admin/real-estate-health", label: "Real Estate Cockpit", icon: Home, superOnly: true },
          { to: "/admin/educ-talentos", label: "Educacional & Talentos", icon: GraduationCap, superOnly: true },
          { to: "/admin/contab-health", label: "Contábil & Office", icon: Calculator, superOnly: true },
          { to: "/admin/events-health", label: "Eventos & Ticketing", icon: Ticket, superOnly: true },
          { to: "/admin/brewery-clube-health", label: "Brewery & Clube", icon: Beer, superOnly: true },
          { to: "/admin/restaurant-health", label: "Restaurant & POS", icon: Utensils, superOnly: true },
          { to: "/admin/inventory-health", label: "Inventory & Stock", icon: Package, superOnly: true },
          { to: "/admin/finance-health", label: "Finance & Cashflow", icon: Wallet, superOnly: true },
          { to: "/admin/crm-health", label: "CRM & Pipeline", icon: KanbanSquare, superOnly: true },
          { to: "/admin/marketing-health", label: "Marketing & Outbox", icon: Megaphone, superOnly: true },
          { to: "/admin/marketplace-b2b-health", label: "Marketplace B2B", icon: Store, superOnly: true },
          { to: "/admin/trial-demo-health", label: "Trial & Demo Gov.", icon: FlaskConical, superOnly: true },
          { to: "/admin/ai-automation-health", label: "AI & Automation", icon: Bot, superOnly: true },
          { to: "/admin/whitelabel-health", label: "White-Label & Vitrine", icon: Globe, superOnly: true },
          { to: "/admin/notifications-cockpit", label: "Notifications Cockpit", icon: Inbox, superOnly: true },
          { to: "/admin/mercadopago-billing-health", label: "MercadoPago & Billing", icon: CreditCard, superOnly: true },
          { to: "/admin/marocas-health", label: "Marocas Hospitality", icon: Building2, superOnly: true },
          { to: "/admin/governance-lgpd-health", label: "Governance & LGPD", icon: ShieldCheck, superOnly: true },
          { to: "/admin/support-ticketing-health", label: "Support & Ticketing", icon: Headphones, superOnly: true },
          { to: "/admin/events-ticketing-health", label: "Eventos & Ticketing", icon: Ticket, superOnly: true },
          { to: "/admin/realestate-cockpit", label: "Imobiliária — Cockpit", icon: Home, superOnly: true },
          { to: "/admin/documents-files-health", label: "Documents & Files", icon: FileCode, superOnly: true },
          { to: "/admin/sales-pos-health", label: "Sales & POS", icon: ShoppingCart, superOnly: true },
          { to: "/admin/ehr-clinical-health", label: "EHR & Clinical", icon: Stethoscope, superOnly: true },
          { to: "/admin/community-health", label: "Community", icon: Users, superOnly: true },
          { to: "/admin/agenda-ops-health", label: "Agenda Operations", icon: CalendarClock, superOnly: true },
          { to: "/admin/ai-projects-health", label: "AI Projects & Pages", icon: Sparkles, superOnly: true },
          { to: "/admin/loyalty-clube-health", label: "Loyalty & Clube", icon: Crown, superOnly: true },
          { to: "/admin/onboarding-provisioning-health", label: "Onboarding & Provisioning", icon: Rocket, superOnly: true },
          { to: "/admin/integrations-automation-health", label: "Integrations & Automation", icon: Workflow, superOnly: true },
          { to: "/admin/payouts-monetization-health", label: "Payouts & Monetization", icon: Banknote, superOnly: true },
          { to: "/admin/config-catalog-health", label: "Config & Catalog", icon: SlidersHorizontal, superOnly: true },
          { to: "/admin/ecosystem-marketplace-health", label: "Ecosystem Marketplace", icon: Handshake, superOnly: true },
          { to: "/admin/growth-funnel-health", label: "Growth Funnel", icon: Filter, superOnly: true },
          { to: "/admin/tenant-identity-health", label: "Tenant Identity & Branding", icon: Building2, superOnly: true },
          { to: "/admin/consumer-journey-health", label: "Consumer Journey & Membership", icon: UserRound, superOnly: true },
          { to: "/admin/audit-security-health", label: "Audit & Security", icon: ShieldCheck, superOnly: true },
          { to: "/admin/jobs-queues-reliability-health", label: "Jobs, Queues & Reliability", icon: Workflow, superOnly: true },
          { to: "/admin/vitrine-legal-health", label: "Vitrine, Site Builder & Legal", icon: Globe, superOnly: true },
          { to: "/admin/notification-deliverability-health", label: "Notification & Deliverability", icon: Inbox, superOnly: true },
          { to: "/admin/real-estate-ops-health", label: "Real Estate Ops & Brokerage", icon: Home, superOnly: true },
          { to: "/admin/education-polos-health", label: "Educação & Polos", icon: GraduationCap, superOnly: true },
          { to: "/admin/affiliates-cockpit-health", label: "Afiliados & Comissões", icon: BadgeDollarSign, superOnly: true },
          { to: "/admin/contab-cockpit-health", label: "Contabilidade", icon: Calculator, superOnly: true },
          { to: "/admin/marocas-ops-health", label: "Marocas — Temporada", icon: Building2, superOnly: true },
          { to: "/admin/talentos-cockpit-health", label: "Talentos", icon: Users, superOnly: true },
          { to: "/admin/agenda-resources-health", label: "Agenda — Recursos", icon: Calendar, superOnly: true },
          { to: "/admin/agenda-operations-health", label: "Agenda — Operações", icon: CalendarClock, superOnly: true },
          { to: "/admin/crm-funnel-health", label: "CRM & Funil", icon: KanbanSquare, superOnly: true },
          { to: "/admin/finance-health", label: "Financeiro", icon: Wallet, superOnly: true },
          { to: "/admin/billing-health", label: "Billing & Assinaturas", icon: CreditCard, superOnly: true },
          { to: "/admin/presales-health", label: "Pré-Vendas & Conversão", icon: Handshake, superOnly: true },
          { to: "/admin/runtime-uptime-health", label: "Runtime & Uptime", icon: Activity, superOnly: true },
          { to: "/core/testes", label: "Testes", icon: FlaskConical, superOnly: true },
          { to: "/core/bi-ecossistema", label: "BI Ecossistema", icon: BarChart3, superOnly: true },
        ],
      },
      {
        label: "Clube, Suporte & Consumidor",
        icon: Crown,
        superOnly: true,
        children: [
          { to: "/admin/clube", label: "Clube — Cockpit", icon: Crown, superOnly: true },
          { to: "/core/consumidor-premium", label: "Consumidor Premium", icon: UserRound, superOnly: true },
          { to: "/torre/consumidores", label: "Torre · Consumidor Final", icon: UserRound, superOnly: true },
          { to: "/torre/restaurantes-demo", label: "Torre · Restaurantes Demo", icon: BarChart3, superOnly: true },
          { to: "/showroom/restaurante", label: "Showroom · Bar/Restaurante", icon: QrCode, superOnly: true },
          { to: "/support/cockpit", label: "Suporte — Cockpit", icon: Headphones, superOnly: true },
        ],
      },
      {
        label: "Compliance & Auditoria",
        icon: FileSearch,
        children: [
          { to: "/audit", label: "Auditoria", icon: FileSearch, perm: "audit.read" },
          { to: "/privacy/cockpit", label: "Cockpit LGPD", icon: ShieldCheck, superOnly: true },
        ],
      },
      {
        label: "Verticais Específicas",
        icon: Stethoscope,
        superOnly: true,
        children: [
          { to: "/admin/fiscal", label: "Fiscal", icon: Receipt, superOnly: true },
          { to: "/admin/imobiliaria", label: "Imobiliária — Admin", icon: Home, superOnly: true },
          { to: "/chrismed/admin", label: "ChrisMed — Admin", icon: Stethoscope, superOnly: true },
          { to: "/chrismed/setup", label: "ChrisMed — Setup", icon: SettingsIcon, superOnly: true },
          { to: "/chrismed/alertas", label: "ChrisMed — Alertas", icon: Inbox, superOnly: true },
        ],
      },
    ],
  },
];
