server {
  listen 80;
  listen [::]:80;
  server_name chrismed.com.br www.chrismed.com.br;

  location /.well-known/acme-challenge/ {
    root /var/www/letsencrypt;
  }

  location / {
    return 301 https://chrismed.impulsionando.com.br$request_uri;
  }
}
