server {
  listen 80;
  listen [::]:80;
  server_name chrismed.com.br www.chrismed.com.br;

  location /.well-known/acme-challenge/ {
    root /var/www/letsencrypt;
  }

  location / {
    return 301 https://chrismed.impulsionando.com.br$request_uri;
  }
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name chrismed.com.br www.chrismed.com.br;

  ssl_certificate /etc/letsencrypt/live/chrismed.com.br/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/chrismed.com.br/privkey.pem;

  access_log /var/log/nginx/chrismed-legacy.access.log;
  error_log /var/log/nginx/chrismed-legacy.error.log warn;

  return 301 https://chrismed.impulsionando.com.br$request_uri;
}
