import { createFileRoute, Link } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { FileCheck2, UploadCloud, WalletCards, Clock3, Receipt, ArrowLeft } from 'lucide-react';
import { toast } from 'sonner';

const COMPANY_ID='642096b5-a9ff-4521-a82a-c004f6d2e2d2';
type Dashboard={professional:{id:string;name:string;profile_status:string;is_active:boolean};reference_month:string;invoice:any;eligibility:any;wallet:any;settlements:any[];policy:any};
const money=(cents=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(cents||0)/100);
const monthValue=()=>{const d=new Date();d.setMonth(d.getMonth()-1);return d.toISOString().slice(0,7);};

export const Route=createFileRoute('/_authenticated/chrismed/profissional/financeiro')({component:ProfessionalFinancePage,head:()=>({meta:[{title:'Financeiro do profissional — CHRISMED'}]})});

function ProfessionalFinancePage(){
 const [month,setMonth]=useState(monthValue()); const [data,setData]=useState<Dashboard|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [invoiceNumber,setInvoiceNumber]=useState(''); const [issuedDate,setIssuedDate]=useState(''); const [file,setFile]=useState<File|null>(null);
 async function load(m=month){setLoading(true);const {data:r,error}=await (supabase as any).rpc('chrismed_get_my_professional_finance_dashboard',{p_reference_month:`${m}-01`});setLoading(false);if(error){toast.error('Não foi possível carregar seu financeiro.');return;}setData(r as Dashboard);setInvoiceNumber((r as any)?.invoice?.invoice_number??'');setIssuedDate((r as any)?.invoice?.issued_at?.slice(0,10)??'');}
 useEffect(()=>{void load();},[]);
 async function changeMonth(v:string){setMonth(v);await load(v);}
 async function submit(e:React.FormEvent){e.preventDefault();if(!file)return toast.error('Selecione a nota fiscal em PDF ou imagem.');if(!invoiceNumber.trim()||!issuedDate)return toast.error('Informe número e data de emissão.');setBusy(true);const {data:auth}=await supabase.auth.getUser();if(!auth.user){setBusy(false);return toast.error('Sessão expirada.');}const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${COMPANY_ID}/${auth.user.id}/${month}/${crypto.randomUUID()}-${safe}`;const {error:up}=await supabase.storage.from('chrismed-professional-fiscal').upload(path,file,{contentType:file.type,upsert:false});if(up){setBusy(false);return toast.error('Não foi possível enviar a nota fiscal.');}const {data:r,error}=await (supabase as any).rpc('chrismed_submit_professional_invoice',{p_reference_month:`${month}-01`,p_invoice_number:invoiceNumber.trim(),p_issued_at:new Date(`${issuedDate}T12:00:00-03:00`).toISOString(),p_storage_path:path,p_original_filename:file.name});setBusy(false);if(error){await supabase.storage.from('chrismed-professional-fiscal').remove([path]);return toast.error('Não foi possível registrar a nota fiscal.');}toast.success((r as any)?.status==='late'?'Nota recebida e marcada como enviada após o prazo.':'Nota fiscal enviada para validação.');setFile(null);await load();}
 const elig=data?.eligibility??{};const invoice=data?.invoice??{};const settlements=data?.settlements??[];
 return <main className="min-h-screen bg-[#F7F3EA] px-4 py-8 text-[#071C18] sm:px-6"><div className="mx-auto max-w-6xl space-y-6">
  <header className="rounded-3xl border border-[#D9D3CB] bg-white p-6"><Link to="/agenda/profissional" className="mb-3 inline-flex items-center text-sm"><ArrowLeft className="mr-1 h-4 w-4"/>Voltar à agenda</Link><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#596660]">Parceiro CHRISMED</p><h1 className="mt-1 text-3xl font-bold">Financeiro e compliance</h1><p className="mt-2 text-sm text-[#3F4A47]">Nota fiscal mensal, recebíveis D7/D37, carteira e repasses em um só lugar.</p></header>
  <div className="flex flex-wrap items-end gap-3 rounded-2xl border bg-white p-4"><div><Label>Período de referência</Label><Input type="month" value={month} onChange={e=>void changeMonth(e.target.value)} /></div><div className="text-xs text-[#596660]">A NF do período deve ser emitida no primeiro dia útil do mês seguinte.</div></div>
  <section className="grid gap-4 md:grid-cols-4"><Metric icon={Receipt} label="Status da NF" value={invoice.status??'PENDENTE'}/><Metric icon={WalletCards} label="Recebíveis maduros" value={money(elig.matured_amount_cents)}/><Metric icon={Clock3} label="Ainda a maturar" value={money(elig.unmatured_amount_cents)}/><Metric icon={FileCheck2} label="Elegível para repasse" value={elig.can_prepare_payout?'SIM':'NÃO'}/></section>
  <section className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>Nota fiscal obrigatória</CardTitle></CardHeader><CardContent className="space-y-4">{invoice.id&&<div className="rounded-xl border bg-[#FDFCFB] p-4 text-sm"><div className="flex gap-2"><Badge>{invoice.status}</Badge><span>NF {invoice.invoice_number??'—'}</span></div><p className="mt-2 text-[#596660]">Emissão: {invoice.issued_at?new Date(invoice.issued_at).toLocaleDateString('pt-BR'):'—'} · Prazo: {invoice.due_business_date?new Date(`${invoice.due_business_date}T12:00:00`).toLocaleDateString('pt-BR'):'—'}</p>{invoice.validation_notes&&<p className="mt-2">Observação: {invoice.validation_notes}</p>}</div>}<form onSubmit={submit} className="space-y-3"><div><Label>Número da NF</Label><Input value={invoiceNumber} onChange={e=>setInvoiceNumber(e.target.value)}/></div><div><Label>Data de emissão</Label><Input type="date" value={issuedDate} onChange={e=>setIssuedDate(e.target.value)}/></div><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed p-5"><UploadCloud className="h-5 w-5"/>{file?file.name:'Selecionar NF (PDF ou imagem)'}<input className="hidden" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><Button disabled={busy} className="w-full">{busy?'Enviando…':'Enviar nota fiscal'}</Button></form></CardContent></Card>
  <Card><CardHeader><CardTitle>Regra de recebimento</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><div className="rounded-xl border p-4"><strong>PIX — D7</strong><p className="mt-1 text-[#596660]">Recebíveis de pagamentos via PIX entram na base elegível após 7 dias.</p></div><div className="rounded-xl border p-4"><strong>Cartão — D37</strong><p className="mt-1 text-[#596660]">Recebíveis em cartão entram na base elegível após 37 dias.</p></div><div className="rounded-xl border p-4"><strong>NF obrigatória</strong><p className="mt-1 text-[#596660]">Sem nota fiscal do período, o sistema bloqueia a preparação do repasse.</p></div><div className="rounded-xl border p-4"><strong>Carteira</strong><p className="mt-1 text-[#596660]">Saldo a compensar: {money(data?.wallet?.unsettled_balance_cents??0)}.</p></div></CardContent></Card></section>
  <Card><CardHeader><CardTitle>Histórico de repasses</CardTitle></CardHeader><CardContent className="space-y-2">{!settlements.length&&<p className="text-sm text-[#596660]">Nenhum repasse registrado.</p>}{settlements.map(s=><div key={s.id} className="grid gap-2 rounded-xl border p-4 md:grid-cols-4"><div><span className="text-xs text-[#596660]">Criado</span><div>{new Date(s.created_at).toLocaleDateString('pt-BR')}</div></div><div><span className="text-xs text-[#596660]">Bruto</span><div>{money(s.gross_payout_cents)}</div></div><div><span className="text-xs text-[#596660]">Líquido</span><div>{money(s.net_payout_cents)}</div></div><div><span className="text-xs text-[#596660]">Status</span><div><Badge variant="outline">{s.status}</Badge></div></div></div>)}</CardContent></Card>
 </div></main>;
}
function Metric({icon:Icon,label,value}:{icon:typeof Receipt;label:string;value:string}){return <Card><CardContent className="pt-6"><Icon className="mb-3 h-5 w-5 text-[#078f8b]"/><p className="text-xs text-[#596660]">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></CardContent></Card>}
