import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ShieldCheck, Headphones } from "lucide-react";

export const Route = createFileRoute("/_authenticated/revela/suporte")({ component: RevelaSupportPage });

async function loadSupport(){
 const {data:company,error:ce}=await supabase.from("companies").select("id,name").ilike("name","REVELA").limit(1).maybeSingle(); if(ce)throw ce;if(!company)throw new Error("Empresa REVELA não encontrada.");
 const [{data:tickets,error:te},{data:cases,error:oe}]=await Promise.all([
  supabase.from("support_tickets").select("id,ticket_code,category,priority,status,subject,description,source_channel,first_response_due_at,resolution_due_at,created_at").eq("company_id",company.id).order("created_at",{ascending:false}).limit(200),
  supabase.from("revela_ombudsman_cases").select("id,protocol,category,subject,description,confidentiality,priority,status,due_at,resolution_summary,created_at").eq("company_id",company.id).order("created_at",{ascending:false}).limit(200)
 ]); if(te)throw te;if(oe)throw oe;return {tickets:tickets??[],cases:cases??[]};
}
const closed=(s:string)=>["resolved","closed","dismissed"].includes(s);
function RevelaSupportPage(){const q=useQuery({queryKey:["revela-support"],queryFn:loadSupport,refetchInterval:30000});if(q.isLoading)return <Card className="p-6">Carregando atendimento…</Card>;if(q.error||!q.data)return <Card className="p-6">{q.error instanceof Error?q.error.message:"Falha no atendimento"}</Card>;const openT=q.data.tickets.filter((x:any)=>!closed(x.status));const openO=q.data.cases.filter((x:any)=>!closed(x.status));return <div className="mx-auto max-w-6xl space-y-5"><header><Badge>REVELA</Badge><h1 className="mt-2 text-3xl font-semibold">Atendimento & Ouvidoria</h1><p className="text-muted-foreground">Canais separados: suporte operacional para resolução do dia a dia e Ouvidoria para manifestações institucionais.</p></header><div className="grid gap-4 md:grid-cols-2"><Card className="p-5"><Headphones className="h-5 w-5"/><div className="mt-3 text-3xl font-semibold">{openT.length}</div><div className="text-sm text-muted-foreground">tickets de suporte abertos</div></Card><Card className="p-5"><ShieldCheck className="h-5 w-5"/><div className="mt-3 text-3xl font-semibold">{openO.length}</div><div className="text-sm text-muted-foreground">manifestações de Ouvidoria abertas</div></Card></div><Tabs defaultValue="support"><TabsList><TabsTrigger value="support">Suporte</TabsTrigger><TabsTrigger value="ombudsman">Ouvidoria</TabsTrigger></TabsList><TabsContent value="support"><Card className="divide-y">{q.data.tickets.length===0?<div className="p-8 text-center text-sm text-muted-foreground">Nenhum ticket registrado.</div>:q.data.tickets.map((t:any)=><div key={t.id} className="p-4"><div className="flex flex-wrap items-center gap-2"><b>{t.ticket_code}</b><Badge variant="outline">{t.status}</Badge><Badge variant="secondary">{t.priority}</Badge></div><div className="mt-1 font-medium">{t.subject}</div><div className="mt-1 text-sm text-muted-foreground">{t.category} · {t.source_channel} · {new Date(t.created_at).toLocaleString("pt-BR")}</div></div>)}</Card></TabsContent><TabsContent value="ombudsman"><Card className="divide-y">{q.data.cases.length===0?<div className="p-8 text-center text-sm text-muted-foreground">Nenhuma manifestação registrada.</div>:q.data.cases.map((o:any)=><div key={o.id} className="p-4"><div className="flex flex-wrap items-center gap-2"><b>{o.protocol}</b><Badge variant="outline">{o.status}</Badge><Badge variant="secondary">{o.priority}</Badge>{o.confidentiality==="confidential"?<Badge>confidencial</Badge>:null}</div><div className="mt-1 font-medium">{o.subject}</div><div className="mt-1 text-sm text-muted-foreground">{o.category} · {new Date(o.created_at).toLocaleString("pt-BR")}</div></div>)}</Card></TabsContent></Tabs></div>}
