import { createFileRoute } from '@tanstack/react-router';
import { createHmac, timingSafeEqual } from 'crypto';
import { askOliver } from '@/lib/oliver-chat.functions';
import { listConversationHistory, recordInboundMessage, recordOutboundMessage } from '@/lib/agents/omnichannel.server';

function verify(raw:string,header:string|null){const secret=(process.env.CHRISMED_META_APP_SECRET||'').trim();if(!secret||!header?.startsWith('sha256='))return false;const expected=createHmac('sha256',secret).update(raw).digest('hex');const supplied=header.slice(7);if(expected.length!==supplied.length)return false;return timingSafeEqual(Buffer.from(expected,'hex'),Buffer.from(supplied,'hex'));}
function history(history:Awaited<ReturnType<typeof listConversationHistory>>){return history.flatMap((m):Array<{role:'user'|'assistant';content:string}>=>{const text=String(m.body_text||'').trim();if(!text)return[];if(m.direction==='INBOUND'||m.author_type==='CONTACT')return[{role:'user',content:text}];if(m.direction==='OUTBOUND'&&m.author_type==='AGENT')return[{role:'assistant',content:text}];return[];}).slice(-20);}
async function sendInstagram(to:string,text:string){const token=(process.env.CHRISMED_META_IG_TOKEN||'').trim();const ig=(process.env.CHRISMED_META_IG_ACCOUNT_ID||'').trim();const version=(process.env.CHRISMED_META_GRAPH_VERSION||'v23.0').trim();if(!token||!ig)throw new Error('instagram_credentials_missing');const r=await fetch(`https://graph.instagram.com/${version}/${encodeURIComponent(ig)}/messages`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({recipient:{id:to},message:{text:text.slice(0,2000)}}),signal:AbortSignal.timeout(12000)});const raw=await r.text();let data:any={};try{data=raw?JSON.parse(raw):{}}catch{data={}}if(!r.ok)throw new Error(`instagram_send_${r.status}`);return data;}
async function processMessage(m:any){const ledger=await recordInboundMessage({agentKey:'chrismed-oliver',channel:'instagram',provider:'meta_graph',externalUserId:m.externalUserId,bodyText:m.text,providerMessageId:m.providerMessageId||null,endpointAddress:m.endpointAddress||null,metadata:{tenant:'chrismed',source:'meta_instagram',health_context:true,root_agent_key:'impulsionito-core'}});const messages=history(await listConversationHistory(ledger.conversation_id,30));const result=await askOliver({data:{messages,pathname:'/instagram',lang:'pt'}});const answer=String(result.reply||'').trim();if(!answer)return;try{const sent=await sendInstagram(m.externalUserId,answer);await recordOutboundMessage({conversationId:ledger.conversation_id,bodyText:answer,channel:'instagram',provider:'meta_graph',endpointId:ledger.endpoint_id,status:result.error?'DEGRADED':'SENT',providerMessageId:String(sent?.message_id||sent?.messageId||'')||null,metadata:{agent_key:'chrismed-oliver',root_agent_key:'impulsionito-core',health_context:true}})}catch(error){await recordOutboundMessage({conversationId:ledger.conversation_id,bodyText:answer,channel:'instagram',provider:'meta_graph',endpointId:ledger.endpoint_id,status:'FAILED',metadata:{agent_key:'chrismed-oliver',delivery_error:error instanceof Error?error.message:'unknown'}});throw error}}
function extract(body:any){const out:any[]=[];if(body?.object!=='instagram')return out;for(const entry of body?.entry||[])for(const ev of entry?.messaging||[]){const text=ev?.message?.text;if(text&&!ev?.message?.is_echo)out.push({externalUserId:String(ev.sender?.id||''),text:String(text),providerMessageId:ev.message?.mid||null,endpointAddress:String(ev.recipient?.id||'')})}return out}
export const Route=createFileRoute('/api/public/hooks/meta-chrismed')({server:{handlers:{GET:async({request})=>{const u=new URL(request.url);const challenge=u.searchParams.get('hub.challenge');const ok=u.searchParams.get('hub.mode')==='subscribe'&&u.searchParams.get('hub.verify_token')===(process.env.CHRISMED_META_VERIFY_TOKEN||'')&&challenge;return ok?new Response(String(challenge),{status:200}):new Response('forbidden',{status:403})},POST:async({request})=>{const raw=await request.text();if(!verify(raw,request.headers.get('x-hub-signature-256')))return new Response('invalid signature',{status:401});let body:any;try{body=JSON.parse(raw)}catch{return new Response('invalid json',{status:400})}for(const m of extract(body).filter((x:any)=>x.externalUserId&&x.text)){try{await processMessage(m)}catch(e){console.error('[meta-chrismed]',e)}}return new Response('EVENT_RECEIVED',{status:200})}}}});
