/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedUnitsRouteImport } from './routes/_authenticated/units'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSectorsRouteImport } from './routes/_authenticated/sectors'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedNichesRouteImport } from './routes/_authenticated/niches'
import { Route as AuthenticatedModulesRouteImport } from './routes/_authenticated/modules'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAccessProfilesRouteImport } from './routes/_authenticated/access-profiles'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales.index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory.index'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance.index'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm.index'
import { Route as AuthenticatedAgendaIndexRouteImport } from './routes/_authenticated/agenda.index'
import { Route as AuthenticatedSalesOrdersRouteImport } from './routes/_authenticated/sales.orders'
import { Route as AuthenticatedSalesNewRouteImport } from './routes/_authenticated/sales.new'
import { Route as AuthenticatedSalesCashRouteImport } from './routes/_authenticated/sales.cash'
import { Route as AuthenticatedInventorySuppliersRouteImport } from './routes/_authenticated/inventory.suppliers'
import { Route as AuthenticatedInventoryProductsRouteImport } from './routes/_authenticated/inventory.products'
import { Route as AuthenticatedInventoryMovementsRouteImport } from './routes/_authenticated/inventory.movements'
import { Route as AuthenticatedInventoryCategoriesRouteImport } from './routes/_authenticated/inventory.categories'
import { Route as AuthenticatedFinanceTransactionsRouteImport } from './routes/_authenticated/finance.transactions'
import { Route as AuthenticatedFinanceMethodsRouteImport } from './routes/_authenticated/finance.methods'
import { Route as AuthenticatedFinanceCommissionsRouteImport } from './routes/_authenticated/finance.commissions'
import { Route as AuthenticatedFinanceCategoriesRouteImport } from './routes/_authenticated/finance.categories'
import { Route as AuthenticatedFinanceAccountsRouteImport } from './routes/_authenticated/finance.accounts'
import { Route as AuthenticatedCrmPipelinesRouteImport } from './routes/_authenticated/crm.pipelines'
import { Route as AuthenticatedCrmLeadsRouteImport } from './routes/_authenticated/crm.leads'
import { Route as AuthenticatedCrmBoardRouteImport } from './routes/_authenticated/crm.board'
import { Route as AuthenticatedCrmActivitiesRouteImport } from './routes/_authenticated/crm.activities'
import { Route as AuthenticatedAgendaWaitlistRouteImport } from './routes/_authenticated/agenda.waitlist'
import { Route as AuthenticatedAgendaServicesRouteImport } from './routes/_authenticated/agenda.services'
import { Route as AuthenticatedAgendaSchedulesRouteImport } from './routes/_authenticated/agenda.schedules'
import { Route as AuthenticatedAgendaProfessionalsRouteImport } from './routes/_authenticated/agenda.professionals'
import { Route as AuthenticatedAgendaAppointmentsRouteImport } from './routes/_authenticated/agenda.appointments'
import { Route as AuthenticatedSalesCashIdRouteImport } from './routes/_authenticated/sales.cash.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUnitsRoute = AuthenticatedUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSectorsRoute = AuthenticatedSectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNichesRoute = AuthenticatedNichesRouteImport.update({
  id: '/niches',
  path: '/niches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModulesRoute = AuthenticatedModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccessProfilesRoute =
  AuthenticatedAccessProfilesRouteImport.update({
    id: '/access-profiles',
    path: '/access-profiles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSalesRoute,
} as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInventoryRoute,
  } as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedAgendaIndexRoute =
  AuthenticatedAgendaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAgendaRoute,
  } as any)
const AuthenticatedSalesOrdersRoute =
  AuthenticatedSalesOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedSalesRoute,
  } as any)
const AuthenticatedSalesNewRoute = AuthenticatedSalesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedSalesRoute,
} as any)
const AuthenticatedSalesCashRoute = AuthenticatedSalesCashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => AuthenticatedSalesRoute,
} as any)
const AuthenticatedInventorySuppliersRoute =
  AuthenticatedInventorySuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedInventoryRoute,
  } as any)
const AuthenticatedInventoryProductsRoute =
  AuthenticatedInventoryProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedInventoryRoute,
  } as any)
const AuthenticatedInventoryMovementsRoute =
  AuthenticatedInventoryMovementsRouteImport.update({
    id: '/movements',
    path: '/movements',
    getParentRoute: () => AuthenticatedInventoryRoute,
  } as any)
const AuthenticatedInventoryCategoriesRoute =
  AuthenticatedInventoryCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedInventoryRoute,
  } as any)
const AuthenticatedFinanceTransactionsRoute =
  AuthenticatedFinanceTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceMethodsRoute =
  AuthenticatedFinanceMethodsRouteImport.update({
    id: '/methods',
    path: '/methods',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceCommissionsRoute =
  AuthenticatedFinanceCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceCategoriesRoute =
  AuthenticatedFinanceCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedFinanceAccountsRoute =
  AuthenticatedFinanceAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)
const AuthenticatedCrmPipelinesRoute =
  AuthenticatedCrmPipelinesRouteImport.update({
    id: '/pipelines',
    path: '/pipelines',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmLeadsRoute = AuthenticatedCrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmBoardRoute = AuthenticatedCrmBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmActivitiesRoute =
  AuthenticatedCrmActivitiesRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedAgendaWaitlistRoute =
  AuthenticatedAgendaWaitlistRouteImport.update({
    id: '/waitlist',
    path: '/waitlist',
    getParentRoute: () => AuthenticatedAgendaRoute,
  } as any)
const AuthenticatedAgendaServicesRoute =
  AuthenticatedAgendaServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAgendaRoute,
  } as any)
const AuthenticatedAgendaSchedulesRoute =
  AuthenticatedAgendaSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => AuthenticatedAgendaRoute,
  } as any)
const AuthenticatedAgendaProfessionalsRoute =
  AuthenticatedAgendaProfessionalsRouteImport.update({
    id: '/professionals',
    path: '/professionals',
    getParentRoute: () => AuthenticatedAgendaRoute,
  } as any)
const AuthenticatedAgendaAppointmentsRoute =
  AuthenticatedAgendaAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedAgendaRoute,
  } as any)
const AuthenticatedSalesCashIdRoute =
  AuthenticatedSalesCashIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSalesCashRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/access-profiles': typeof AuthenticatedAccessProfilesRoute
  '/agenda': typeof AuthenticatedAgendaRouteWithChildren
  '/audit': typeof AuthenticatedAuditRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRouteWithChildren
  '/modules': typeof AuthenticatedModulesRoute
  '/niches': typeof AuthenticatedNichesRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/sales': typeof AuthenticatedSalesRouteWithChildren
  '/sectors': typeof AuthenticatedSectorsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/agenda/appointments': typeof AuthenticatedAgendaAppointmentsRoute
  '/agenda/professionals': typeof AuthenticatedAgendaProfessionalsRoute
  '/agenda/schedules': typeof AuthenticatedAgendaSchedulesRoute
  '/agenda/services': typeof AuthenticatedAgendaServicesRoute
  '/agenda/waitlist': typeof AuthenticatedAgendaWaitlistRoute
  '/crm/activities': typeof AuthenticatedCrmActivitiesRoute
  '/crm/board': typeof AuthenticatedCrmBoardRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/crm/pipelines': typeof AuthenticatedCrmPipelinesRoute
  '/finance/accounts': typeof AuthenticatedFinanceAccountsRoute
  '/finance/categories': typeof AuthenticatedFinanceCategoriesRoute
  '/finance/commissions': typeof AuthenticatedFinanceCommissionsRoute
  '/finance/methods': typeof AuthenticatedFinanceMethodsRoute
  '/finance/transactions': typeof AuthenticatedFinanceTransactionsRoute
  '/inventory/categories': typeof AuthenticatedInventoryCategoriesRoute
  '/inventory/movements': typeof AuthenticatedInventoryMovementsRoute
  '/inventory/products': typeof AuthenticatedInventoryProductsRoute
  '/inventory/suppliers': typeof AuthenticatedInventorySuppliersRoute
  '/sales/cash': typeof AuthenticatedSalesCashRouteWithChildren
  '/sales/new': typeof AuthenticatedSalesNewRoute
  '/sales/orders': typeof AuthenticatedSalesOrdersRoute
  '/agenda/': typeof AuthenticatedAgendaIndexRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/sales/': typeof AuthenticatedSalesIndexRoute
  '/sales/cash/$id': typeof AuthenticatedSalesCashIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/access-profiles': typeof AuthenticatedAccessProfilesRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/modules': typeof AuthenticatedModulesRoute
  '/niches': typeof AuthenticatedNichesRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/sectors': typeof AuthenticatedSectorsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/agenda/appointments': typeof AuthenticatedAgendaAppointmentsRoute
  '/agenda/professionals': typeof AuthenticatedAgendaProfessionalsRoute
  '/agenda/schedules': typeof AuthenticatedAgendaSchedulesRoute
  '/agenda/services': typeof AuthenticatedAgendaServicesRoute
  '/agenda/waitlist': typeof AuthenticatedAgendaWaitlistRoute
  '/crm/activities': typeof AuthenticatedCrmActivitiesRoute
  '/crm/board': typeof AuthenticatedCrmBoardRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/crm/pipelines': typeof AuthenticatedCrmPipelinesRoute
  '/finance/accounts': typeof AuthenticatedFinanceAccountsRoute
  '/finance/categories': typeof AuthenticatedFinanceCategoriesRoute
  '/finance/commissions': typeof AuthenticatedFinanceCommissionsRoute
  '/finance/methods': typeof AuthenticatedFinanceMethodsRoute
  '/finance/transactions': typeof AuthenticatedFinanceTransactionsRoute
  '/inventory/categories': typeof AuthenticatedInventoryCategoriesRoute
  '/inventory/movements': typeof AuthenticatedInventoryMovementsRoute
  '/inventory/products': typeof AuthenticatedInventoryProductsRoute
  '/inventory/suppliers': typeof AuthenticatedInventorySuppliersRoute
  '/sales/cash': typeof AuthenticatedSalesCashRouteWithChildren
  '/sales/new': typeof AuthenticatedSalesNewRoute
  '/sales/orders': typeof AuthenticatedSalesOrdersRoute
  '/agenda': typeof AuthenticatedAgendaIndexRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
  '/sales/cash/$id': typeof AuthenticatedSalesCashIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/access-profiles': typeof AuthenticatedAccessProfilesRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRouteWithChildren
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/_authenticated/inventory': typeof AuthenticatedInventoryRouteWithChildren
  '/_authenticated/modules': typeof AuthenticatedModulesRoute
  '/_authenticated/niches': typeof AuthenticatedNichesRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRouteWithChildren
  '/_authenticated/sectors': typeof AuthenticatedSectorsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/units': typeof AuthenticatedUnitsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/agenda/appointments': typeof AuthenticatedAgendaAppointmentsRoute
  '/_authenticated/agenda/professionals': typeof AuthenticatedAgendaProfessionalsRoute
  '/_authenticated/agenda/schedules': typeof AuthenticatedAgendaSchedulesRoute
  '/_authenticated/agenda/services': typeof AuthenticatedAgendaServicesRoute
  '/_authenticated/agenda/waitlist': typeof AuthenticatedAgendaWaitlistRoute
  '/_authenticated/crm/activities': typeof AuthenticatedCrmActivitiesRoute
  '/_authenticated/crm/board': typeof AuthenticatedCrmBoardRoute
  '/_authenticated/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/_authenticated/crm/pipelines': typeof AuthenticatedCrmPipelinesRoute
  '/_authenticated/finance/accounts': typeof AuthenticatedFinanceAccountsRoute
  '/_authenticated/finance/categories': typeof AuthenticatedFinanceCategoriesRoute
  '/_authenticated/finance/commissions': typeof AuthenticatedFinanceCommissionsRoute
  '/_authenticated/finance/methods': typeof AuthenticatedFinanceMethodsRoute
  '/_authenticated/finance/transactions': typeof AuthenticatedFinanceTransactionsRoute
  '/_authenticated/inventory/categories': typeof AuthenticatedInventoryCategoriesRoute
  '/_authenticated/inventory/movements': typeof AuthenticatedInventoryMovementsRoute
  '/_authenticated/inventory/products': typeof AuthenticatedInventoryProductsRoute
  '/_authenticated/inventory/suppliers': typeof AuthenticatedInventorySuppliersRoute
  '/_authenticated/sales/cash': typeof AuthenticatedSalesCashRouteWithChildren
  '/_authenticated/sales/new': typeof AuthenticatedSalesNewRoute
  '/_authenticated/sales/orders': typeof AuthenticatedSalesOrdersRoute
  '/_authenticated/agenda/': typeof AuthenticatedAgendaIndexRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
  '/_authenticated/sales/cash/$id': typeof AuthenticatedSalesCashIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/access-profiles'
    | '/agenda'
    | '/audit'
    | '/companies'
    | '/crm'
    | '/dashboard'
    | '/finance'
    | '/inventory'
    | '/modules'
    | '/niches'
    | '/permissions'
    | '/sales'
    | '/sectors'
    | '/settings'
    | '/units'
    | '/users'
    | '/agenda/appointments'
    | '/agenda/professionals'
    | '/agenda/schedules'
    | '/agenda/services'
    | '/agenda/waitlist'
    | '/crm/activities'
    | '/crm/board'
    | '/crm/leads'
    | '/crm/pipelines'
    | '/finance/accounts'
    | '/finance/categories'
    | '/finance/commissions'
    | '/finance/methods'
    | '/finance/transactions'
    | '/inventory/categories'
    | '/inventory/movements'
    | '/inventory/products'
    | '/inventory/suppliers'
    | '/sales/cash'
    | '/sales/new'
    | '/sales/orders'
    | '/agenda/'
    | '/crm/'
    | '/finance/'
    | '/inventory/'
    | '/sales/'
    | '/sales/cash/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/access-profiles'
    | '/audit'
    | '/companies'
    | '/dashboard'
    | '/modules'
    | '/niches'
    | '/permissions'
    | '/sectors'
    | '/settings'
    | '/units'
    | '/users'
    | '/agenda/appointments'
    | '/agenda/professionals'
    | '/agenda/schedules'
    | '/agenda/services'
    | '/agenda/waitlist'
    | '/crm/activities'
    | '/crm/board'
    | '/crm/leads'
    | '/crm/pipelines'
    | '/finance/accounts'
    | '/finance/categories'
    | '/finance/commissions'
    | '/finance/methods'
    | '/finance/transactions'
    | '/inventory/categories'
    | '/inventory/movements'
    | '/inventory/products'
    | '/inventory/suppliers'
    | '/sales/cash'
    | '/sales/new'
    | '/sales/orders'
    | '/agenda'
    | '/crm'
    | '/finance'
    | '/inventory'
    | '/sales'
    | '/sales/cash/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/access-profiles'
    | '/_authenticated/agenda'
    | '/_authenticated/audit'
    | '/_authenticated/companies'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/inventory'
    | '/_authenticated/modules'
    | '/_authenticated/niches'
    | '/_authenticated/permissions'
    | '/_authenticated/sales'
    | '/_authenticated/sectors'
    | '/_authenticated/settings'
    | '/_authenticated/units'
    | '/_authenticated/users'
    | '/_authenticated/agenda/appointments'
    | '/_authenticated/agenda/professionals'
    | '/_authenticated/agenda/schedules'
    | '/_authenticated/agenda/services'
    | '/_authenticated/agenda/waitlist'
    | '/_authenticated/crm/activities'
    | '/_authenticated/crm/board'
    | '/_authenticated/crm/leads'
    | '/_authenticated/crm/pipelines'
    | '/_authenticated/finance/accounts'
    | '/_authenticated/finance/categories'
    | '/_authenticated/finance/commissions'
    | '/_authenticated/finance/methods'
    | '/_authenticated/finance/transactions'
    | '/_authenticated/inventory/categories'
    | '/_authenticated/inventory/movements'
    | '/_authenticated/inventory/products'
    | '/_authenticated/inventory/suppliers'
    | '/_authenticated/sales/cash'
    | '/_authenticated/sales/new'
    | '/_authenticated/sales/orders'
    | '/_authenticated/agenda/'
    | '/_authenticated/crm/'
    | '/_authenticated/finance/'
    | '/_authenticated/inventory/'
    | '/_authenticated/sales/'
    | '/_authenticated/sales/cash/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/units': {
      id: '/_authenticated/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedUnitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sectors': {
      id: '/_authenticated/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof AuthenticatedSectorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/niches': {
      id: '/_authenticated/niches'
      path: '/niches'
      fullPath: '/niches'
      preLoaderRoute: typeof AuthenticatedNichesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modules': {
      id: '/_authenticated/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AuthenticatedModulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access-profiles': {
      id: '/_authenticated/access-profiles'
      path: '/access-profiles'
      fullPath: '/access-profiles'
      preLoaderRoute: typeof AuthenticatedAccessProfilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedSalesRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedInventoryRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/agenda/': {
      id: '/_authenticated/agenda/'
      path: '/'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AuthenticatedAgendaIndexRouteImport
      parentRoute: typeof AuthenticatedAgendaRoute
    }
    '/_authenticated/sales/orders': {
      id: '/_authenticated/sales/orders'
      path: '/orders'
      fullPath: '/sales/orders'
      preLoaderRoute: typeof AuthenticatedSalesOrdersRouteImport
      parentRoute: typeof AuthenticatedSalesRoute
    }
    '/_authenticated/sales/new': {
      id: '/_authenticated/sales/new'
      path: '/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof AuthenticatedSalesNewRouteImport
      parentRoute: typeof AuthenticatedSalesRoute
    }
    '/_authenticated/sales/cash': {
      id: '/_authenticated/sales/cash'
      path: '/cash'
      fullPath: '/sales/cash'
      preLoaderRoute: typeof AuthenticatedSalesCashRouteImport
      parentRoute: typeof AuthenticatedSalesRoute
    }
    '/_authenticated/inventory/suppliers': {
      id: '/_authenticated/inventory/suppliers'
      path: '/suppliers'
      fullPath: '/inventory/suppliers'
      preLoaderRoute: typeof AuthenticatedInventorySuppliersRouteImport
      parentRoute: typeof AuthenticatedInventoryRoute
    }
    '/_authenticated/inventory/products': {
      id: '/_authenticated/inventory/products'
      path: '/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof AuthenticatedInventoryProductsRouteImport
      parentRoute: typeof AuthenticatedInventoryRoute
    }
    '/_authenticated/inventory/movements': {
      id: '/_authenticated/inventory/movements'
      path: '/movements'
      fullPath: '/inventory/movements'
      preLoaderRoute: typeof AuthenticatedInventoryMovementsRouteImport
      parentRoute: typeof AuthenticatedInventoryRoute
    }
    '/_authenticated/inventory/categories': {
      id: '/_authenticated/inventory/categories'
      path: '/categories'
      fullPath: '/inventory/categories'
      preLoaderRoute: typeof AuthenticatedInventoryCategoriesRouteImport
      parentRoute: typeof AuthenticatedInventoryRoute
    }
    '/_authenticated/finance/transactions': {
      id: '/_authenticated/finance/transactions'
      path: '/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof AuthenticatedFinanceTransactionsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/methods': {
      id: '/_authenticated/finance/methods'
      path: '/methods'
      fullPath: '/finance/methods'
      preLoaderRoute: typeof AuthenticatedFinanceMethodsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/commissions': {
      id: '/_authenticated/finance/commissions'
      path: '/commissions'
      fullPath: '/finance/commissions'
      preLoaderRoute: typeof AuthenticatedFinanceCommissionsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/categories': {
      id: '/_authenticated/finance/categories'
      path: '/categories'
      fullPath: '/finance/categories'
      preLoaderRoute: typeof AuthenticatedFinanceCategoriesRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/finance/accounts': {
      id: '/_authenticated/finance/accounts'
      path: '/accounts'
      fullPath: '/finance/accounts'
      preLoaderRoute: typeof AuthenticatedFinanceAccountsRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
    '/_authenticated/crm/pipelines': {
      id: '/_authenticated/crm/pipelines'
      path: '/pipelines'
      fullPath: '/crm/pipelines'
      preLoaderRoute: typeof AuthenticatedCrmPipelinesRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/leads': {
      id: '/_authenticated/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AuthenticatedCrmLeadsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/board': {
      id: '/_authenticated/crm/board'
      path: '/board'
      fullPath: '/crm/board'
      preLoaderRoute: typeof AuthenticatedCrmBoardRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/activities': {
      id: '/_authenticated/crm/activities'
      path: '/activities'
      fullPath: '/crm/activities'
      preLoaderRoute: typeof AuthenticatedCrmActivitiesRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/agenda/waitlist': {
      id: '/_authenticated/agenda/waitlist'
      path: '/waitlist'
      fullPath: '/agenda/waitlist'
      preLoaderRoute: typeof AuthenticatedAgendaWaitlistRouteImport
      parentRoute: typeof AuthenticatedAgendaRoute
    }
    '/_authenticated/agenda/services': {
      id: '/_authenticated/agenda/services'
      path: '/services'
      fullPath: '/agenda/services'
      preLoaderRoute: typeof AuthenticatedAgendaServicesRouteImport
      parentRoute: typeof AuthenticatedAgendaRoute
    }
    '/_authenticated/agenda/schedules': {
      id: '/_authenticated/agenda/schedules'
      path: '/schedules'
      fullPath: '/agenda/schedules'
      preLoaderRoute: typeof AuthenticatedAgendaSchedulesRouteImport
      parentRoute: typeof AuthenticatedAgendaRoute
    }
    '/_authenticated/agenda/professionals': {
      id: '/_authenticated/agenda/professionals'
      path: '/professionals'
      fullPath: '/agenda/professionals'
      preLoaderRoute: typeof AuthenticatedAgendaProfessionalsRouteImport
      parentRoute: typeof AuthenticatedAgendaRoute
    }
    '/_authenticated/agenda/appointments': {
      id: '/_authenticated/agenda/appointments'
      path: '/appointments'
      fullPath: '/agenda/appointments'
      preLoaderRoute: typeof AuthenticatedAgendaAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAgendaRoute
    }
    '/_authenticated/sales/cash/$id': {
      id: '/_authenticated/sales/cash/$id'
      path: '/$id'
      fullPath: '/sales/cash/$id'
      preLoaderRoute: typeof AuthenticatedSalesCashIdRouteImport
      parentRoute: typeof AuthenticatedSalesCashRoute
    }
  }
}

interface AuthenticatedAgendaRouteChildren {
  AuthenticatedAgendaAppointmentsRoute: typeof AuthenticatedAgendaAppointmentsRoute
  AuthenticatedAgendaProfessionalsRoute: typeof AuthenticatedAgendaProfessionalsRoute
  AuthenticatedAgendaSchedulesRoute: typeof AuthenticatedAgendaSchedulesRoute
  AuthenticatedAgendaServicesRoute: typeof AuthenticatedAgendaServicesRoute
  AuthenticatedAgendaWaitlistRoute: typeof AuthenticatedAgendaWaitlistRoute
  AuthenticatedAgendaIndexRoute: typeof AuthenticatedAgendaIndexRoute
}

const AuthenticatedAgendaRouteChildren: AuthenticatedAgendaRouteChildren = {
  AuthenticatedAgendaAppointmentsRoute: AuthenticatedAgendaAppointmentsRoute,
  AuthenticatedAgendaProfessionalsRoute: AuthenticatedAgendaProfessionalsRoute,
  AuthenticatedAgendaSchedulesRoute: AuthenticatedAgendaSchedulesRoute,
  AuthenticatedAgendaServicesRoute: AuthenticatedAgendaServicesRoute,
  AuthenticatedAgendaWaitlistRoute: AuthenticatedAgendaWaitlistRoute,
  AuthenticatedAgendaIndexRoute: AuthenticatedAgendaIndexRoute,
}

const AuthenticatedAgendaRouteWithChildren =
  AuthenticatedAgendaRoute._addFileChildren(AuthenticatedAgendaRouteChildren)

interface AuthenticatedCrmRouteChildren {
  AuthenticatedCrmActivitiesRoute: typeof AuthenticatedCrmActivitiesRoute
  AuthenticatedCrmBoardRoute: typeof AuthenticatedCrmBoardRoute
  AuthenticatedCrmLeadsRoute: typeof AuthenticatedCrmLeadsRoute
  AuthenticatedCrmPipelinesRoute: typeof AuthenticatedCrmPipelinesRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
}

const AuthenticatedCrmRouteChildren: AuthenticatedCrmRouteChildren = {
  AuthenticatedCrmActivitiesRoute: AuthenticatedCrmActivitiesRoute,
  AuthenticatedCrmBoardRoute: AuthenticatedCrmBoardRoute,
  AuthenticatedCrmLeadsRoute: AuthenticatedCrmLeadsRoute,
  AuthenticatedCrmPipelinesRoute: AuthenticatedCrmPipelinesRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
}

const AuthenticatedCrmRouteWithChildren =
  AuthenticatedCrmRoute._addFileChildren(AuthenticatedCrmRouteChildren)

interface AuthenticatedFinanceRouteChildren {
  AuthenticatedFinanceAccountsRoute: typeof AuthenticatedFinanceAccountsRoute
  AuthenticatedFinanceCategoriesRoute: typeof AuthenticatedFinanceCategoriesRoute
  AuthenticatedFinanceCommissionsRoute: typeof AuthenticatedFinanceCommissionsRoute
  AuthenticatedFinanceMethodsRoute: typeof AuthenticatedFinanceMethodsRoute
  AuthenticatedFinanceTransactionsRoute: typeof AuthenticatedFinanceTransactionsRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
}

const AuthenticatedFinanceRouteChildren: AuthenticatedFinanceRouteChildren = {
  AuthenticatedFinanceAccountsRoute: AuthenticatedFinanceAccountsRoute,
  AuthenticatedFinanceCategoriesRoute: AuthenticatedFinanceCategoriesRoute,
  AuthenticatedFinanceCommissionsRoute: AuthenticatedFinanceCommissionsRoute,
  AuthenticatedFinanceMethodsRoute: AuthenticatedFinanceMethodsRoute,
  AuthenticatedFinanceTransactionsRoute: AuthenticatedFinanceTransactionsRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
}

const AuthenticatedFinanceRouteWithChildren =
  AuthenticatedFinanceRoute._addFileChildren(AuthenticatedFinanceRouteChildren)

interface AuthenticatedInventoryRouteChildren {
  AuthenticatedInventoryCategoriesRoute: typeof AuthenticatedInventoryCategoriesRoute
  AuthenticatedInventoryMovementsRoute: typeof AuthenticatedInventoryMovementsRoute
  AuthenticatedInventoryProductsRoute: typeof AuthenticatedInventoryProductsRoute
  AuthenticatedInventorySuppliersRoute: typeof AuthenticatedInventorySuppliersRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
}

const AuthenticatedInventoryRouteChildren: AuthenticatedInventoryRouteChildren =
  {
    AuthenticatedInventoryCategoriesRoute:
      AuthenticatedInventoryCategoriesRoute,
    AuthenticatedInventoryMovementsRoute: AuthenticatedInventoryMovementsRoute,
    AuthenticatedInventoryProductsRoute: AuthenticatedInventoryProductsRoute,
    AuthenticatedInventorySuppliersRoute: AuthenticatedInventorySuppliersRoute,
    AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  }

const AuthenticatedInventoryRouteWithChildren =
  AuthenticatedInventoryRoute._addFileChildren(
    AuthenticatedInventoryRouteChildren,
  )

interface AuthenticatedSalesCashRouteChildren {
  AuthenticatedSalesCashIdRoute: typeof AuthenticatedSalesCashIdRoute
}

const AuthenticatedSalesCashRouteChildren: AuthenticatedSalesCashRouteChildren =
  {
    AuthenticatedSalesCashIdRoute: AuthenticatedSalesCashIdRoute,
  }

const AuthenticatedSalesCashRouteWithChildren =
  AuthenticatedSalesCashRoute._addFileChildren(
    AuthenticatedSalesCashRouteChildren,
  )

interface AuthenticatedSalesRouteChildren {
  AuthenticatedSalesCashRoute: typeof AuthenticatedSalesCashRouteWithChildren
  AuthenticatedSalesNewRoute: typeof AuthenticatedSalesNewRoute
  AuthenticatedSalesOrdersRoute: typeof AuthenticatedSalesOrdersRoute
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
}

const AuthenticatedSalesRouteChildren: AuthenticatedSalesRouteChildren = {
  AuthenticatedSalesCashRoute: AuthenticatedSalesCashRouteWithChildren,
  AuthenticatedSalesNewRoute: AuthenticatedSalesNewRoute,
  AuthenticatedSalesOrdersRoute: AuthenticatedSalesOrdersRoute,
  AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
}

const AuthenticatedSalesRouteWithChildren =
  AuthenticatedSalesRoute._addFileChildren(AuthenticatedSalesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessProfilesRoute: typeof AuthenticatedAccessProfilesRoute
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRouteWithChildren
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRouteWithChildren
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRouteWithChildren
  AuthenticatedModulesRoute: typeof AuthenticatedModulesRoute
  AuthenticatedNichesRoute: typeof AuthenticatedNichesRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRouteWithChildren
  AuthenticatedSectorsRoute: typeof AuthenticatedSectorsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUnitsRoute: typeof AuthenticatedUnitsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessProfilesRoute: AuthenticatedAccessProfilesRoute,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRouteWithChildren,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRouteWithChildren,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRouteWithChildren,
  AuthenticatedModulesRoute: AuthenticatedModulesRoute,
  AuthenticatedNichesRoute: AuthenticatedNichesRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRouteWithChildren,
  AuthenticatedSectorsRoute: AuthenticatedSectorsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUnitsRoute: AuthenticatedUnitsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
