create or replace function public.marocas_company_id()
returns uuid language sql stable security definer set search_path=public as $$
  select company_id from public.communication_tenants
  where slug='marocas' and active=true and deleted_at is null and company_id is not null
  limit 1
$$;
revoke all on function public.marocas_company_id() from public,anon,authenticated;
grant execute on function public.marocas_company_id() to service_role;

create table if not exists public.marocas_owners (
 id uuid primary key default gen_random_uuid(), company_id uuid not null default public.marocas_company_id() references public.companies(id), user_id uuid references auth.users(id) on delete set null,
 full_name text not null, email text, phone text, document text, pix_key text, bank_info jsonb not null default '{}', notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.marocas_apartments (
 id uuid primary key default gen_random_uuid(), company_id uuid not null default public.marocas_company_id() references public.companies(id), owner_id uuid not null references public.marocas_owners(id) on delete cascade,
 code text not null unique, title text not null, building text, address text, city text, state text check(state is null or state ~ '^[A-Z]{2}$'), zip text, municipality_ibge text check(municipality_ibge is null or municipality_ibge ~ '^[0-9]{7}$'), bedrooms int default 1, bathrooms int default 1, capacity int default 2, area_m2 numeric(8,2), cover_photo_url text, photos jsonb not null default '[]', amenities jsonb not null default '[]', status text not null default 'disponivel' check(status=any(array['disponivel','ocupado','manutencao','bloqueado'])), daily_rate numeric(10,2), marocas_commission_percent numeric(5,2) default 20, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.marocas_professionals (
 id uuid primary key default gen_random_uuid(), company_id uuid not null default public.marocas_company_id() references public.companies(id), user_id uuid references auth.users(id) on delete set null,
 full_name text not null, role text not null check(role=any(array['camareira','lavanderia','manutencao','vistoriador','gerente'])), phone text,email text,document text,pix_key text,hourly_rate numeric(10,2),per_service_rate numeric(10,2),rating numeric(3,2) default 5,active boolean not null default true,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.marocas_services (
 id uuid primary key default gen_random_uuid(), company_id uuid not null default public.marocas_company_id() references public.companies(id), apartment_id uuid not null references public.marocas_apartments(id) on delete cascade, professional_id uuid references public.marocas_professionals(id) on delete set null,
 service_type text not null check(service_type=any(array['limpeza','reposicao','enxoval','lavanderia','manutencao','vistoria','check_in','check_out'])), status text not null default 'agendado' check(status=any(array['agendado','em_andamento','concluido','cancelado','atrasado'])), priority text default 'media' check(priority=any(array['baixa','media','alta','urgente'])), scheduled_for timestamptz not null,started_at timestamptz,completed_at timestamptz,checklist jsonb not null default '[]',photos_before jsonb not null default '[]',photos_after jsonb not null default '[]',cost numeric(10,2) default 0,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.marocas_supplies (
 id uuid primary key default gen_random_uuid(), company_id uuid not null default public.marocas_company_id() references public.companies(id), apartment_id uuid references public.marocas_apartments(id) on delete cascade,category text not null,item_name text not null,current_qty int not null default 0,min_qty int not null default 0,unit text default 'un',unit_cost numeric(10,2),last_restocked_at timestamptz,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.marocas_maintenance_requests (
 id uuid primary key default gen_random_uuid(), company_id uuid not null default public.marocas_company_id() references public.companies(id), apartment_id uuid not null references public.marocas_apartments(id) on delete cascade,opened_by uuid references auth.users(id) on delete set null,title text not null,description text,category text,priority text not null default 'media' check(priority=any(array['baixa','media','alta','urgente'])),status text not null default 'aberto',photos jsonb not null default '[]',approved_quote_id uuid,resolved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.marocas_maintenance_quotes (
 id uuid primary key default gen_random_uuid(), company_id uuid not null default public.marocas_company_id() references public.companies(id), request_id uuid not null references public.marocas_maintenance_requests(id) on delete cascade,professional_id uuid not null references public.marocas_professionals(id) on delete cascade,amount numeric(10,2) not null,estimated_hours numeric(6,2),notes text,status text not null default 'enviado',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.marocas_owner_statements (
 id uuid primary key default gen_random_uuid(), company_id uuid not null default public.marocas_company_id() references public.companies(id),owner_id uuid not null references public.marocas_owners(id) on delete cascade,apartment_id uuid not null references public.marocas_apartments(id) on delete cascade,reference_month date not null,gross_revenue numeric(12,2) not null default 0,marocas_fee numeric(12,2) not null default 0,expenses numeric(12,2) not null default 0,net_payout numeric(12,2) not null default 0,status text not null default 'previsto' check(status=any(array['previsto','liberado','pago','contestado'])),pix_txid text,paid_at timestamptz,breakdown jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.marocas_report_schedules (
 id uuid primary key default gen_random_uuid(),company_id uuid not null default public.marocas_company_id() references public.companies(id),user_id uuid not null references auth.users(id) on delete cascade,period text not null check(period in('dia','semana')),hour smallint not null check(hour between 0 and 23),weekday smallint check(weekday is null or weekday between 0 and 6),channels text[] not null default array['cockpit']::text[],enabled boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,period));
create table if not exists public.marocas_report_runs (
 id uuid primary key default gen_random_uuid(),company_id uuid not null default public.marocas_company_id() references public.companies(id),user_id uuid references auth.users(id) on delete set null,schedule_id uuid references public.marocas_report_schedules(id) on delete set null,period text not null check(period in('dia','semana')),range_from timestamptz not null,range_to timestamptz not null,channels text[] not null default '{}',status text not null check(status in('success','error','partial')),total int not null default 0,done int not null default 0,late int not null default 0,error text,triggered_by text not null default 'manual',created_at timestamptz not null default now());

create or replace function public.marocas_touch_updated_at() returns trigger language plpgsql set search_path=public as $$ begin new.updated_at=now(); return new; end $$;
do $$ declare t text; begin foreach t in array array['marocas_owners','marocas_apartments','marocas_professionals','marocas_services','marocas_supplies','marocas_maintenance_requests','marocas_maintenance_quotes','marocas_owner_statements','marocas_report_schedules'] loop execute format('drop trigger if exists trg_%I_touch on public.%I',t,t); execute format('create trigger trg_%I_touch before update on public.%I for each row execute function public.marocas_touch_updated_at()',t,t); end loop; end $$;
do $$ declare t text; begin foreach t in array array['marocas_owners','marocas_apartments','marocas_professionals','marocas_services','marocas_supplies','marocas_maintenance_requests','marocas_maintenance_quotes','marocas_owner_statements','marocas_report_schedules','marocas_report_runs'] loop execute format('alter table public.%I enable row level security',t); execute format('grant select,insert,update,delete on public.%I to authenticated',t); execute format('grant all on public.%I to service_role',t); execute format('drop policy if exists marocas_company_access on public.%I',t); execute format('create policy marocas_company_access on public.%I for all to authenticated using (public.user_belongs_to_company(auth.uid(),company_id) or public.is_impulsionando_staff(auth.uid())) with check (public.user_belongs_to_company(auth.uid(),company_id) or public.is_impulsionando_staff(auth.uid()))',t); end loop; end $$;
create index if not exists marocas_apartments_company_idx on public.marocas_apartments(company_id);
create index if not exists marocas_services_company_schedule_idx on public.marocas_services(company_id,scheduled_for);
create index if not exists marocas_maintenance_company_status_idx on public.marocas_maintenance_requests(company_id,status);
create index if not exists marocas_statements_company_month_idx on public.marocas_owner_statements(company_id,reference_month);
comment on function public.marocas_company_id() is 'Resolve a empresa Marocas pelo Core communication_tenants; evita IDs fixos em código e migrações.';