begin;
drop policy if exists members_write on public.communication_tenant_members;
create policy members_insert on public.communication_tenant_members for insert to authenticated with check (private.is_tenant_member(tenant_id,array['OWNER','ADMIN']));
create policy members_update on public.communication_tenant_members for update to authenticated using (private.is_tenant_member(tenant_id,array['OWNER','ADMIN'])) with check (private.is_tenant_member(tenant_id,array['OWNER','ADMIN']));
create policy members_delete on public.communication_tenant_members for delete to authenticated using (private.is_tenant_member(tenant_id,array['OWNER','ADMIN']));
create index if not exists communication_tenants_parent_idx on public.communication_tenants(parent_id);
create index if not exists communication_brands_tenant_idx on public.communication_brands(tenant_id);
create index if not exists communication_senders_tenant_idx on public.communication_senders(tenant_id);
create index if not exists communication_senders_brand_idx on public.communication_senders(brand_id);
create index if not exists communication_senders_provider_idx on public.communication_senders(provider_account_id);
create index if not exists communication_agents_tenant_idx on public.communication_agents(tenant_id);
create index if not exists communication_agents_brand_idx on public.communication_agents(brand_id);
create index if not exists communication_recipients_tenant_idx on public.communication_recipients(tenant_id);
create index if not exists communication_recipients_user_idx on public.communication_recipients(user_id);
create index if not exists communication_templates_tenant_idx on public.communication_templates(tenant_id);
create index if not exists communication_templates_brand_idx on public.communication_templates(brand_id);
create index if not exists communication_templates_parent_idx on public.communication_templates(parent_template_id);
create index if not exists communication_templates_created_by_idx on public.communication_templates(created_by);
create index if not exists communication_template_versions_tenant_idx on public.communication_template_versions(tenant_id);
create index if not exists communication_template_versions_template_idx on public.communication_template_versions(template_id);
create index if not exists communication_template_versions_created_by_idx on public.communication_template_versions(created_by);
create index if not exists communication_template_versions_approved_by_idx on public.communication_template_versions(approved_by);
create index if not exists communication_template_blocks_tenant_idx on public.communication_template_blocks(tenant_id);
create index if not exists communication_template_blocks_brand_idx on public.communication_template_blocks(brand_id);
create index if not exists communication_events_brand_idx on public.communication_events(brand_id);
create index if not exists communication_events_recipient_idx on public.communication_events(recipient_id);
create index if not exists communication_events_agent_idx on public.communication_events(agent_id);
create index if not exists communication_messages_tenant_idx on public.communication_messages(tenant_id);
create index if not exists communication_messages_recipient_idx on public.communication_messages(recipient_id);
create index if not exists communication_messages_template_version_idx on public.communication_messages(template_version_id);
create index if not exists communication_messages_brand_idx on public.communication_messages(brand_id);
create index if not exists communication_messages_sender_idx on public.communication_messages(sender_id);
create index if not exists communication_messages_agent_idx on public.communication_messages(agent_id);
create index if not exists communication_preferences_recipient_idx on public.communication_preferences(recipient_id);
create index if not exists communication_consents_tenant_idx on public.communication_consents(tenant_id);
create index if not exists communication_consents_recipient_idx on public.communication_consents(recipient_id);
create index if not exists communication_suppressions_recipient_idx on public.communication_suppressions(recipient_id);
create index if not exists communication_deliveries_tenant_idx on public.communication_deliveries(tenant_id);
create index if not exists communication_interactions_tenant_idx on public.communication_interactions(tenant_id);
create index if not exists communication_failures_message_idx on public.communication_failures(message_id);
create index if not exists communication_failures_event_idx on public.communication_failures(event_id);
create index if not exists communication_retries_tenant_idx on public.communication_retries(tenant_id);
create index if not exists communication_provider_events_tenant_idx on public.communication_provider_events(tenant_id);
create index if not exists communication_workflow_runs_tenant_idx on public.communication_workflow_runs(tenant_id);
create index if not exists communication_workflow_runs_automation_idx on public.communication_workflow_runs(automation_id);
create index if not exists communication_workflow_runs_event_idx on public.communication_workflow_runs(event_id);
commit;
