create table if not exists public.riomed_pos_terminals (
 id uuid primary key default gen_random_uuid(), company_id uuid not null default public.riomed_company_id() references public.companies(id) on delete cascade,
 code text not null,name text not null,location text,currency text not null default 'BOB',active boolean not null default true,
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,code));
create table if not exists public.riomed_pos_sessions (
 id uuid primary key default gen_random_uuid(),company_id uuid not null default public.riomed_company_id() references public.companies(id) on delete cascade,
 terminal_id uuid not null references public.riomed_pos_terminals(id) on delete cascade,opened_by uuid not null references auth.users(id),opened_at timestamptz not null default now(),opening_amount numeric(14,2) not null default 0,
 closed_at timestamptz,closed_by uuid references auth.users(id),closing_amount numeric(14,2),expected_amount numeric(14,2),difference numeric(14,2),status text not null default 'open' check(status in('open','closed')),notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists riomed_pos_one_open_session_per_terminal on public.riomed_pos_sessions(terminal_id) where status='open';
create table if not exists public.riomed_pos_sales (
 id uuid primary key default gen_random_uuid(),company_id uuid not null default public.riomed_company_id() references public.companies(id) on delete cascade,
 session_id uuid not null references public.riomed_pos_sessions(id) on delete cascade,terminal_id uuid not null references public.riomed_pos_terminals(id),seller_id uuid references auth.users(id),customer_name text,customer_doc text,
 subtotal numeric(14,2) not null default 0,discount numeric(14,2) not null default 0,total numeric(14,2) not null default 0,currency text not null default 'BOB',payment_method text not null default 'cash' check(payment_method in('cash','card','qr','transfer','mixed')),paid_amount numeric(14,2) not null default 0,change_amount numeric(14,2) not null default 0,status text not null default 'completed' check(status in('completed','voided')),fiscal_invoice_id uuid,fiscal_number text,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.riomed_pos_sale_items (
 id uuid primary key default gen_random_uuid(),sale_id uuid not null references public.riomed_pos_sales(id) on delete cascade,product_id uuid references public.riomed_products(id) on delete set null,description text not null,qty numeric(12,3) not null default 1 check(qty>0),unit_price numeric(14,2) not null check(unit_price>=0),total numeric(14,2) not null check(total>=0),created_at timestamptz not null default now());
create table if not exists public.riomed_pos_movements (
 id uuid primary key default gen_random_uuid(),company_id uuid not null default public.riomed_company_id() references public.companies(id) on delete cascade,session_id uuid not null references public.riomed_pos_sessions(id) on delete cascade,kind text not null check(kind in('cash_in','cash_out')),amount numeric(14,2) not null check(amount>0),reason text,created_by uuid references auth.users(id),created_at timestamptz not null default now());

do $$ declare t text; begin foreach t in array array['riomed_pos_terminals','riomed_pos_sessions','riomed_pos_sales','riomed_pos_movements'] loop execute format('alter table public.%I enable row level security',t); execute format('grant select,insert,update,delete on public.%I to authenticated',t); execute format('grant all on public.%I to service_role',t); execute format('drop policy if exists riomed_pos_company_access on public.%I',t); execute format('create policy riomed_pos_company_access on public.%I for all to authenticated using(public.user_belongs_to_company(auth.uid(),company_id) or public.is_impulsionando_staff(auth.uid())) with check(public.user_belongs_to_company(auth.uid(),company_id) or public.is_impulsionando_staff(auth.uid()))',t); end loop; end $$;
alter table public.riomed_pos_sale_items enable row level security; grant select,insert,update,delete on public.riomed_pos_sale_items to authenticated; grant all on public.riomed_pos_sale_items to service_role;
drop policy if exists riomed_pos_items_access on public.riomed_pos_sale_items;
create policy riomed_pos_items_access on public.riomed_pos_sale_items for all to authenticated using(exists(select 1 from public.riomed_pos_sales s where s.id=sale_id and (public.user_belongs_to_company(auth.uid(),s.company_id) or public.is_impulsionando_staff(auth.uid())))) with check(exists(select 1 from public.riomed_pos_sales s where s.id=sale_id and (public.user_belongs_to_company(auth.uid(),s.company_id) or public.is_impulsionando_staff(auth.uid()))));

do $$ declare t text; begin foreach t in array array['riomed_pos_terminals','riomed_pos_sessions','riomed_pos_sales'] loop execute format('drop trigger if exists trg_%I_touch on public.%I',t,t); execute format('create trigger trg_%I_touch before update on public.%I for each row execute function public.riomed_commercial_touch()',t,t); end loop; end $$;
create index if not exists riomed_pos_sessions_company_opened_idx on public.riomed_pos_sessions(company_id,opened_at desc);
create index if not exists riomed_pos_sales_company_created_idx on public.riomed_pos_sales(company_id,created_at desc);
create index if not exists riomed_pos_movements_session_idx on public.riomed_pos_movements(session_id,created_at);