-- Prevent automated test fixtures from ever entering the commercial client lifecycle.
-- These fixture names are generated by regression/security tests with a millisecond timestamp suffix.

create or replace function public.core_is_technical_fixture_name(p_name text)
returns boolean
language sql
immutable
set search_path to 'pg_catalog'
as $$
  select coalesce(p_name,'') ~ '^(Meta [AB]|Signed URL Co|Storage Co [AB]|Cross [AB]) [0-9]{10,}$';
$$;

create or replace function public.core_mark_technical_fixture_demo()
returns trigger
language plpgsql
set search_path to 'pg_catalog','public'
as $$
begin
  if public.core_is_technical_fixture_name(new.name) then
    new.is_demo := true;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_core_mark_technical_fixture_demo on public.companies;
create trigger trg_core_mark_technical_fixture_demo
before insert or update of name
on public.companies
for each row execute function public.core_mark_technical_fixture_demo();

-- Existing fixtures produced by tests before this guard are reclassified and
-- removed from commercial enrollment/subdomain reconciliation.
update public.companies
set is_demo=true,updated_at=now()
where public.core_is_technical_fixture_name(name)
  and coalesce(is_demo,false)=false;

update public.communication_tenants t
set active=false,
    deleted_at=coalesce(t.deleted_at,now()),
    updated_at=now(),
    settings=coalesce(t.settings,'{}'::jsonb)||jsonb_build_object('excluded_reason','automated_test_fixture')
from public.companies c
where t.company_id=c.id and c.is_demo=true and public.core_is_technical_fixture_name(c.name);

delete from public.core_tenant_identity i
using public.companies c
where i.company_id=c.id and c.is_demo=true and public.core_is_technical_fixture_name(c.name);

delete from public.core_client_enrollment e
using public.companies c
where e.company_id=c.id and c.is_demo=true and public.core_is_technical_fixture_name(c.name);

delete from public.core_service_access_state s
using public.companies c
where s.company_id=c.id and c.is_demo=true and public.core_is_technical_fixture_name(c.name);
