-- CHRISMED booking holds reserve both the professional's operational interval and physical resource.
alter table public.chrismed_appointments add column if not exists blocking_ends_at timestamptz;
update public.chrismed_appointments a set blocking_ends_at=a.starts_at+make_interval(mins=>coalesce(o.blocking_duration_minutes,o.duration_minutes)) from public.chrismed_service_offerings o where a.offering_id=o.id and a.blocking_ends_at is null;
alter table public.chrismed_appointments alter column blocking_ends_at set not null;
alter table public.chrismed_appointments drop constraint if exists chrismed_appointments_no_overlap;
alter table public.chrismed_appointments add constraint chrismed_appointments_no_overlap exclude using gist (professional_id with =,tstzrange(starts_at,blocking_ends_at,'[)') with &&) where (status=any(array['held'::text,'pending_payment'::text,'confirmed'::text]));
alter table public.chrismed_appointments drop constraint if exists chrismed_appointments_resource_no_overlap;
alter table public.chrismed_appointments add constraint chrismed_appointments_resource_no_overlap exclude using gist (resource_id with =,tstzrange(starts_at,blocking_ends_at,'[)') with &&) where (resource_id is not null and status=any(array['held'::text,'pending_payment'::text,'confirmed'::text]));

-- The production RPC is intentionally redefined here so the database itself remains the concurrency authority.
create or replace function public.create_chrismed_booking_hold(p_request jsonb)
returns table(appointment_id uuid,hold_token uuid,hold_expires_at timestamptz,amount_cents integer)
language plpgsql security definer set search_path to 'public','auth' as $function$
declare
 v_company constant uuid:='642096b5-a9ff-4521-a82a-c004f6d2e2d2'::uuid; v_offering public.chrismed_service_offerings; v_professional public.agenda_professionals;
 v_starts timestamptz; v_ends timestamptz; v_blocking_ends timestamptz; v_resource uuid; v_name text:=trim(coalesce(p_request->>'patientName','')); v_email text:=lower(trim(coalesce(p_request->>'patientEmail',''))); v_phone text:=nullif(regexp_replace(coalesce(p_request->>'patientPhone',''),'[^0-9+]','','g'),''); v_doc text:=regexp_replace(coalesce(p_request->>'patientDocument',''),'[^0-9]','','g'); v_terms text:=trim(coalesce(p_request->>'termsVersion','')); v_privacy text:=trim(coalesce(p_request->>'privacyVersion','')); v_coupon_code text:=nullif(trim(coalesce(p_request->>'couponCode','')),''); v_created public.chrismed_appointments%rowtype; v_coupon jsonb; v_amount integer; v_intent_hash text; v_min_advance integer; v_hold_seconds integer; v_required_scope text;
begin
 if pg_column_size(p_request)>16384 then raise exception 'request too large'; end if; if char_length(v_name) not between 2 and 160 then raise exception 'valid patient name required'; end if; if v_email !~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then raise exception 'valid patient email required'; end if; if not public.chrismed_is_valid_cpf(v_doc) then raise exception 'valid patient CPF required'; end if; if v_terms='' or v_privacy='' or coalesce((p_request->>'accepted')::boolean,false) is not true then raise exception 'terms and privacy acceptance required'; end if;
 select * into v_offering from public.chrismed_service_offerings where id=(p_request->>'offeringId')::uuid and company_id=v_company and active; if not found then raise exception 'active offering not found'; end if; v_required_scope:=nullif(v_offering.metadata->>'required_schedule_scope','');
 select * into v_professional from public.agenda_professionals where company_id=v_company and (id=nullif(p_request->>'professionalId','')::uuid or (nullif(p_request->>'professionalSlug','') is not null and public_slug=p_request->>'professionalSlug')) and is_active=true and profile_status in ('approved','active'); if not found then raise exception 'active professional not found'; end if;
 v_min_advance:=coalesce((select (value#>>'{}')::integer from public.company_settings where company_id=v_company and key='agenda.min_advance_minutes'),30); v_hold_seconds:=coalesce((select (value#>>'{}')::integer from public.company_settings where company_id=v_company and key='agenda.checkout_hold_seconds'),300); if v_hold_seconds<60 or v_hold_seconds>1800 then v_hold_seconds:=300; end if;
 v_starts:=(p_request->>'startsAt')::timestamptz; v_ends:=v_starts+make_interval(mins=>v_offering.duration_minutes); v_blocking_ends:=v_starts+make_interval(mins=>coalesce(v_offering.blocking_duration_minutes,v_offering.duration_minutes));
 if v_required_scope='presencial_copacabana' then select id into v_resource from public.chrismed_physical_resources where company_id=v_company and slug='copacabana-consultorio' and active limit 1; elsif nullif(p_request->>'resourceId','') is not null then select id into v_resource from public.chrismed_physical_resources where id=(p_request->>'resourceId')::uuid and company_id=v_company and active; end if;
 if v_starts<now()+make_interval(mins=>v_min_advance) or v_starts>now()+interval '120 days' then raise exception 'appointment start outside allowed window'; end if;
 if not exists(select 1 from public.agenda_schedules s where s.company_id=v_company and s.professional_id=v_professional.id and s.is_active and s.weekday=extract(dow from v_starts at time zone 'America/Sao_Paulo')::smallint and (v_starts at time zone 'America/Sao_Paulo')::time>=s.start_time and (v_blocking_ends at time zone 'America/Sao_Paulo')::time<=s.end_time and (v_required_scope is null or v_required_scope=any(s.allowed_scopes))) then raise exception 'slot is outside offering schedule scope'; end if;
 if exists(select 1 from public.agenda_blocks b where b.company_id=v_company and (b.professional_id=v_professional.id or b.professional_id is null) and tstzrange(b.starts_at,b.ends_at,'[)')&&tstzrange(v_starts,v_blocking_ends,'[)')) then raise exception 'slot is blocked'; end if;
 update public.chrismed_appointments a set status='expired',updated_at=now() where a.status in ('held','pending_payment') and a.hold_expires_at<=now(); perform pg_advisory_xact_lock(hashtextextended(v_professional.id::text,0)); if v_resource is not null then perform pg_advisory_xact_lock(hashtextextended(v_resource::text,0)); end if;
 v_intent_hash:=public.chrismed_coupon_cpf_hash(v_doc); if v_coupon_code is null then select coupon_code into v_coupon_code from public.chrismed_coupon_checkout_intents where cpf_hash=v_intent_hash and expires_at>now() limit 1; end if;
 insert into public.chrismed_appointments(company_id,professional_id,offering_id,patient_user_id,patient_name,patient_email,patient_phone,patient_document_last4,starts_at,ends_at,blocking_ends_at,resource_id,hold_expires_at,terms_version,privacy_version,metadata) values(v_company,v_professional.id,v_offering.id,auth.uid(),v_name,v_email,v_phone,right(v_doc,4),v_starts,v_ends,v_blocking_ends,v_resource,now()+make_interval(secs=>v_hold_seconds),v_terms,v_privacy,jsonb_build_object('requestId',nullif(p_request->>'requestId',''),'locale',coalesce(p_request->>'locale','pt-BR'),'checkout_hold_seconds',v_hold_seconds,'schedule_scope',v_required_scope,'blocking_duration_minutes',coalesce(v_offering.blocking_duration_minutes,v_offering.duration_minutes))) returning * into v_created;
 v_amount:=v_offering.price_cents; if v_coupon_code is not null then v_coupon:=public.chrismed_reserve_coupon_for_appointment(v_created.id,v_coupon_code,v_doc); delete from public.chrismed_coupon_checkout_intents where cpf_hash=v_intent_hash; if coalesce((v_coupon->>'valid')::boolean,false) is not true then delete from public.chrismed_appointments where id=v_created.id; raise exception 'coupon_invalid:%',coalesce(v_coupon->>'reason','invalid'); end if; v_amount:=(v_coupon->>'net_amount_cents')::integer; else update public.chrismed_appointments set metadata=coalesce(metadata,'{}'::jsonb)||jsonb_build_object('checkout_amount_cents',v_offering.price_cents) where id=v_created.id; end if; delete from public.chrismed_coupon_checkout_intents where expires_at<=now(); return query select v_created.id,v_created.hold_token,v_created.hold_expires_at,v_amount;
exception when exclusion_violation or unique_violation then raise exception 'slot is no longer available' using errcode='23P01'; end;
$function$;
revoke all on function public.create_chrismed_booking_hold(jsonb) from public; grant execute on function public.create_chrismed_booking_hold(jsonb) to anon,authenticated,service_role;