// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const CANONICAL_RECOVERY_URL = 'https://impulsionando.com.br/reset-password';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;

  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];

    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Configure as variáveis de ambiente do Supabase na infraestrutura Impulsionando.`;

    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const client = createClient<Database>(
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY,
    {
      auth: {
        storage:
          typeof window !== 'undefined'
            ? localStorage
            : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    }
  );

  // Password recovery is a Core capability, not a tenant-specific feature.
  // All subdomains use one canonical callback so Auth URL allow-listing stays
  // deterministic and a client domain can never break recovery by itself.
  const originalResetPasswordForEmail = client.auth.resetPasswordForEmail.bind(client.auth);
  client.auth.resetPasswordForEmail = (email, options) =>
    originalResetPasswordForEmail(email, {
      ...options,
      redirectTo: CANONICAL_RECOVERY_URL,
    });

  return client;
}

let _supabase:
  | ReturnType<typeof createSupabaseClient>
  | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy(
  {} as ReturnType<typeof createSupabaseClient>,
  {
    get(_, prop, receiver) {
      if (!_supabase) {
        _supabase = createSupabaseClient();
      }

      return Reflect.get(_supabase, prop, receiver);
    },
  }
);
