// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

let runtimeFileEnv: Record<string, string> | undefined;

function readRuntimeFileEnv(): Record<string, string> {
  if (runtimeFileEnv) return runtimeFileEnv;
  runtimeFileEnv = {};
  const fs = process.getBuiltinModule?.('fs') as
    | { readFileSync(path: string, encoding: 'utf8'): string }
    | undefined;
  if (!fs) return runtimeFileEnv;
  for (const path of ['/app/impulsionando-core.env', '/etc/impulsionando-core.env']) {
    try {
      const content = fs.readFileSync(path, 'utf8');
      for (const line of content.split(/\r?\n/)) {
        if (!line || line.startsWith('#')) continue;
        const separator = line.indexOf('=');
        if (separator <= 0) continue;
        runtimeFileEnv[line.slice(0, separator)] = line.slice(separator + 1);
      }
      break;
    } catch {
      // The file is optional when the process already receives environment variables.
    }
  }
  return runtimeFileEnv;
}

function serverEnv(name: string): string | undefined {
  return process.env[name] || readRuntimeFileEnv()[name];
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = serverEnv('SUPABASE_URL');
  const SUPABASE_SERVICE_ROLE_KEY = serverEnv('SUPABASE_SERVICE_ROLE_KEY');

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
