import { ReactNode, useEffect } from "react";
import { Link, Outlet, useLocation, useNavigate } from "@tanstack/react-router";
import { LayoutDashboard, Package, User, LogOut, ShieldCheck, MessageCircle, Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { supabase } from "@/integrations/supabase/client";
import { useColorsDashboard } from "@/lib/colors-account";

const NAV=[{to:"/colors/minha-conta",label:"Painel",icon:LayoutDashboard,exact:true},{to:"/colors/minha-conta/pedidos",label:"Meus pedidos",icon:Package},{to:"/colors/minha-conta/perfil",label:"Perfil",icon:User}] as const;
export default function AccountShell({children}:{children?:ReactNode}){const{pathname}=useLocation();const navigate=useNavigate();const{data,isLoading,error}=useColorsDashboard();useEffect(()=>{if((error as any)?.message==="AUTH_REQUIRED")navigate({to:"/colors/entrar"})},[error,navigate]);const active=(to:string,exact?:boolean)=>exact?pathname===to:pathname===to||pathname.startsWith(to+"/");async function logout(){await supabase.auth.signOut();navigate({to:"/colors/entrar"});}
if(isLoading)return<div className="grid min-h-dvh place-items-center bg-[#050a08] text-white"><Loader2 className="h-7 w-7 animate-spin text-emerald-400"/></div>;
const name=data?.profile?.name?.split(/\s+/)[0]||"cliente";
return<div className="min-h-dvh bg-[#050a08] text-white"><header className="sticky top-0 z-30 border-b border-white/10 bg-[#050a08]/85 backdrop-blur-xl"><div className="container mx-auto flex h-16 max-w-7xl items-center justify-between px-4"><Link to="/colors" className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-emerald-400 to-lime-400 font-black text-black">C</span><span className="text-lg font-black">Colors Saúde</span></Link><div className="flex items-center gap-3"><span className="hidden rounded-full border border-emerald-400/30 bg-emerald-500/10 px-3 py-1 text-xs font-semibold text-emerald-300 sm:inline-flex"><ShieldCheck className="mr-1 h-3 w-3"/>Conta segura</span><span className="hidden text-sm text-white/70 sm:inline">Olá, <strong>{name}</strong></span><button onClick={logout} className="rounded-full border border-white/15 bg-white/5 px-3 py-1.5 text-xs font-semibold text-white/80"><LogOut className="mr-1 inline h-3 w-3"/>Sair</button></div></div></header><div className="container mx-auto grid max-w-7xl gap-8 px-4 py-8 lg:grid-cols-[260px_1fr]"><aside className="lg:sticky lg:top-24 lg:self-start"><nav className="flex gap-2 overflow-x-auto lg:flex-col lg:gap-1">{NAV.map(n=><Link key={n.to} to={n.to} className={cn("inline-flex shrink-0 items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold transition",active(n.to,n.exact)?"bg-gradient-to-r from-emerald-500/20 to-lime-500/10 text-emerald-200 ring-1 ring-emerald-400/30":"text-white/70 hover:bg-white/[0.04] hover:text-white")}><n.icon className="h-4 w-4"/>{n.label}</Link>)}</nav><div className="mt-6 hidden rounded-2xl border border-white/10 bg-white/[0.03] p-4 lg:block"><p className="text-xs font-bold uppercase tracking-widest text-emerald-300">Precisa de ajuda?</p><p className="mt-2 text-sm text-white/70">A Íris usa o mesmo Customer 360° desta conta.</p><Link to="/colors/suporte" className="mt-3 inline-flex items-center gap-2 rounded-full bg-emerald-500 px-3 py-1.5 text-xs font-bold text-black"><MessageCircle className="h-3.5 w-3.5"/>Abrir atendimento</Link></div></aside><main className="min-w-0">{children??<Outlet/>}</main></div></div>}
export function AccountPageHeader({title,description,icon:Icon,action}:{title:string;description?:string;icon?:React.ComponentType<{className?:string}>;action?:ReactNode}){return<div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div className="flex items-start gap-3">{Icon&&<div className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-500/15 text-emerald-300 ring-1 ring-emerald-400/25"><Icon className="h-5 w-5"/></div>}<div><h1 className="text-2xl font-black sm:text-3xl">{title}</h1>{description&&<p className="mt-1 text-sm text-white/60">{description}</p>}</div></div>{action}</div>}
export function OrderStatusBadge({status}:{status:string}){const map:Record<string,[string,string]>={draft:["Aguardando confirmação","bg-amber-500/15 text-amber-300 ring-amber-400/30"],confirmed:["Pagamento aprovado","bg-sky-500/15 text-sky-300 ring-sky-400/30"],processing:["Em processamento","bg-violet-500/15 text-violet-300 ring-violet-400/30"],fulfilled:["Concluído","bg-emerald-500/15 text-emerald-300 ring-emerald-400/30"],cancelled:["Cancelado","bg-red-500/15 text-red-300 ring-red-400/30"],refunded:["Reembolsado","bg-red-500/15 text-red-300 ring-red-400/30"],shipped:["Enviado","bg-indigo-500/15 text-indigo-300 ring-indigo-400/30"],delivered:["Entregue","bg-emerald-500/15 text-emerald-300 ring-emerald-400/30"]};const[label,cls]=map[status]??[status||"Status indisponível","bg-white/10 text-white/70 ring-white/15"];return<span className={cn("inline-flex items-center rounded-full px-2.5 py-1 text-xs font-bold ring-1",cls)}>{label}</span>}
